### ISSUE TITLE
Add telegram message in case of PTF crash

### ISSUE THREAD

**Issue by mehtadone** [mehtadone/PTFeeder#10]
if the app gets stuck for some reason, send a telegram message

**Comment by MetaAtman** [comment]
Or restart

**Comment by RichardLuo0506** [comment]
I would like telegram message even if the market condition didn't change.
I like seeing the change in percentages, and when I don't get a telegram message in a while I'm worried something broke.

**Comment by jalapeno777** [comment]
Indeed....like a message ping every 3 market checks that have remained the same would be nice to ensure the app is always operational.

**Comment by mehtadone** [comment]
Telegram message has been added in case of crash
