### ISSUE TITLE
[REQ] Blacklist Coins that have been added recently to an Exchange

### ISSUE THREAD

**Issue by Q-Rush** [mehtadone/PTFeeder#100]
Hi,

i love pt-feeder. Runs great!
It would be great if we could have a Variable to set like "min_days_added" to determine how long a coin has to be listed on an Exchange before we trade it.

Nearly every coin that gets added to an exchange is fluctuating alot for a few days. Blacklisting it for a few days would be great to be protected agains unnecessary bags.

Here is a great example of this feature: https://github.com/bennettca/binance-auto-blacklist

Apparently we can't run it besides pt-feeder as it would interfere with it!

Thanks in advance!

**Comment by daryledesilva** [comment]
+1 to this. i talked to the guy behind your link, he said he's working on a
plugin for pt-feeder. if pt-feeder itself will add this to their core
engine that would be great! ICOs that just got into the exchange usually
fluctuates ending up in really bad bags that can last for weeks if you dont
want to sell them at loss

**Comment by avalonea** [comment]
Totally would love this!!!

**Comment by mehtadone** [comment]
Daryledesilva, if you can ask the dev to contact me, preferably on discord, I'll work with him to get them working together

**Comment by notnight** [comment]
Sounds like an excellent addition.

**Comment by daryledesilva** [comment]
@mehtadone ok, told @bennettca already. I think he finished his ptfeeder addon just now https://github.com/bennettca/binance-auto-blacklist/issues/1#issuecomment-362763616

**Comment by CryptoKris** [comment]
+1

**Comment by smoochy** [comment]
As we already (and thanks for this big release) have version 1.4, but I did not see it mentioned in the changelog of 1.4, is this still being worked on? You added it to the 1.3.6 milestone, hence I am asking.

Thank you.

**Comment by mehtadone** [comment]
@smoochy still in progress so didnt make 1.4

**Comment by mehtadone** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Coin blacklist](https://trello.com/c/diq87DgX/18-coin-blacklist)

**Comment by smoochy** [comment]
Not sure what it should show, but it is not publicly accessible.

**Comment by mehtadone** [comment]
@smoochy Don't worry about it yet. Didn't realise it would link here too. Just building the roadmap out for releases
