### ISSUE TITLE
TimeOffset

### ISSUE THREAD

**Issue by devonr93** [mehtadone/PTFeeder#108]
The time is correct on my home pc, vps, and Profit Trailer. My issue (I think) is that my PTFeeder time is correct other than the fact that it is in military time so I think the bot is getting confused and says it can't check the server time and to make sure my computer (vps) time is correct and everything is right besides PTFeeder being in military time. My apologies if this is already answered somewhere but I didn't see anything.

https://gyazo.com/9e0332372e4163a13cd0aa5d8f8039ec

**Comment by mehtadone** [comment]
That's just a warning. If there are no issues in running PT Feeder, it's nothing to worry about
