### ISSUE TITLE
[ERROR]Handled exception error: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by smoochy** [mehtadone/PTFeeder#109]
Hi there. 

I had been using PTF successfully for like 4 days. I am running it on a Windows Server 2016 VPS. .net 2.1.4 is installed. Tonight I restarted PTF and since then I get this error message:

![error](https://user-images.githubusercontent.com/34371932/35704986-6d284f10-07a1-11e8-8249-b306d85a815c.jpg)

There is nothing else coming up. This error message is repeating after 5 minutes. There is nothing else written into the log file.

I even copied off PT and PTF to my personal windows machine, installed java and .net freshly and got the same error message.

Any help would be appreciated. Thank you.

**Comment by mehtadone** [comment]
Can you paste your appsettings.json onto pastebin.com and add the link here? I'll take a look

**Comment by smoochy** [comment]
Sure, thanks for the fast response. Would it be ok, if I send you the details of my appsettings via PM in discord? I tried to send you a PM, but it is disabled (for obvious reasons ;)). I am in the PTF install issues channel under smoochy#6365.

**Comment by smoochy** [comment]
Issue was caused by having a

> "MaxTopCoinAverageChange": "-1,5"

instead of

> "MaxTopCoinAverageChange": "-1.5"

Comma instead of a dot.

Thanks for quick support.
