### ISSUE TITLE
can the  .NET SDK work  for 32bit windows 7 computer? i need help!

### ISSUE THREAD

**Issue by runitupp** [mehtadone/PTFeeder#110]
can the  .NET SDK work  for 32bit windows 7 computer? i need help!
i used this link but im not getting a solution. 
https://www.microsoft.com/net/learn/get-started/windows?utm_expid=.-Fmi9Q05Ry2oXQgdtPElHw.0&utm_referrer=

 im not able to Install .NET SDK  .. this is the error...
The installlation package is not supported by this processor type .contact your product vender 0x8007066

**Comment by mehtadone** [comment]
You need dotnet core not .NET sdk. They are two different things. Confusing I know but if you follow the links on the wiki it should get you to the right place

**Comment by runitupp** [comment]
im not sure what im doing wrong, can u help?
