### ISSUE TITLE
Check EMAs for each pair to enable buying

### ISSUE THREAD

**Issue by Tank33au** [mehtadone/PTFeeder#112]
Since PT has no way of measuring a trend of a pair before it buys, I think it would be a fantastic feature for PTF to have.

You could get really complicated but for a start, I want PTF to be able to tell me if fast EMA is above slow EMA before it lets PT to buy a pair.

If a pair doesnt meet above condition, we can put it in SOM.

We should be able to choose a timeframe for candles and period for fast and period for slow just like how its done in PT.

**Comment by fjdelaba** [comment]
That would be a great feature

**Comment by NigglesSquiggles** [comment]
I would love to see this added

**Comment by mehtadone** [comment]
Moved to forum: 

http://forum.ptfeeder.co/t/check-emas-for-each-pair-to-enable-buying/40
