### ISSUE TITLE
PT Feeder License Bot - No response after entering default_apiKey

### ISSUE THREAD

**Issue by Aetherspark01** [mehtadone/PTFeeder#113]
I seem to be unable to register my default_apiKey, everything is successful up until after I paste in the key and press enter (using Binance).

1. Start the Telegram chat with the bot.
2. /manage
3. paste PTFeeder license key, press enter
4. Type 2, press enter
5. Copy and paste the default_apiKey from application.properties (only the api key, no spaces or "default_apiKey =") and then press enter.

I have run through again with option 1 to list my registered API keys, and the bot returns "you haven't added PT api keys".

Any ideas?  Thanks

**Comment by GLock-PPC** [comment]
Same problem here, I am trying to register a second API key and I get no response from the telegram bot.

**Comment by Dantons** [comment]
Same problem here.

**Comment by mehtadone** [comment]
Can you guys contact me on discord

**Comment by Aetherspark01** [comment]
Thanks for the reply, however I am unable to send you a discord friend invite, states you must send me an invite.

Aetherspark#5259

Thanks again for being so involved in helping out!

**Comment by Aetherspark01** [comment]
well....  that’s what i get for doing this on my phone via vnc...

**Comment by Thor788** [comment]
I also can't register my API key with the license bot

**Comment by mehtadone** [comment]
Invite sent aetherspark.

**Comment by Thor788** [comment]
I sent you a request as well Thor78#6663

**Comment by zdewji** [comment]
Hi mehtadone, I also cannot connect. Can you add me on discord? Zdewj#6099
