### ISSUE TITLE
Cryptoprofitbot order cancelled

### ISSUE THREAD

**Issue by EdgarWatkins** [mehtadone/PTFeeder#114]
I received a message that my crypto profit bit order was not filled. I suppose this is becuase I paid the 0.08 bitcoin but after payeer fees only 0.07780050 was received and there is a balance of 0.0021995 which I can transfer immediately. Below are details of my transaction.
Operation date: 01 Feb 2018 17:20
Operation ID: I have this available
Operation type: withdraw
Payment system: BitCoin
Status: success
Debited: 0.08000000 
Credited: 0.07780050
Payeer fees: 0.00019950
Gate fees: 0.00200000 
Account: 1JmuvP8qVEcCepma4CfbzdML6fPTqXKwF6
How do I reach the cryptoprofitbot support team.﻿
Edgar Watkins

**Comment by mehtadone** [comment]
Please contact your seller. I don't sell directly
