### ISSUE TITLE
Feeder reports bittrex candles on binance setting

### ISSUE THREAD

**Issue by efahrenholz** [mehtadone/PTFeeder#115]
When starting up feeder, with a binance configuration, one of the lines states:

Querying bittrex for USDT-(base coin) candles. 

This should be: 

Querying (market) for USDT-(base coin) candles.

**Comment by wpvv** [comment]
Got the same problem. It's not only this line, PTF is also querying bittrex!

**Comment by mehtadone** [comment]
2 separate issues. The USDT is because PTF gets the btc price from the exchange with the most volume. Not necessarily the one you are using.

Querying the incorrect exchange is because you have put your folder location in the wrong place in hostsettings.json
