### ISSUE TITLE
paid but not received my order

### ISSUE THREAD

**Issue by SHAW900** [mehtadone/PTFeeder#117]
Hi can you please check I paid 0.002  5 hours ago but still not received my order?

Order #5925 was placed on February 3, 2018 
Bitcoin Payment Details
Your order total: 0.02000000 BTC
Amount received: 0.02000000 BTC
Payment address: 1J9rHPpXDLXBhMFxhf71672vgvpeirCeQ7
Amount missing: 0.00000000 BTC

1J9rHPpXDLXBhMFxhf71672vgvpeirCeQ7
0.02 BTC

Confirmed Balance
0.02 BTC
Unconfirmed Balance
0.00 BTC
Received
0.02 BTC
Spent
0.00 BTC
Inputs
1
Outputs
0
Transactions

**Comment by mehtadone** [comment]
Hey, please contact your seller as i don't sell directly

**Comment by SHAW900** [comment]
but i don't have contact details 

can you provide please i bought from https://cryptoprofitbot.com

**Comment by jrodder** [comment]
Shaw, this is not the place for that. Please give your order number to
J-ROD on Discord, or send an email to contact@cryptoprofitbot.com.

**Comment by SHAW900** [comment]
Hi

i already 5 hours ago but still not received my order can you please check
:

Order #5925 was placed on February 3, 2018
Bitcoin Payment DetailsYour order total: 0.02000000 BTC
Amount received: 0.02000000 BTC
Payment address: 1J9rHPpXDLXBhMFxhf71672vgvpeirCeQ7
<https://www.smartbit.com.au/address/1J9rHPpXDLXBhMFxhf71672vgvpeirCeQ7>
Amount missing: 0.00000000 BTC

**Comment by SHAW900** [comment]
can you please send discord link ?

**Comment by mehtadone** [comment]
https://discord.gg/Wv86PT
