### ISSUE TITLE
Add "MinutesToMeasureTrend": "" to market conditions under appsettings.json

### ISSUE THREAD

**Issue by CryptoKris** [mehtadone/PTFeeder#121]
Per our conversation in #commons-area

If the condition is not met then the current market is not changed and not set to "default"

Thanks mehtadone!

**Comment by CryptoKris** [comment]
One thing I just thought of with this mehtadone - you will have to add priorities with this per market conditions "configs".  Reason being you could have overlapping trends.  For example, if you use say 60 minutes for "bear" and 720 minutes for "boring" you could be in a bear market within 60 minutes but overall in the 720 minute window in a boring market.  Probably add a line like "priority": "1", in the market conditions in the configs section.

**Comment by mehtadone** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Multiple minutes to measure trend overrides](https://trello.com/c/m0YglCO0/17-multiple-minutes-to-measure-trend-overrides)

**Comment by mehtadone** [comment]
Moved to forum

http://forum.ptfeeder.co/t/add-minutestomeasuretrend-to-market-conditions-under-appsettings-json/39
