### ISSUE TITLE
PTFeeder error, feeder keeps asking me if i register my default api key with ptfeeder license bot.

### ISSUE THREAD

**Issue by raulthinks** [mehtadone/PTFeeder#122]
this error keeps the feeder from running i believe. i gave the bot my license key that i ptfeeder, then registered the api and confirmed that the bot had it saved.

**Comment by puzuzu** [comment]
I am having the exact same issue. I followed the setup guide exactly. Profit Trailer itself is running fine but PTFeeder will not start because it says my API is not valid. Any help here would be great.

**Comment by mehtadone** [comment]
If you place a message on the discord then someone will get back. Can't really share private info like keys on here. https://discord.gg/hrQz4H9
