### ISSUE TITLE
MinBaseCoinPriceChange not working correctly in MarketConditions

### ISSUE THREAD

**Issue by smoochy** [mehtadone/PTFeeder#123]
Hi there, I am not sure if there is a bug with the new pt-feeder-v1.3.5.324 - Build 2 version or that I do have an understanding issue.

I have set sth like this:

```
"MarketConditions": {
    "Configs": [
      {
        "FolderName": "01-superbear",
        "MaxTopCoinAverageChange": "-5",
		"MinBaseCoinPriceChange": "-6",
		"SellOnlyMode": "true"
      },
      {
        "FolderName": "02-bear",
        "MaxTopCoinAverageChange": "-2",
		"MinBaseCoinPriceChange": "-5",
		_conditions_
      },
      {
        "FolderName": "03-boring",
		"MaxTopCoinAverageChange": "1.5",
               "MinBaseCoinPriceChange": "1",
		_conditions_
      },
      {
        "FolderName": "04-bull",
		"MaxTopCoinAverageChange": "3",
		"MinBaseCoinPriceChange": "5",
		_conditions_
      },
      {
        "FolderName": "05-superbull",
		"MaxTopCoinAverageChange": "7.5",
		"MinBaseCoinPriceChange": "10",
		_conditions_
      }
    ]
  },
```
Although BTC is at -2.3894%, the superbear config is used, instead of the bear config. Even later on, as BTC change is positive, it does not switch off superbear config.

![ptf](https://user-images.githubusercontent.com/34371932/35884382-d31d51fc-0b8a-11e8-9b8b-71eaacbf3255.jpg)

As soon as I remove the MinBaseCoinPriceChange from the superbearconfig, it seems to working correctly:

![ptf2](https://user-images.githubusercontent.com/34371932/35884573-6e2de08a-0b8b-11e8-8e26-e701ad3e213c.jpg)

Am I getting sth wrong, or is there a bug included?

Cheers.

/Edit: I think it is still not correct: 
![ptf3](https://user-images.githubusercontent.com/34371932/35885184-595dcaa6-0b8d-11e8-94d4-44e09ab300a6.jpg)

It should have switched to boring mode, no?

/edit2: if I remove "MaxTopCoinAverageChange" from any MarketConditions. It is always putting me into superbear mode

/Edit3: issue is also with pt-feeder-v1.3.5.329 - Build 3

**Comment by mehtadone** [comment]
I think there might be an understanding. 

The top coin change is a maximum and the min base coin is a minimum. This was built on the assumption that when BTC goes up, ALTs go down and vica versa. Agreed that this is not the case at the moment but has been for a while. 

So when you say this: 

  "FolderName": "01-superbear",
        "MaxTopCoinAverageChange": "-5",
		"MinBaseCoinPriceChange": "-6",
		"SellOnlyMode": "true"
      },

You are saying if the top coin change is -5% or lower and BTC change is -6% or higher, then its superbear. When BTC is -2.3894%, it IS higher than -6% hence it is superbear. 

(Reopen if further clarification needed)
