### ISSUE TITLE
Hide excluded pairs?

### ISSUE THREAD

**Issue by dblasi69** [mehtadone/PTFeeder#127]
If I have a coin excluded pairs such as -

"ExcludedPairs": "BNB"

What is the setting to hide these watchonly pairs so they don't show up in my pairs log?

**Comment by dblasi69** [comment]
I see in another Issue thread that the workaround for now is to add ALL_hidden_pairs to the .txt files of each config.  Pairs.txt etc.

**Comment by mehtadone** [comment]
Perfect. Glad you found it
