### ISSUE TITLE
The problem with adding one more market condition.

### ISSUE THREAD

**Issue by clippart** [mehtadone/PTFeeder#128]
Hello mehtadone!
There is a problem when adding one more state of the market and it is this.
Example
      {
        "FolderName": "01-superbearbuy",
        "MaxTopCoinAverageChange": "-6",
        "BuyValueOffset": "-20",
      },

Total market conditions 6

in the logs the following
2018-02-08 03:14:45.521 +07:00 [Information] All prices added to database
**_2018-02-08 03:14:45.783 +07:00 [Information] Top coin change (60 mins) : NaN%_**
2018-02-08 03:14:45.784 +07:00 [Information] BTC change (60 mins) : -0.1285%
2018-02-08 03:14:45.784 +07:00 [Information] USING CONFIG FROM: 01-superbearbuy
2018-02-08 03:14:45.784 +07:00 [Information] Reason: Price could not be calculated

**Comment by mehtadone** [comment]
What exchange are you on?

I think this might be related to https://support.binance.com/hc/en-us/articles/360000713851

**Comment by mehtadone** [comment]
Ahh so it doesn't happen all the time. I can see in your log you got a NaN but then on next check it found the correct folder. This is a known issue. When the exchange throws some incorrect data, PTF can't calculate the top coin change correctly. Trying to work through how to fix this working around exchange limitations.

Am I correct in reading your log correctly? It happens intermittently?

**Comment by clippart** [comment]
> Am I correct in reading your log correctly? It happens intermittently?
yes

**Comment by felipeff** [comment]
FYI I have the same issue on bittrex.  3 min later on the next attempt, it works. But it happens from time to time

**Comment by mehtadone** [comment]
The reason for this is when the exchange didn't return any data, which they all do time to time, we don't know what the market it doing so go safe. I'm add a few retires in a future version but it won't eliminate the problem totally, hopefully reduce it
