### ISSUE TITLE
Request - Exchange being down should not prevent startup

### ISSUE THREAD

**Issue by Dunce001** [mehtadone/PTFeeder#130]
First - Thanks for a great program :)
A suggestion - I've just upgraded to latest version with no issues however I noticed that on startup it checked for connectivity to exchanges. I'm currently using Poloniex and Binance. Since Binance is currently down , of course it could not connect.

PTF then shutdown.  Exchanges are not always going to be available - Surely it would be better to just prevent writing/updating of files for the unavailable exchanges (or even just highlight the lack of connectivity) - rather than shutting down and therefore not continuing to work with the exchanges that it can connect to?

Hopefully that makes sense.

Thanks again for all the teams hard work ... Mark

**Comment by mehtadone** [comment]
Hi Mark, thanks for the issue.

Yes, that would be better. It should be preventing a startup. 

I'll get that fixed

**Comment by Dunce001** [comment]
Fantastic, thanks

**Comment by Dunce001** [comment]
Just to add to this - with the recent/current Binance issues I've noticed that whilst Binance.com is still not resolving - us.binance.com is (and is much faster at the moment). Would it be possible to allow this to be a configurable option as well?
Thanks,
Mark

**Comment by mehtadone** [comment]
Moved to forum: 

http://forum.ptfeeder.co/t/exchange-being-down-should-not-prevent-startup/38
