### ISSUE TITLE
Could not connect to binance 

### ISSUE THREAD

**Issue by Azizg** [mehtadone/PTFeeder#133]
after the binance "update" i updated my PT and PTF all like in instruction, and i got error writing in PTF 
"checking if connectivity to binance is ok"
"could not connect to binance. Has your firewall not got and exceprion for PT" 

i didnt change ports and i addede all ports in and out in excpetions long time ago and it was working please help me

**Comment by mehtadone** [comment]
Duplicate. Check in the PTF discord or: https://github.com/mehtadone/PTFeeder/issues/132#issuecomment-364426627

**Comment by sannyd** [comment]
how do I get to the PTF discord?
