### ISSUE TITLE
Provide a proper way to configure the API URLs used if multiple

### ISSUE THREAD

**Issue by yyyc514** [mehtadone/PTFeeder#134]
Please provide a way to specify the URL. Binding to a DIFFERENT IP address in your hosts file is a BAD idea... those IPs are all temporarily assigned and dynamically dispatched at Cloudflare... they are subject to change - that's what DNS is for.

The software should have a config setting to let you specify which country specific hostname it uses.

**Comment by yyyc514** [comment]
Ref: https://github.com/mehtadone/PTFeeder/issues/132

**Comment by yyyc514** [comment]
I'm told `api.binance.com` is working for PT, why is Feeder not using that URL?

**Comment by mehtadone** [comment]
Because there have been no problems with the other one up until now.

**Comment by r1rider01** [comment]
mehtadone, are you pushing an update?

**Comment by mehtadone** [comment]
@r1rider01 No, there won't be. We either need to wait until www.binance comes back online or use the host file edit workaround

**Comment by boxz0r** [comment]
What is the host file edit workaround? redirect binance.com traffic to us.binance.com ?

**Comment by mehtadone** [comment]
@boxz0r it's shared in the discord. It's a community fix!

**Comment by mehtadone** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Confire api endpoint called by PTF](https://trello.com/c/WaTr1J6t/16-confire-api-endpoint-called-by-ptf)

**Comment by mehtadone** [comment]
Change to use the api endpoint as reccomended by binance
