### ISSUE TITLE
Cant connect to Binance API

### ISSUE THREAD

**Issue by CryptoSophos** [mehtadone/PTFeeder#136]
Please help here since im waiting for days to setup but cant complete..

PT Feeder cant connect to Binex since yesterdays down.
Today same issue, PT works, got 26 PBL and 1 pair in log, also does some trades but the Feeder is not connected.. There is not a problem with the firewall or anything else.. Should i update/change API Keys?

Thanks.

**Comment by CryptoSophos** [comment]
Before Binance was down, it workd perfectly.

**Comment by orionmodern** [comment]
Step 1. Open your Windows start menu, search for the Notepad application and then right click the notepad icon. 
Step 2. Choose “Run as administrator” and then, while inside Notepad, browse to folder (/windows/system32/drivers/etc) that contains the hosts file.
Step 3. Add 54.192.27.29   www.binance.com
Step 4. Save
Step 5. Run Feeder

![unknown](https://user-images.githubusercontent.com/36226590/36036144-ed33d5f4-0d6d-11e8-8236-6914aeb8c0b7.png)

**Comment by CryptoSophos** [comment]
Great this worked now PT Feeder runs but gives multiple WRN - could not calculate long term price change on nearly all pairs.. will try again in the next run..

I renew 3x but still cant calculate, what can i do here to fix?

Thanks.
