### ISSUE TITLE
After installation: Pairs.properties file not updating with feeder settings.

### ISSUE THREAD

**Issue by OatmealTokyo** [mehtadone/PTFeeder#141]
I had to reinstall working PT & Feeder on my Mac.
I deleted pm2 feeder in Terminal on existing App connection.
I reinstalled PT with no issues.
I reinstalled Feeder: 1: SDK no issue, 2: Terminal dotnet pt-feeder.dll (Created new files as necessary) no issue, 3: Node no issue, 4: pm2 start pm2-PT-Feeder.json No issue.  Verified in Terminal: pm2 status pt-feeder it is online.

However in trading folder, Pairs.Properties file is the original file from PT.  I do not see a recent modified date.  Nothing is being written to the file. When I review the file.  It does not show the various bear/bull settings and which current market profile it is running (current boring) as I have notice before.  Is there something I missed on reinstallation?  How do I verify my feeder is running?  It is my understanding it will re-write the PT pairs.properties files and with a warning in the file that changes made will be overwritten by PTF.

PT: Most recent release
PTF Ver: pt-feeder-v1.3.5.329 - Build 3
Exchange:  Binance

Please note I had it working prior with no issues.  Only when I reinstalled everything again.  I had some errors running PTF and reading your issue feed it might of beena corrupt db file.  This is the reason deleted the files and reinstalled. I copy back the original hostsettings & appsettings file as the structure and settings was the same.

Thank you.  FYI You make a great app!

**Comment by OatmealTokyo** [comment]
https://gyazo.com/fbbc37fe7785c37b01c27a799300fe11

**Comment by OatmealTokyo** [comment]
Please note file structure in Finder (mac).  Notice the Date Modified has not changed since installation of PT.
https://gyazo.com/fe6d47e9af73812fd8d8b29cfe7bc327

**Comment by DrewskyJ** [comment]
Were you getting the error that it couldn't connect to Binance before?

**Comment by OatmealTokyo** [comment]
HI.  NO issue with connection to Binance.

It is my understanding the 3 files from PT (DCA, INDICATORS, PAIRS) should be updated periodically from Feeder based on the profiles (bear/bull/boring) in the config folder of Feeder correct?  And all my changes should be done in config folder which at some point will be updated to the 3 files in PT?

**Comment by OatmealTokyo** [comment]
mehtadone H.  I rebuilt my computer and started from scratch again.  For now it looks like no issue.  If this happens again, I will make a new issue post.  Thank you for your time.
