### ISSUE TITLE
TurnsToRegenerateFiles Setting Wrong on Wiki

### ISSUE THREAD

**Issue by Luceid7** [mehtadone/PTFeeder#143]
Tried to set feeder to check pairs every 5 minutes:
"MarketConditionCheckInMinutes": "5",
"TurnsToRegenerateFiles ": "1",

The bot checked every market change and every 5 turns (25 minutes) regardless of what number I put there.

When I changed it to:
"TurnsToRegenerateFiles": "1",

The setting worked as intended. I believe it was the extra space at the end of the word files that messed it up. Seeing as I copied this code straight from the wiki, consider changing wiki documentation for this setting and all others added in 1.3.5 that might have added extra spaces (volatility calc below has same issue).

**Comment by mehtadone** [comment]
fixed. Thank you
