### ISSUE TITLE
API key not registering with licensebot

### ISSUE THREAD

**Issue by xrossovr** [mehtadone/PTFeeder#144]
I have numerously put in the api key from profit trailer into the telegram license bot. When i run the DLL file it says that the api key is not valid and asks if I have added it to the licensebot on telegram.

**Comment by elidovilla** [comment]
I have the same problem. I input my licenses key and the bot does not respond...

**Comment by elidovilla** [comment]
Never mind, got it to work. Checking your licenses key spelling

**Comment by xrossovr** [comment]
I actually got it working. I didnt have the full license key in. I was mossing a character.
