### ISSUE TITLE
The feeder configuration does not match PT

### ISSUE THREAD

**Issue by clippart** [mehtadone/PTFeeder#146]
Can you find out what's going on? =)
![sb](https://user-images.githubusercontent.com/33903011/36060667-75ed298c-0e80-11e8-9274-c879a2e3f701.PNG)

![sb2](https://user-images.githubusercontent.com/33903011/36060670-7c009052-0e80-11e8-8a8c-f29939f0039a.PNG)

**Comment by mehtadone** [comment]
I don't quite understand the question. You've circled a market condition name and then a property

**Comment by clippart** [comment]
The question is, why in the market is there a superbear dca true, when the false is indicated in the ptf?

**Comment by mehtadone** [comment]
Because the dcaenabled = true in the dca file doesn't mean dca is enabled.

You need to look at your pairs.properties and all_dca_enabled and xxxyyy_dca_enabled

**Comment by clippart** [comment]
what do you say to this? som false, dca true...
![sb3](https://user-images.githubusercontent.com/33903011/36060919-3ea033a2-0e85-11e8-9ade-29d97a63ef45.PNG)

**Comment by mehtadone** [comment]
I need to look at your pair overrides further down that page.

**Comment by clippart** [comment]
everything is fine, but after all the global som was included earlier by the indicator, but now it is not, this confused

# Sell only mode activated for market condition


ADABTC_trading_enabled = true
ADABTC_trailing_profit = 0.25
ADABTC_DCA_enabled = false
ADABTC_sell_value = 0.85
ADABTC_sell_only_mode = true

**Comment by mehtadone** [comment]
Even on the market condition SOM, it is each pair overrides which will have som set as true
