### ISSUE TITLE
Max Cost

### ISSUE THREAD

**Issue by AlexeiKirch99** [mehtadone/PTFeeder#148]
Guys, this is showing on my CMD:

![image](https://user-images.githubusercontent.com/36091395/36066939-7b5f0830-0e9a-11e8-82a3-1ff01eee3238.png)

If I change the PAIRS file the feeder will change it...

What can I do?

**Comment by mehtadone** [comment]
You need to make the cost changes in appsettings.json in feeder.

See https://help.cryptoprofitbot.com/kb/fix-max-cost-problems
