### ISSUE TITLE
FTL  An error occurred starting the application

### ISSUE THREAD

**Issue by frank9988** [mehtadone/PTFeeder#149]
![pf](https://user-images.githubusercontent.com/36343895/36067887-0d8eb160-0e96-11e8-96b5-ba6fe96086cf.JPG)

I get my feeder to work on my computer no problem.  Copy and pasted the exact folders to vps, and when i run it, i get this error.  Any ideas how to fix this?

**Comment by mehtadone** [comment]
Does user Frank exist on your VPS? You are logged in as admin. Looks like two different paths.
