### ISSUE TITLE
Curent Value > Pending Value

### ISSUE THREAD

**Issue by Mzzlaza** [mehtadone/PTFeeder#150]
![capture d ecran 2018-02-11 a 22 37 25](https://user-images.githubusercontent.com/36368274/36073537-7fd6c4b0-0f86-11e8-8376-2ea2907871f8.png)

I don't understand. My settings seems great. I also checked on Binance ans I'm curently doing some profits.

**Comment by Mzzlaza** [comment]
Thanks a lot for your work By the way   :)

**Comment by Mzzlaza** [comment]
![capture d ecran 2018-02-11 a 20 14 03](https://user-images.githubusercontent.com/36368274/36073569-1c309976-0f87-11e8-87e8-87b317168b69.png)

**Comment by Mzzlaza** [comment]
But my issue doesn't show up here
![capture d ecran 2018-02-12 a 00 00 24](https://user-images.githubusercontent.com/36368274/36073638-f8bcb1a4-0f87-11e8-911f-9daa5951f4ab.png)

**Comment by mehtadone** [comment]
Hi @Mzzlaza , I can see the issue but this is related to PT and not PT Feeder so there is not much I can do to help. Most likely it is due to pending orders you have on the exchange directly.
