### ISSUE TITLE
Backup PTF files, not PT files

### ISSUE THREAD

**Issue by smoochy** [mehtadone/PTFeeder#153]
Hi there,

I think it would be much more beneficial, if the PTF backup function would actually backup PTF files (the market conditions folders and its content, appsettings.json and hostsettings.json) instead of the files in PT\trading.

Background: changes are only done by the user in the PTF files, not the PT files.

**Comment by mehtadone** [comment]
Mmm if your editing the PTF files manually, how can PTF make a backup of them?

**Comment by smoochy** [comment]
Sometimes I edit things in the appsettings.json which later turn out not to be a smart move. I can not fully remember the more successful settings I used before. If I would have a backup of those settings, I could revert back to them.

**Comment by mehtadone** [comment]
@smoochy I think this is going to be difficult to do. If you don't have PTF running, and you edit your files in notepad for example, then PTF can't back them up. Unfortunately I'm going to have to say no to this issue.
