### ISSUE TITLE
Max_cost set to 0 in pairs.properties when running percentage based figures.

### ISSUE THREAD

**Issue by yobimania** [mehtadone/PTFeeder#154]
Hey guys,

I've been trying to trouble shoot this line that keeps popping up in ProfitTrailer CMD.

I'm sure it's a simple fix, has anyone else encountered it before? My only concern is it's causing me to skip heaps of potential trades.

Other than that, PTF is running like a gem! Cheers in advance!

**Comment by yobimania** [comment]
I'd also like to add that i've triple checked my percentages. The pairs.properties file is being overwritten and the max_cost entry being changed to 0 everytime. Anyone able to explain this?

**Comment by mehtadone** [comment]
@yobimania that is how PTF works. It overwrites your pair.properties files. Have a look at some YouTube videos and a read of the wiki and 
https://help.cryptoprofitbot.com/faq
