### ISSUE TITLE
Constant Errors

### ISSUE THREAD

**Issue by DNation722** [mehtadone/PTFeeder#155]
![screenshot 1](https://user-images.githubusercontent.com/36412538/36102127-3ab98b88-1003-11e8-9a7c-665c4026acad.png)

No one can seem to give a straightforward answer or fix to this issue. My timezones are all synced, and I am even using the Network Time Sync tool. PT-feeder was running fine on my VPS for weeks until out of nowhere it just started crapping out.

**Comment by mehtadone** [comment]
The errors are for coins that are delisted from bittrex. Try deleting your database file and restarting.

Those errors and warnings should have no impact on generating your pairs.properties file however.
