### ISSUE TITLE
[REQ] More price trend offsets

### ISSUE THREAD

**Issue by octobrium** [mehtadone/PTFeeder#161]
Having more price trend offsets would allow us to consider a wider range of market behavior. The 5 minute graph may make it look like a good time to buy, but last week may tell a different story.
Currently, PT Feeder only supports 2 trends, but having more can greatly fine tune our buy and sell decisions.

Basically, the idea is, you want to make decisions based on multiple timelines, not just the 24h or 1h behavior. If the coin has been dipping for the past month, I don't think i would want to rush in to buy it
immediately. Likewise, if the coins has risen or dropped 50% in the past 5 mins
i would wanna avoid the pump n dump. Therefore, multiple trend offsets could dramatically increase profits.

To put this in the bot, it can be as simple as adding another trend offset. Since there are already 2 available trend offsets, I would imagine it is not hard to duplicate a third, fourth, fifth, or more that behave the exact same way. On Binance, there are 11 graph views to watch from: 1m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 12h, 24h, 1W.
Therefore adding up to an additional 9 optional trend offsets should cover every possible need on Binance.

**Comment by mehtadone** [comment]
http://forum.ptfeeder.co/t/more-price-trend-offsets/32
