### ISSUE TITLE
[BUG] Feeder goes into superbear mode due to NaN% from top coins

### ISSUE THREAD

**Issue by dennis2k** [mehtadone/PTFeeder#162]
Bot now and then goes to superbear mode and posts this in my telegram
https://i.gyazo.com/14fa588a3ee7bdae39112906915c105f.png

I happends randomly but many times a day

I have TopCurrenciesToCheck set to 35

**Comment by oblodgett** [comment]
This is a duplicate of #152

**Comment by djbadders** [comment]
+1 and to make it worse it ends up in WATCHMODE on all pairs!!!!

**Comment by mehtadone** [comment]
Duplicate https://github.com/mehtadone/PTFeeder/issues/152
