### ISSUE TITLE
SellOnlyMode = "True" disables all trading not just buying

### ISSUE THREAD

**Issue by djbadders** [mehtadone/PTFeeder#165]
I have SellOnlyMode = "true" in my Super Bear config and I was surprised to see my bot in WATCHMODE for all currencies as it was supposed to switch into sell only mode. It appeared in the pairs config file that ALL_trading_enabled = false and no currencies had been listed, so effectively the bot was not trading.

What I expected was:
ALL_trading_enabled = true
ALL_sell_only_mode = true

Which would have achieved the objective.

Not sure how to achieve sell only mode at present as All_trading_enabled gets added automatically.

**Comment by djbadders** [comment]
This could be the side effect of the NaN bug, as this is how it went into the Super Bear market

**Comment by mehtadone** [comment]
ALL_trading_enabled should be false. That is how PTF works as there should be pair specific overrides.

https://help.cryptoprofitbot.com/faq

Can you check you are configured for the right exchange?

**Comment by djbadders** [comment]
Can you reopen please as this is a bug; I am configured fine and it is the NaN bug causing PF to stop creating the file part way, so no coin pairs are in the pairs file but it still copies the incomplete files over. This is a serious bug as sell opportunities are missed!!!

**Comment by djbadders** [comment]
Surely if there is an exception during the creation of the files it is safer and preferable to leave the existing files in place, so do not copy the incomplete files to PT.

**Comment by mehtadone** [comment]
I can reopen it but you mentioned

What I expected was:
ALL_trading_enabled = true

This is not how PTF works. This will always be false. 

It was not clear that no pairs had been created. 

I'm not convinced that leaving existing files there is a good idea. You say that sell opportunities are missed but if PTF does not know what the market is doing, then you'll be complaining that you ended up with big bags.

**Comment by djbadders** [comment]
It is a tricky situation when something goes wrong; maybe ensuring it is in sell only mode for all pairs is the safest option. I sure it is the NaN bug that is causing this.

**Comment by mehtadone** [comment]
Retry added for NaN in 1.4
