### ISSUE TITLE
Per coin price change failing when "MinutesToMeasureTrend" too high.

### ISSUE THREAD

**Issue by Luceid7** [mehtadone/PTFeeder#166]
I initially tried swapping my minute trends in the hopes of getting the market conditions to read off of a much longer minutestomeasure. I tried this:

"MinutesToMeasureTrend": "1440",
"MinutesForLongerTermTrend": "30",

And a bunch of other scenarios until I came to the conclusion that the bug only presents itself when "MinutesToMeasureTrend" is a larger number than "MinutesForLongerTermTrend".

PT feeder returned errors as in the attached picture:
![screenshot 2](https://user-images.githubusercontent.com/36316714/36281473-c6b24624-126b-11e8-89e7-5cbca16abb3d.png)

In the short term, fixing this bug would be nice, however in the long term, I believe it should be a feature to choose whether market conditions will use "MinutesToMeasureTrend" OR "MinutesForLongerTermTrend" to read data off.

**Comment by Luceid7** [comment]
And on further review, if either number is too large, it will return bad results as well. Setting the short term to 1440 and long term to 2880 both produced errors.

**Comment by mehtadone** [comment]
This is the issue for more customisable trend windows: https://github.com/mehtadone/PTFeeder/issues/121

**Comment by mehtadone** [comment]
version 1.4 should be able to make short term larger than long term
