### ISSUE TITLE
Specific Coin Overrides

### ISSUE THREAD

**Issue by godfodder** [mehtadone/PTFeeder#168]
Discussed this in Disco and realized there is need for a small function addon.

I was looking for a method to set a cost override for specific coins that i wanted the bot to spend more money on in trades.

At first i thought it might work to place these in the the market folders in pairs.txt files as (Binance Example):
AAABBB_max_cost=XXX.XXX

But was informed that this would be overriden by existing common settings into pairs.properties by PTFeeder.

This functionality would allow advanced users to further customize coin specific trades without the need of moving groups of coins to another instance of PTFeeder or another market (lots of work considering all we would want to change is purchase price for pairs.

Ideas?

**Comment by godfodder** [comment]
There is also room in this "coin specific settings" to set a minimum quantity. to avoid trading coins that are being held for longer positions. A lot of people ask about that too.

**Comment by mehtadone** [comment]
So you are asking for a way to manually, and not automatically adjust the max coin per pair. So with feeder you can say for coins more than 1000BTC volume, increase the max_cost by 10% for example. 

Minimum quanity unfortunately is not something feeder can do as PT doesn't support it. If PT adds that feature, I can add it in feeder
