### ISSUE TITLE
How to add PT's new Rebuy_Timeout feature

### ISSUE THREAD

**Issue by NigglesSquiggles** [mehtadone/PTFeeder#170]
How is the new rebuy feature added to Feeder's appsettings file?
I tried to add into the appsettings file:
"DcaRebuyTimeout": "5"
"RebuyTimeout":  "5"

Buy that was a big fat "DIDN'T WORK"

**Comment by dorjedan** [comment]
It should be added to the PAIRs.txt files inside of the market folders.

**Comment by NigglesSquiggles** [comment]
Cool, I guess thats the same for the DCA.txt as well

**Comment by dorjedan** [comment]
Yes, I just edited my previous comment to clarify.

**Comment by mehtadone** [comment]
That's spot on. And you can add it in the common pairs.txt or dca.txt if you have the latest version

**Comment by NigglesSquiggles** [comment]
Thats, awesome, I've just done that, now waiting to see changes populate into the dashboard config
