### ISSUE TITLE
PT Feeder support for ALL_hidden_pairs 

### ISSUE THREAD

**Issue by atka007** [mehtadone/PTFeeder#172]
Want to keep BNB hidden but Feeder keeps un-hiding it. we need PT Feeder support for ALL_hidden_pairs function.

**Comment by dorjedan** [comment]
Add it to the pairs.txt files inside of the market condition folders.

**Comment by mehtadone** [comment]
@doredan is correct

**Comment by atka007** [comment]
thank you.
