### ISSUE TITLE
Trading in ETH and BTC at the same time. 

### ISSUE THREAD

**Issue by cruz1383** [mehtadone/PTFeeder#173]
Is there a way to trade with both btc and eth at the same time or if this is being looked at?? I had some bags that I converted over to ETH manually and made more money with them then btc. Then I traded the eth to btc and made another .40% gain on it but it was manually done.

**Comment by mehtadone** [comment]
Not at the moment. It's complicated as there is no way to translate your bought price from one market to the other. And only really works if you are looking at $ values 

I'd love to do something in the future but the math is pretty tricky. I'll leave this issue open though until I figure out if it is possible and makes sense

**Comment by cruz1383** [comment]
thanks a lot for the insight man. i hope you or someone figures something out on this lol it was an eye opener when i did the trade and made a pretty good gain on it.

**Comment by mehtadone** [comment]
And the gain is dollar value right? If you aren't converted to dollars, and you end game is to grow more btc, how did you work out your gains?

What you are looking for is cross currency arbitrage. There are a couple of other bots that do do it but they are way more complex than PT and PTF

**Comment by mehtadone** [comment]
Unfortunately this isn't going to be possible as cross currency arbitrage will need a seperate bot in its own right
