### ISSUE TITLE
DCA_enabled should be 0 only if DcaEnabled is false

### ISSUE THREAD

**Issue by leoneparise** [mehtadone/PTFeeder#176]
I'm seeing that `DCA_enabled` is set to `0` on some coins even if `DcaEnabled` is not `false`. My default `DcaEnabled` is set to `-1.5` and I have only offset rules (should never be `0`).

 `0` is `false` on ProfitTrailer, removing the coin from DCA.

**Comment by mehtadone** [comment]
Can you paste your appsettings.json on pastebin.com and add the link on this issue?

**Comment by leoneparise** [comment]
@mehtadone: https://gist.github.com/leoneparise/871f0a025a82e4e4e75dc1e43feb2e98

**Comment by leoneparise** [comment]
```
ASTBTC_trading_enabled = true
ASTBTC_trailing_profit = 0.15
ASTBTC_DCA_enabled = 200
ASTBTC_sell_value = 0.675
ASTBTC_sell_only_mode = true
```

This 200 should be only an offset, not the absolute value.

**Comment by leoneparise** [comment]
An example of `DCA_enabled = 0`
```
ADXBTC_trading_enabled = true
ADXBTC_max_cost_percentage = 2.25
ADXBTC_min_buy_balance_percentage = 0
ADXBTC_trailing_profit = 0.15
ADXBTC_trailing_buy = 0.15
ADXBTC_buy_value = 0.285
ADXBTC_DCA_enabled = 0
ADXBTC_sell_value = 0.675
ADXBTC_max_buy_spread = 0.4
ADXBTC_min_profit = 0.75
ADXBTC_min_buy_volume = 300
ADXBTC_min_buy_price = 0.00005
```

**Comment by mehtadone** [comment]
I can't seem to reproduce the DCA_enabled as 200 however. I've made all my longterm price grouping the same as -10 that seems to be where the 200 came from but still getting 0 for AST.

**Comment by leoneparise** [comment]
If you set `DcaEnabled` to `true` in `General` you will get the `200` value. I got the logic, it's the opposit of what I understood from the wiki. If my `DcaEnabled` is `-1.5` and I want to increase `50%`, it should be `-2.0`, not `-0.75`. So, should I put `-50` in the offset to get `-2.0`?

**Comment by mehtadone** [comment]
Ok, so that makes sense for the DCAEnabled. I'll have a think about how to handle that as offsetting "true" by 200% as that is not really a valid thing to do. Whether it should use your offset value as a absolute as it has done questionable. 

Offset calculations are explained in more detail here: https://github.com/mehtadone/PTFeeder/wiki/appsettings.json---Offset-Calculation

**Comment by leoneparise** [comment]
Got it! I didn't read that section. My bad!

@mehtadone thank you for you support! 
I'm closing this issue.
