### ISSUE TITLE
error "MinBaseCoinPriceChange" WHY?

### ISSUE THREAD

**Issue by ccp89** [mehtadone/PTFeeder#177]
[10:59:02 INF] Top coin change (60 mins) : -0.5346%
[10:59:02 INF] **BTC change (60 mins) : -1.5736%**
[10:59:02 INF] USING CONFIG FROM: 02-boring
[10:59:02 INF] Reason: Coin trend is lower than 1%

i have in MARKET CONDITIONS
         +"FolderName": "01-bear",
		"MaxTopCoinAverageChange": "-1",
		"MinBaseCoinPriceChange": "-1",
       + "FolderName": "02-boring",
                "MaxTopCoinAverageChange": "1",
		"MinBaseCoinPriceChange": "1",
        +"FolderName": "03-bull",
                "MaxTopCoinAverageChange": "1000",

WHY is not bear, btc is under  -1%...????
,

**Comment by mehtadone** [comment]
Because MinBaseCoinPriceChange is a minimum. It needs to be at least  -1% which it is not, it is less than

https://github.com/mehtadone/PTFeeder/wiki/appsettings.json---Market-Conditions

**Comment by ccp89** [comment]
but BTC change (60 mins) : -1.5736% is lower, i do not understand, can you give an example please?
thank you
