### ISSUE TITLE
Halt PT trading until all 3 files are updated by PTF

### ISSUE THREAD

**Issue by ITJusus** [mehtadone/PTFeeder#180]
I'm having an issue that during the 10 second span between PTF writing the new PAIRS file and it writing the new INDICATORS file, PT is making bad trades.  This is because my PAIRS offsets change the buy value to be much higher in Bull market conditions, but this only works correctly if my INDICATORS utilizes a much shorter time-frame.  

Unfortunately, because there is a 10 second delay between the PAIRS and INDICATORS being written as well as PT is still free to trade during this mismatched period, the new buy value is applied but to a much longer time-frame...often making it then trade at the top of a shorter time-frame move.

The strategy details are not important, but rather the concept.   There is a 5-10 second period in which bad trades can potentially be made if the PAIRS or DCA files rely on the INDICATORS file contents to be different. 

Please code PT Feeder to temporarily disable all trading in PT until all 3 files (PAIRS, DCA, INDICATORS) are over-written- which typically is about a 15 second period.

**Comment by oblodgett** [comment]
This sounds like a Feeder issue not PT. Feeder could wait before writting the file till it was ready to write all of them at once. I would suggest taking this issue to the Feeder issues tracker rather then here.

**Comment by mehtadone** [comment]
This is the feeder issue tracker. I'll remove the wait in the next version. PT had an issue where it only detected one of the file changes if they were written all at once but I believe that has been fixed now. I'll speak to the PT devs to confirm and remove the wait time

**Comment by mehtadone** [comment]
Timeout removed in 1.4
