### ISSUE TITLE
Some Pairs art DCA Enabled

### ISSUE THREAD

**Issue by AudiInvestor** [mehtadone/PTFeeder#181]
App settings - https://pastebin.com/4AKF9VCA
Pairs file - https://pastebin.com/GvTaXspv
I have been on the discord and no one can help me. Some of my pairs are enabled in DCA and most of the pairs it is buying have DCA set to 0 how do i change this

**Comment by mehtadone** [comment]
The maximum value dcaenabled can be is 0. I can see you from your config that you have a positive offset of 200. -3 increased by 600 will result in 0 because of the max being 0.

I suspect you want those dcaenabled as -200
