### ISSUE TITLE
"MinBaseCoinPriceChange" fault

### ISSUE THREAD

**Issue by ccp89** [mehtadone/PTFeeder#182]
i do not understand it, can you give an example please? what do i have to put, that market change to bear if btc drop under -1%, and market change to bull if btc rise 1+%? cause i put these settings, and says bear?!!?!?! thank you very much.

[10:52:11 INF] Top coin change (60 mins) : -0.1474%
[10:52:11 INF] BTC change (60 mins) : **1.1271%**
[10:52:11 INF] USING CONFIG FROM: 01-bear
**[10:52:11 INF] Reason: BTC price change is higher than -0.1%** ??????

        "FolderName": "01-bear",
		"MinBaseCoinPriceChange": "-0.1",
      {
        "FolderName": "02-boring",
		"MinBaseCoinPriceChange": "0",
      {
        "FolderName": "03-bull",
		"MinBaseCoinPriceChange": "0.1",

**Comment by mehtadone** [comment]
The MinBaseCoinPriceChange is a minumum so the btc price change needs to be higher than this to match a market condition. If you want to btc price to mirror your market, you need something like this:

"FolderName": "01-bull",
	"MinBaseCoinPriceChange": "0.1",
  {
    "FolderName": "02-boring",
	"MinBaseCoinPriceChange": "0",
  {
    "FolderName": "03-bear",
	"MinBaseCoinPriceChange": "-0.1",

**Comment by mehtadone** [comment]
Comments from other issue

**Comment by mehtadone** [comment]
Carrying on from https://github.com/mehtadone/PTFeeder/issues/183 you can still comment on closed issues. They are closed as I believe I have provided a satisfactory answer. If you don't think so, you can still comment or reopen

**Comment by mehtadone** [comment]
If you compare yours to mine, the bull and bear are the other way around. MinBaseCoinPriceChange is a minimum. This means that the btc price needs to be higher than this minimum. In your config, you have said it is bear if the btc price change is higher than -0.1%, which 1.127% is. Hence why it is bear. If you want to have bear when it is lower than -0.1 you need to swap them around like my example

**Comment by mehtadone** [comment]
That is not a problem at all
