### ISSUE TITLE
"MinBaseCoinPriceChange" error

### ISSUE THREAD

**Issue by ccp89** [mehtadone/PTFeeder#183]
Please, can you STOP closing a issue if is not answered? feeder code is incorrect.
i had the same config as you said:

"you need something like this:
"FolderName": "01-bull",
"MinBaseCoinPriceChange": "0.1",
{
"FolderName": "02-boring",
"MinBaseCoinPriceChange": "0",
{
"FolderName": "03-bear",
"MinBaseCoinPriceChange": "-0.1",

and then feedder says:
[11:23:37 INF] BTC change (60 mins) : 1.8868%
**## [11:23:37 INF] USING CONFIG FROM: 01-bear
[11:23:37 INF] Reason: BTC price change is higher than -0.1%**
??????

FEEDER is sayuing bear why?

**Comment by mehtadone** [comment]
Please keep it to one issue
