### ISSUE TITLE
Feeder puts my deep bags in Pending Log

### ISSUE THREAD

**Issue by atka007** [mehtadone/PTFeeder#184]
A few days ago I turned on the Feeder the first time and it put 4 of my deep bags in the Pending Log (up for sale). I tried to cancel it in Binance manually but it put it up for sale again. I didnt bother with it.
I finally sold one of my deep bags this morning. This was in the Pending Log for over 4 days. But it doesn't show up in the Sales Log, so I have no data of the returns in my spreadsheet.
Filed an issue here: https://github.com/taniman/profit-trailer/issues/1167
Their answer is : Pendings do not show in sales currently by design. The bot didn't sell it, so it doesn't track it.
I have three more big bags in Pending Log. Any ideas?

**Comment by mehtadone** [comment]
There is a property called pending_order_wait_time. It will be in your pairs.txt or dca.txt. This puts a coin in pending after a period of time. If you don't want to use this feature you can either use it or use it will combined_cancel_pending_trigger.
