### ISSUE TITLE
feeder issue, I have moved to vps

### ISSUE THREAD

**Issue by pjfj55** [mehtadone/PTFeeder#185]
Hi Mehtadone,
I have attached log and image of screen, telling me I don't have double slash but I do, any help much appreciated, at least it wants to run which is a big plus
thanks 
James
[PTFeeder-20180219.txt](https://github.com/mehtadone/PTFeeder/files/1737791/PTFeeder-20180219.txt)
![img_8037](https://user-images.githubusercontent.com/10498477/36391574-f6d2cda2-159e-11e8-87a7-0ae69a174e9b.JPG)

**Comment by mehtadone** [comment]
Are you sure that path exists on your VPS? It probably won't be the same as your desktop.

**Comment by mehtadone** [comment]
Closing as no response. Reopen if needed

**Comment by pjfj55** [comment]
Sorry Mehtadone, I forgot you when I went to vps as it all worked and I was like a dog with two dicks!, got to VPS and put new path in and it sorted it, thank you for all your assistance and all you do
