### ISSUE TITLE
[Feature Request] MaxTradingPairs calculation change

### ISSUE THREAD

**Issue by harrispp** [mehtadone/PTFeeder#187]
I think that this is more of an issue for PTF rather than PT.

Can we calculate the max trading pairs as all pairs in DCA and PAIRS file excluding those pairs in WATCHMODE.

So that if I wanted to manually trade 4 pairs on the exchange and have ALL_max_trading_pairs = 6 then instead of having only 2 active trading pairs the bot would still look to trade 6 more pairs.

Also if I have one PTF controlling 2 PT instances, where I could have 4 manual trades on Bittrex and 3 manual trades on Binance then the single "MaxTradingPairs": "nn" property within PTF would result in the same number of actively traded pairs on both exchanges.

**Comment by mehtadone** [comment]
Unfortunately this wouldnt be possible for PTF to manage as it doesn't use at of your personal data from your exchange. It is totally anonymous so there is no way of knowing that you are doing manual trades.
