### ISSUE TITLE
PT Feeder error

### ISSUE THREAD

**Issue by bfmfmf** [mehtadone/PTFeeder#188]
[20:39:23 FTL] Malformed json is has been found. Check hostsettings.json and appsettings.json in your config folder. The error is:
Could not parse the JSON file. Error on line number '179': '}
'.

My profit trailer feeder is doing this and I am not sure what the problem is, I have tried getting rid of, adding, or keeping the same with the end brackets. I also tried adding a comma at the end of the brackets but it still wouldn't work.

**Comment by mehtadone** [comment]
Can you paste your appsettings.json on pastebin.com and let me know here

**Comment by bfmfmf** [comment]
{
  "General": {
    "BaseCurrency": "BTC", // MARKET
    "BuyStrategy": "LOWBB", // ALL_buy_strategy
    "BuyValue": "15", // ALL_buy_value
    "BuyValueLimit": "0", // ALL_buy_value_limit used for SPREAD and CROSS strategies only
    "Cost": "0.003", // ALL_max_cost or or All_max_cost_percentage
    "DcaEnabled": "-4", // ALL_DCA_enabled
    "DcaMaxBuySpread": "1", // max_buy_spread in DCA.properties
    "DcaMaxBuyTimes": "5", // max_buy_times in DCA.properties
    "DcaMaxCost": "0", // max_cost in DCA.properties
    "DcaMinBuyBalance": "20", // min_buy_balance in DCA.properties depending on UseMinBuyBalancePercentage in hostsettings.json
    "DcaSellTrigger": "0.6", // sell_trigger in DCA.properties
    "DcaSellStrategy": "GAIN", // sell_strategy in DCA.properties
    "DcaSellValue": "0.75", // sell_value in DCA.properties
    "DcaTrailingBuy": "0.2", // trailing_buy in DCA.properties
    "DcaTrailingProfit": "0.3", // trialing_profit in DCA.properties
    "ExcludedPairs": "BNB", // coins you don't want PTF to create settings for. These will have no config generated and will appear in watchmode
    "SomOnlyPairs": "MTL,DGD,TRIG,MTL,SWIFT,ARDR,SAFEX,BTA,DAR,DRACO,SLING,CRYPT,DOGE,UNO,SC,INCNT,NAUT,SJCX,NOTE,TKN,TIME", // these are coins where BASE_COIN_sell_only_mode will be true
    "DcaExcluded": "", // coins you don't want DCA enabled for no matter what
    "EnabledPairsOnly": "", // coins that you only want to trade. If pairs are in here and the ExcludedList, they will not be traded
    "MaxBuySpread": "1", // All_max_buy_spread
    "MaxTrailingBuy": "0.3", // All_trailing_buy
    "MaxTrailingProfit": "0.3", // All_tailing_profit
    "MinBuyBalance": "50", // All_min_buy_balance or All_min_buy_balance_percentage
    "MinBuyPrice": "0.00005", // All_min_buy_price
    "MinBuyVolume": "500", // All_min_buy_volume
    "MinProfit": "0.55", // All_min_profit
    "MinTrailingBuy": "0.02", // minumum the trailing buy after offsets can be
    "MinTrailingProfit": "0.02", // minumum the trailing buy after offsets can be
    "MinutesForLongerTermTrend": "720", // minutes to measure trend for LongerTermPriceChange
    "MinutesToMeasureTrend": "60", // minutes to measure trend for base coin trend, PriceTrendChange and volatility calc
    "NumberOfPairs": "15", // ALL_max_trading_pairs
    "SellStrategy": "GAIN", // ALL_sell_strategy
    "SellValue": "0.75", // ALL_sell_value
    "TopCurrenciesToCheck": "35" // number of pairs to check from your exchange for MaxTopCoinAverageChange
  },
  "MarketConditions": {
    "Configs": [
      {
        // If the top coins average is less than -1.5%, then go into Sell Only Mode
        "FolderName": "01-bear",
        "MaxTopCoinAverageChange": "-1.5",
        "BuyValueOffset": "-30",
        "SellOnlyMode": "true",
        "SellValueOffset": "-20"
      },
      {
        // Only use the defaults if we are in a boring market - more than -1.5 change and less than 0.5% change
        "FolderName": "02-boring",
        "MaxTopCoinAverageChange": "0.5"
      },
      {
        // Increase the buyvalue if we are in a bull market. More than 0.5% and less 1000%. This is a catch all as in the market conditions, you need a section for all scenarios.
        "FolderName": "03-bull",
        "MaxTopCoinAverageChange": "1000",
        "BuyValueOffset": "2"
      }
    ]
  },
  "Volume": {
    "Configs": [
      {
        // For any coins with a volume of less than 500 BTC, then increase the trailingbuy by 10% and reduce the trailing profit by -20%
        "MaxVolume": "500",
        "TrailingBuyOffset": "10",
        "TrailingProfitOffset": "-20",
        "DcaEnabled": "-20"
      }
    ]
  },
  "PriceTrendChange": {
    "Configs": [
      {
        // if a coin has dropped more than -5% in  "MinutesToMeasureTrend": "60", then go sell only mode and drop the SellValue by 20%
        "MaxPriceTrendPercentageChange": "-5",
        "SellOnlyMode": "true",
        "SellValueOffset": "-20"
      },
      {
        // if a coin has changed between -5% and 0.5% then increase the TrailingProfit by 5% and reduce the TrailingBuy by -70%
        "MaxPriceTrendPercentageChange": "0.5",
        "TrailingBuyOffset": "-70",
        "TrailingProfitOffset": "5"
      }
    ]
  }
}

**Comment by mehtadone** [comment]
What's the error?

**Comment by bfmfmf** [comment]
using copypastebin i would rather go this route these are not the same settings as the one that wasn't working. this is working on getting the bot running but its been more than 24 hours its added 6 more dust and no sales. if you can help me change some settings that would be nice

**Comment by mehtadone** [comment]
I can't help on settings. This is up to the user. There are other users that do share their settings which you are also free to use but we always recommend setting feeder up based on your own risk profile

**Comment by bfmfmf** [comment]
i have been to wiki many times its been almost daily for 3 weeks now and i have only earned $33 in trade altogether and went from .0662354 btc to a total value of .0564795 btc I know you or anyone else has control of the markets but if theres anyway to avoid so much dust that would be helpful i do have bnb coins and it turn on to pick up fees so anything you could suggest would  I SEE
