### ISSUE TITLE
Pais Max Cost Setting

### ISSUE THREAD

**Issue by jwk27** [mehtadone/PTFeeder#190]
I consistently have this spamming logs

INFO ProfitTrailerService - Cannot buy XXXXXX. Please increase max_cost to approximately 0.001!

I have to manually edit the PAIRS config in Profit Trailer every 10 mins before my bot can make any buys or sells.

**Comment by mehtadone** [comment]
Have a read of this

https://help.cryptoprofitbot.com/kb/bot-not-buying#ch_6

**Comment by mehtadone** [comment]
Either turn off percentages in hostsettings.json or put in a valid % amount

**Comment by jwk27** [comment]
Why do I have to turn off the %, when the percentage is supposed to run with whatever amount I have and is also remaining in my bal.

**Comment by mehtadone** [comment]
@jwk27 Becuase the exchanges have a minimum amount you can trade. If the % of your Total Current Value is less than 0.001 in this case, then you will get that max_cost error.

**Comment by jwk27** [comment]
Ok i have a minimum bal of this on PT 0.00220495 BTC

How come it keeps saying "Please increase max_cost to approximately 0.001!"

I am running Profit trailer + Profit Feeder together

**Comment by jwk27** [comment]
Also is it possible you have a look at my logs and settings?

Please so that you can provide me with some assistance

**Comment by mehtadone** [comment]
Can you paste your appsettings.json and hostsettings.json to pastebin.com without any sensitive info like your license keys?

**Comment by jwk27** [comment]
appsetings   https://pastebin.com/ipyWNjWK

hostsettings https://pastebin.com/VSqYPsbu

**Comment by jwk27** [comment]
Hello

**Comment by mehtadone** [comment]
What is your total current value from your PT monitoring page?

**Comment by jwk27** [comment]
Thanks Methadone for the wonderful care and time 

however, due to the delay, I switched to ETH this morning. 

I am currently halfway through the configuration. when I am done and it is working I will provide feedback

**Comment by Cryptoj** [comment]
hello, was wondering if you figured out the configuration

**Comment by jwk27** [comment]
Yes I did, thanks for the help
