### ISSUE TITLE
Profit trailer is not hitting DCA after I started running feeder

### ISSUE THREAD

**Issue by Wezz777** [mehtadone/PTFeeder#191]
Profit trailer is not hitting DCA after I started running feeder. I double checked the settings and cant find anything wrong. See attached appsettings

[appsettings copy.txt](https://github.com/mehtadone/PTFeeder/files/1743908/appsettings.copy.txt)

**Comment by mehtadone** [comment]
Can you check your PT logs to see if there are any warnings there?

**Comment by Wezz777** [comment]
ja it says the spread is too big.. must be a bad time right now..
Thanks

**Comment by mehtadone** [comment]
Also check your max_spead in your dca.properies file that feeder has generated. DcaMaxSpread is the property in appsettings.json in Feeder that generates this.
