### ISSUE TITLE
Calculate Volatility every cycle

### ISSUE THREAD

**Issue by mehtadone** [mehtadone/PTFeeder#193]
Calculate Volatility every cycle rather than every 100.

**Comment by Mtrade** [comment]
Calculation every cycle is ideal. But if the calculations might be resource or time intensive perhaps allow for a "TurnsToRegenerateVolatility" setting in hostsettings so people can tailor this to their liking.

As a side note, if setting volatility to calculate every cycle makes it necessary to perform more time-consuming calculations when PTFeeder first starts up, I think the longer wait time is an acceptable tradeoff for those that would use this feature.

**Comment by mehtadone** [comment]
The issue is not when starting up, it's that it will take the same time as startup each time that the volatility is calculated at the moment. This is bring rearchitected however

**Comment by mehtadone** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Calculate volatility every cycle](https://trello.com/c/0qHYVfdB/14-calculate-volatility-every-cycle)

**Comment by sannyd** [comment]
is there a way to "force" volatility recalculation? restarting PT Feeder does not seem to do it.

**Comment by mehtadone** [comment]
The volatility calculations are done when the full set of candles are queried from the exchange. On a PTF restart, we check to see if we have the latest candle set in the db, and if we do, we don't query the exchange again.

So you have two options. Close PTF and wait 10 mins. Or close PTF and delete the db file.

On a second note, in the next version, the candles are not being stored to the database so volatility will be checked on every cycle

**Comment by sannyd** [comment]
Thanks so much for the quick reply/explanation!  Great product!

**Comment by Mtrade** [comment]
Is there a planned release before 1.4.1 to include this then? Only asking because I see the issue is closed but not transferred to 1.4.1 milestones.

**Comment by mehtadone** [comment]
Sorry, I didn't mean to close it.

**Comment by mehtadone** [comment]
Dev complete and will be in next version
