### ISSUE TITLE
PTv1.2.6.16 + PTFv1.4.0.431 dont work

### ISSUE THREAD

**Issue by Kakos95** [mehtadone/PTFeeder#194]
Hello mehtadone, could you please help me out? I have PT over a week now I use v1.2.6.16. Yesterday I purchased PT Feeder and downloaded latest v1.4.0.431. I configured it and run it. Well, after 24 hours it did 0 trades. In my opinion it is because I have EMASPREAD -2 but Indicators are EMA 2 and EMA 4 (INDICATORS are Feeders work). Is it posiible that I have configured Feeder wrong? Or is just the market situation bad that not even bot trades? :D thank you

![image](https://user-images.githubusercontent.com/36712232/36503072-3d27b818-174c-11e8-96e4-8f2ee96a72e5.png)
![image](https://user-images.githubusercontent.com/36712232/36503121-68a60bfc-174c-11e8-9c4d-d680dc4e5dd3.png)

**Comment by mehtadone** [comment]
What indicators were you using before PTF? You can set them in indicators.txt in your config/market condition folders? And what BuyValue were you using before PTF? -2 as well?

**Comment by Kakos95** [comment]
I used EMA 13 (fast) and EMA 34(slow).  I used EMAGAIN before. I want to try EMASPREAD now, since every youtuber who use PTFeeder use EMASPREAD. EMA 2 and 4 is default for every PTF release? Is it bad that I run PT and PTF on my local machine instead of VPS? (I have mining rig which runs 24/7) Thank you for your support :-)

**Comment by mehtadone** [comment]
Well you can't really compare with and without if your settings are totally different!

I can't remember off the top of my head what is default but you can check by looking in your indicators.txt file. 

But if you were happy with EMAGAIN, why not just run with that?
