### ISSUE TITLE
PT Feeder keeps turning off all trading.

### ISSUE THREAD

**Issue by FredCole** [mehtadone/PTFeeder#195]
My PT Feeder keeps changing my "all_trading_enabled" to false. I have tried to change this configuration in Profit Trailer and through the configs options on my Profit Trailer dashboard, after which, in both cases the settings were saved. Whenever I change it to true, to enable all trading, feeder goes back to make it false. I have also tried to find out the answer myself but to no avail I couldn't find it. Please help.

Thank you,

Fred

**Comment by mehtadone** [comment]
It should be false. 

Each pair in your pair.properties has an override for BTCLTC_trading_enabled = true for example.
