### ISSUE TITLE
ProfitTrailerFolder Override Groups?

### ISSUE THREAD

**Issue by ssbn** [mehtadone/PTFeeder#199]
Would it be possible to get an override group that works like the Exchange one, but for the Profit Trailer folder configs themselves?

I would love to be able to do this:

`
"ProfitTrailerFolders": {
     "Configs":     {
     {
          "ProfitTrailerFolder": "1",
          "BaseCurrency": "BTC"
      }
`

**Comment by mehtadone** [comment]
Unfortunately not. PTF is written to work with one market. That is why it can stay pretty lightweight and work on things such as the pi. 

If you need to work with a different market, you need to run two instances of PTF>
