### ISSUE TITLE
be able to manually override or set market conditions

### ISSUE THREAD

**Issue by abien** [mehtadone/PTFeeder#20]
I would like to be able to manually control (or override) the market conditions.
This may be useful if (among other reasons) i assume to know the market is gonna turn and i want my bots to switch to superbear.

The override should either stay in place until cancelled or should be equipped with a timer in minutes.
ex: goto superbear for 4320 minutes (3days). After the times is expired - it would go back to whatever the market conditions are at that time.

**Comment by Dunce001** [comment]
I would love this too...

**Comment by tvsmvp** [comment]
Ditto!

**Comment by tulihub** [comment]
@abien @Dunce001 @tvsmvp 

I would suggest you use this tool: https://github.com/tulihub/moonbot

**Comment by mehtadone** [comment]
As mentioed, for manual actions, I would reccomend Moonbot
