### ISSUE TITLE
Pt feeder settings and installation

### ISSUE THREAD

**Issue by NIKHILMBL** [mehtadone/PTFeeder#200]
NIKHIL GUPTA:
Sir,
I have purchased license key for both profit trailor as well as feeder
Iam new with pt feeder,i have read all the instructions about how to install pt feeder in wiki
I have also downloaded latest version of pt feeder
But i want to ask u whether i need to change all the settings of appsettings.json and hostsettings.json in new version of pt feeder downloaded or simply add my path of pairs folder ,license key ,telegram bot to host settings
Plz guide me as iam very confused

**Comment by mehtadone** [comment]
YOu only need to change the settings in hostsettings.json to match your install. You can then change appsettings.json as you understand them
