### ISSUE TITLE
Question about the way how it calculates top coin changes

### ISSUE THREAD

**Issue by Liliniser** [mehtadone/PTFeeder#203]
Hello.

I don't really understand the way of calculating top coin changes. I'm trading on Binance with USDT currency and the market is going down for almost 60 hours at the moment.

![bb](https://user-images.githubusercontent.com/438474/36570914-a863186c-1877-11e8-9e9c-aeed4447f21d.png)

I set "MinutesToMeasureTrend" to 720 in appsettings.json. Now I'm expecting that "MaxTopCoinAverageChange" on MarketCondition group should be around -4% ~ -5%, but it is only -0.05%

![2018-02-23 8 56 51](https://user-images.githubusercontent.com/438474/36570899-8fdd79ae-1877-11e8-9d21-721ed8fe5d17.png)

Have I missed something? I need better understanding, please help me.

Thank you

**Comment by mehtadone** [comment]
MaxTopCoinAverageChange takes the change of the top coins and averages them, so it is not an indicator of what USDT/BTC is doing but all USDT pairs.  

That however does seem quite low, so I'll investigate if there is some edge case with USDT.

**Comment by mehtadone** [comment]
Can you now try with version 1.5
