### ISSUE TITLE
An assembly specified in the application dependencies manifest (pt-feeder.deps.json) was not found:

### ISSUE THREAD

**Issue by raenrfm** [mehtadone/PTFeeder#204]
Setting up a Ubuntu 16.04 VPS with feeder.  Installed dotnet sdk 2.1.4 and when I try to run feeder for the first time I'm getting this:

dotnet pt-feeder.dll
Error:
  An assembly specified in the application dependencies manifest (pt-feeder.deps.json) was not found:
    package: 'services', version: '1.1.33'
    path: 'lib/netcoreapp2.0/services.dll'

I tried re-installing dotnet with no fix.  Can someone tell me if this is a bug?

**Comment by mehtadone** [comment]
Have a look if that file "services.dll" is in your folder and if it is also spelt correctly, with a small s. Its not a bug, it normally happens with either a corrupt download of the zip or an existing file still there from an old version.
