### ISSUE TITLE
PTFeeder on Mac error

### ISSUE THREAD

**Issue by orionmodern** [mehtadone/PTFeeder#205]
[20:11:32 FTL] Malformed json is has been found. Check the json files in your config folder. The error is: 
Could not parse the JSON file. Error on line number '3': '"General": {
"BaseCurrency": “USDT”, // MARKET'.

**Comment by Liliniser** [comment]
This happens because of “
Look carefully, it must be     "    NOT   “

**Comment by orionmodern** [comment]
I didn't change the original file " NOT “. Should I replace all those symbols?

**Comment by orionmodern** [comment]
yeah that didn't work =/

**Comment by orionmodern** [comment]
and this:

[20:46:12 FTL] Malformed json is has been found. Check the json files in your config folder. The error is: 
Could not parse the JSON file. Error on line number '4': '"ProfitTrailerFolder1": "/Users/tc/Desktop/ProfitTrailer/trading", // add your in one or more PT folders below, where ths application.properties file is. Note that windows users must add \\ in between the folders, NOT \
"HostName": “PT Feeder", // the name that is used on telegram messages'.

**Comment by Liliniser** [comment]
> "HostName": “PT Feeder", // the name that is used on telegram messages'.

Again, “ here
Trust me, it's because of them
You'll probably want your mac not to use “ all the time

http://www.iclarified.com/38772/how-to-disable-curly-quotes-in-mac-os-x-mavericks

This site will help you

**Comment by orionmodern** [comment]
ah! thank you so much. it was those curly quotes!
