### ISSUE TITLE
host file ServerUrls not in latest version... Is this a problem if running two instances on one machine?

### ISSUE THREAD

**Issue by TheBigShort111** [mehtadone/PTFeeder#206]
I'm in the process of updating to the latest version, however I run two instances on the same machine and have had to use two different server urls in the past for them to both run... I notice this line is missing from the latest version, so I am wondering if there will be a conflict, or has this line of code been depreciated?

"ServerUrls": "http://localhost:5001", // Nothing at this website yet. Don't change the port in this line unless there's a good reason. Especially DO NOT set it to the same port as your Profit Trailer is on.

Also, it is mentioned to delete the database when installing the latest version... What information will I lose during the database replacement, if any?

Thanks to anyone that can help

**Comment by mehtadone** [comment]
You can add this line back into hostsettings.json. It has been made optional and only required to change it if you have a port clash: 

"ServerUrls": "http://localhost:5001",
https://github.com/mehtadone/PTFeeder/wiki/hostsettings.json#serverurls-leave-default

**Comment by TheBigShort111** [comment]
What about the database replacement?... Will I lose any data, or history when I delete it?

**Comment by mehtadone** [comment]
@TheBigShort111 no, it is queried again on start
