### ISSUE TITLE
DCA will not buy due to low volume error

### ISSUE THREAD

**Issue by vincev1975** [mehtadone/PTFeeder#208]
I have set  "DcaBuyAvailableVolumeTrigger": "100",  in appsettings and for 3 days since updating to the latest PTF version I am getting this error.  XRPBTC has very high order volume so this should not be an issue.   Can you fix please?

https://www.screencast.com/t/s1yoPXQJ

**Comment by mehtadone** [comment]
Can you show me the dca.properties file?

**Comment by vincev1975** [comment]
Hi, Yes I have attached the PTF DCA.txt file.  Please let me know if this can be fixed. Thanks 
____________________________________________________________
How To Remove Eye Bags & Lip Lines Fast (Watch)
Fit Mom Daily
http://thirdpartyoffers.juno.com/TGL3131/5a92d28f235fa528e123est01vuc
#BUY SETTINGS #2

buy_strategy = ANDERSON
buy_style = DOUBLEDOWN
buy_trigger_1 = -4.5
buy_trigger_2 = -7.5
buy_trigger_3 = -14.5
buy_trigger_4 = -19.5
buy_trigger_5 = -25.5

stop_loss_trigger = -25
pending_order_wait_time = 0
ignore_sell_only_mode = false
min_buy_volume = 100

**Comment by mehtadone** [comment]
I need to see your dca.properties from PT not your dca.txt as that file is the one that PT is using to do dca buys

**Comment by vincev1975** [comment]
Sure.  Here it is.  
____________________________________________________________
1 Simple Trick Removes Eye Bags & Lip Lines in Seconds
Fit Mom Daily
http://thirdpartyoffers.juno.com/TGL3131/5a934e57efb3a4e574a9cst03vuc

**Comment by mehtadone** [comment]
Hi, 

Unfortunately the attachment didn't attach.

**Comment by mehtadone** [comment]
Closing for the time being. Re-open if still an issue
