### ISSUE TITLE
[REQ] Buy strategy override enhancement

### ISSUE THREAD

**Issue by Mtrade** [mehtadone/PTFeeder#210]
Allow for an "AND" condition to combine offset groupings for a buy strategy override. 
For example: [If Price is < 0.1 AND Volume < 10000 AND PriceTrendChange < 5], apply buy strategy override.

For a given buy strategy override, have an option to disable applying existing BuyValue offsets and/or be able to apply a different set of BuyValue offsets (i.e. user may want to adjust offsets when a buy strategy changes from EMAGAIN to LOWBB for example.)

**Comment by Mtrade** [comment]
Is this still possible from a development perspective? Overrides would be much more useful if checking for two or more criteria/groupings before applying a buy strategy change. 

For example, if short-term price trend AND long-term price trend are above/below set levels, apply a more aggressive or more conservative buy strategy.

**Comment by mehtadone** [comment]
Undocumented, but try this on Feeder 1.5:

```
  "MTradeGrouping": {
    "Condition": "[pair.LongerTermTrendPercentageChange] > [config.MinPriceChange] && [pair.PercentageChange] > [config.MinPriceChangeLongTerm]",
    "Configs": [
      {
        "MinPriceChange": "0.5",
        "MinPriceChangeLongTerm": "0.5", //rsi
        "ASellValueOffset": "-50", // gain
        "Override": {
          "ABuyStrategy": "SMACROSS",
          "Weight": "60"
        }
      }
    ]
  },
```

Feel free if to message if you want more info on how this works.

**Comment by Mtrade** [comment]
Thanks, I will experiment with this.

Are the "MinPriceChange" and "MinPriceChangeLongTerm" terms just created ad hoc within this config?

**Comment by mehtadone** [comment]
Yes, in the condition, anything that is config.XXXX, the XXXX needs to be in the config

**Comment by Mtrade** [comment]
Thanks, the logic appears to be functioning.

Is there any way to ignore all offsets when applying a buy strategy override? 
When applying a new strategy based on specific conditions like this I don't necessarily want any of the offsets I have setup for EMAGAIN or EMASPREAD to be applicable to a LOWBB or STOCH buy strategy for example.

**Comment by mehtadone** [comment]
There is no way to do that but I'd probably suggest using overrides for anything buy value related in this case, not offsets. Would that work?

**Comment by Mtrade** [comment]
I'm not sure it would. I have PTFeeder setup to behave under normal conditions with a set strategy, applying various offsets to buy_value depending on market conditions, price trends and volatility levels, relying on their 'interactions' with each other.

The idea here was to apply a completely different entry strategy if certain set, specific criteria/conditions are met, and so most or all of the defined offsets for the original strategy would not be necessary or applicable. (e.g. I wouldn't want to apply the volatility offsets defined for the original strategy to the override strategy)
I will think of a workaround.
