### ISSUE TITLE
Exchange offsets not working as expected

### ISSUE THREAD

**Issue by bluefuzz** [mehtadone/PTFeeder#211]
I have `"MinBuyVolume": "750"` in my General section. I then have an exchange grouping set up for Bittrex with `"MinBuyVolumeOffset": "-50"` which reduces the volume to 50% (375). It is the first grouping after the general section (if that matters).

For enabled pairs this apparently works fine, eg. for Ether I get `BTC-ETH_min_buy_volume = 375`. However many of the SOM pairs are being disabled solely due to volume lower than 750. 

Eg. for Lisk:

```
# Sell Only Mode Reasons:
 # Pair volume 531.2633072 is less than the min buy volume of 750
```

Since this is higher than 375 it should not be disabled as Lisk doesn't have any other criteria to put it in SOM as far as I can see. So not working as expected ...

**Comment by mehtadone** [comment]
confirmed this is an issue and will fix in 1.4.1
