### ISSUE TITLE
Spaces in JSON

### ISSUE THREAD

**Issue by bluefuzz** [mehtadone/PTFeeder#213]
I couldn't understand why my PTF was in 'bull' mode when it should have been 'boring'. Then I noticed I had a space in one of the parameters like this: `"MaxTopCoinAverageChange ": "2"`in my 'boring' section. Notice the space before the second double-quote. This resulted in PTF ignoring this section completely. This was not caught by running the config through a JSON linter as it is still valid JSON. And PTF happily eat the config without any error or warning.

I take it that PTF ignores any extraneous spaces in both keywords and values? This should probably be noted on the wiki somewhere in big letters. Even better if PTF could throw a warning if it encounters extra space it doesn't understand ...

**Comment by muratssu** [comment]
Do you think the true way is like :
"MaxTopCoinAverageChange ":"2"  ??

ALl my configs have space before the second quote

**Comment by bluefuzz** [comment]
@muratssu I think you misunderstand. I'm talking about the space *at the end* of the keyword "MaxTopCoinAverageChange " before the second quotemark. If there is a space there the whole section apparently gets ignored. Spaces around the colon don't matter - or shouldn't according to the JSON spec.

**Comment by muratssu** [comment]
Ok. Now i understood.  it makes sense now.  Thanks

**Comment by mehtadone** [comment]
Hey @bluefuzz , removing spaces is going to be tricky to do due to the way the json is converted into .net objects. A bit technical but for the meantime, I'm going to have to suggest checking your json files carefully. 

In the longer term (hopefully 3 or 4 weeks from now) there is a gui coming to avoid editing the json file at all which will avoid these types of errors.

**Comment by bluefuzz** [comment]
I thought it might be tricky. I posted it as much as a warning to anyone else who can't understand why their settings aren't doing what they expect them to be doing. I look forward to the gui, but in the meantime it might be an idea to mention it on the wiki. It may save you a few support calls ... ;-)

**Comment by mehtadone** [comment]
@bluefuzz added in common errors page! Thanks

**Comment by muratssu** [comment]
Hi Mehtadone;
I am also looking forward for the gui. That was what i was thinking for a few weeks.
Actually i seperated and tidyied the appsettings.json file. Also translated the comments with //  to understand in a better way. 
But with the new update, i noticed that there is not enough data for the new features. For example : buy strategy overrides. This is what i was trying to do during last one week with the older version. On the github, there is only one syntax example for this. Beyond this, there is a parameter called "weight" which i am trying to understand myself.
İf there was more communication with us and software it would be better. Maybe a discord channel or sth? To ask other people.

İ am sure that you are very busy and we appreciate it
 İ am an engineer but not good in programming. İ am trying for long time to understand all these better. We should have more detailed documents with examples of atleast the new features.

Thanks for your understanding.

Murat

**Comment by mehtadone** [comment]
@muratssu There is a discord. It can be found on this page: https://help.cryptoprofitbot.com/start/
