### ISSUE TITLE
Exchange Offsets not working at all for me

### ISSUE THREAD

**Issue by Dunce001** [mehtadone/PTFeeder#214]
Hi - First- Thanks for  the continued updates and efforts being put into PTF :) 
I was previously running two instances of PTFeeder to be able to provice different settings to each exchange - so this latest update is just the job - I can now run one instance with different exchange settings - thank you.

Sadly however the Exchange Offsets do not seem to be working for me.
In my hosts file I have Binance and Poloniex:

 _"Host": {
"ProfitTrailerFolder1": "C:\\inetpub\\websites\\ProfitTrailer\\Poloniex", 
"ProfitTrailerFolder2": "C:\\inetpub\\websites\\ProfitTrailer\\Binance",_

**And in my App Settings I have added the exchange configs:** 

_...
    "MinBuyBalance": "10" 
  },
  "Exchange": {
             "Configs": [{
                 "ExchangeName": "Binance",
                 "MinBuyBalanceOffset": "10" // offset from default value of 10. [ should now be 10+10=20]
               },
               {
                 "ExchangeName": "Poloniex",
                 "MinBuyBalanceOffset": "15" // offset from default value of 10. [ should now be 10+15=25]
               }
             ]
          },
  "MarketConditions": {
..._

**But nothing gets changed in the Pairs folder for each exchange.**

Both the Poloniex and Binance Pairs file (as taken from live "Config") still read:
_ALL_min_buy_balance_percentage = 10_

**Comment by mehtadone** [comment]
The exchange offsets are being applied to the pair overrides. So 

LTCBTC_min_buy_balance_percentage should have the exchange override applied which is the one that matters. 

This is however, on the ones that do have pair specific overrides. There are some where it is not being applied. This is being tracked here: https://github.com/mehtadone/PTFeeder/issues/211
