### ISSUE TITLE
USDT Pairs not querying, not grabbing correct TopCoinChange or DCA'ing

### ISSUE THREAD

**Issue by kendog819** [mehtadone/PTFeeder#218]
[appsettings.txt](https://github.com/mehtadone/PTFeeder/files/1756706/appsettings.txt)

Spoke with Collibhoy and J-Rod and have been asked to post here.

Changing market to USDT, Pairs consistently stay at 0 of 6 queried
It seems as if the data is possibly being grabbed, but not being shown that it is

Have changed "TopCurrenciesToCheck": from between 1 and 6.
1 shows me 0% constantly, 6 starts throwing me other errors 

Cannot get anything to DCA for me and Market Conditions never change
. Yet pairs will buy and sell.

![unknown 1](https://user-images.githubusercontent.com/11353628/36645175-e2b139d8-1a32-11e8-8f87-6326fe571cae.png)
![unknown 1](https://user-images.githubusercontent.com/11353628/36645193-0273be44-1a33-11e8-9e9c-45fb4aa3f0af.png)
![unknown 1](https://user-images.githubusercontent.com/11353628/36645206-2a971132-1a33-11e8-8016-5c2e88cf118c.png)
![unknown 1](https://user-images.githubusercontent.com/11353628/36645214-47c3b79c-1a33-11e8-979a-0228992a5b33.png)

**Comment by mehtadone** [comment]
Can you attach your appsettings.json to this issue?

I can help fixing the issue of the 0% top coin change when setting the top coins to 1. Can you point me to the error that gets shown when its 6? 

I think the pairs are being queried correctly, its that the log doesn't show when its done.

**Comment by kendog819** [comment]
I added appsettings to the OP as a .txt file, as Github doesn't allow you to upload .json files to posts apparently. 

The errors I was referring to when setting top coins to 6 was the different price mismatch messages, that only started happening when setting to 6.

**Comment by mehtadone** [comment]
That wouldn't affect the bought price as that is internal to PT. Nothing PTF or any other add on can do to affect that.

I know that some of the PT support staff probably and you back here so I'll see if I can speak to them. 

The issue on PTF I can see that I'll need to fix is when you have only 1 top coin to query and it doesnt get the right top coin change as per your first screenshot

**Comment by mehtadone** [comment]
One other thing that would be handy is your dca.properites file that PTF generated. I can see if there is anything that is missing in there

**Comment by kendog819** [comment]
I just changed back to USDT after running BTC market all day, then this. 
![image](https://user-images.githubusercontent.com/11353628/36648439-b83da0b8-1a61-11e8-9548-95d25b858a82.png) It is definitely attributed to USDT somehow

**Comment by kendog819** [comment]
[DCA_Properties.txt](https://github.com/mehtadone/PTFeeder/files/1756884/DCA_Properties.txt)
 Collinbhoy was trying to help me the most, he would probably be most helpful to speak to.
