### ISSUE TITLE
ETH Pairs not DCAing

### ISSUE THREAD

**Issue by geeklingo** [mehtadone/PTFeeder#220]
Might be related to https://github.com/mehtadone/PTFeeder/issues/218 as similar behaviour to USDT pairs.

Even though DCA is enabled in the config, all the pairs are being written to the PT config files as: xxxETH_DCA_enabled = false. So DCA never actually kicks in.

**Comment by mehtadone** [comment]
Can you attach your appsettings.json please?

**Comment by geeklingo** [comment]
I think I sorted it. New setting in 1.4

 

Kind Regards,

Noeneel Sharma

Executive Editor

https://www.geeklingo.net
