### ISSUE TITLE
BuyValueOffSet error

### ISSUE THREAD

**Issue by jrischma** [mehtadone/PTFeeder#222]
Hi, with this:

"BuyValue": "-0.89", 
"BuyValueOffset": "-15"

i get -0.13 (0.89 x 0.15 = 0.1335)

on https://github.com/mehtadone/PTFeeder/wiki/appsettings.json---Offset-Calculation

show that

BuyValue + (Absolute(BuyValue)/100 * BuyValueOffset) = -.89 + (.89/100 x -15) = -1.0235 

so what is the problem??

thanks

**Comment by jrischma** [comment]
DcaSellValueOffset work fine 
for "DcaSellValue": "0.5" and "DcaSellValueOffset": "-25", 
i got 0.375 (0,38)

**Comment by mehtadone** [comment]
Can you attach your full appsettings.json? You can use pastebin.com if that's easier. Thanks

**Comment by jrischma** [comment]
sorry, i replace "BuyValueOffset":  with "BuyValue":

**Comment by mehtadone** [comment]
So it is working now?

**Comment by jrischma** [comment]
"BuyValue": -> work
"BuyValueOffset" -> not work

**Comment by mehtadone** [comment]
OK, can you attach your appsettings.json

**Comment by jrischma** [comment]
[appsettings.json.txt](https://github.com/mehtadone/PTFeeder/files/1760895/appsettings.json.txt)

**Comment by mehtadone** [comment]
I can't seem to see BuyValueOffset in that file

**Comment by mehtadone** [comment]
Closing as no response. Please re-open if it is still a problem
