### ISSUE TITLE
Add stop loss trigger offsets

### ISSUE THREAD

**Issue by leoneparise** [mehtadone/PTFeeder#225]
I'm using a strategy with stop loss trigger but I can't find any information about configuring stop losses for each pair. Do PTFeeder has it? For now I'm using the config from pairs.txt for each market condition but it would be awesome to have it configurable for each pair.

**Comment by mnanut** [comment]
Please add stop loss offsets if its not yet implemented.  Is this a profit trailer inquiry or does profit trailer already have this ability?  I need this for different market conditions and for different maxpercentagechange for each coin for long and short term.

**Comment by mehtadone** [comment]
Dev complete. Will be in next version
