### ISSUE TITLE
Coin offset as offset group

### ISSUE THREAD

**Issue by SJT5** [mehtadone/PTFeeder#227]
The ability to add offsets to specific coins would be great. For example, if a specific coin has been performing better than others, being able to increase cost for that coin. Similarly, for lower performing coins, lowering costs would help (instead of just putting them in SOM)

**Comment by mehtadone** [comment]
This is already possible. You can use any of these offset groups: https://github.com/mehtadone/PTFeeder/wiki/appsettings.json---Offset-Groups and use CostOffset to change the Cost https://github.com/mehtadone/PTFeeder/wiki/appsettings.json---Offset-List

**Comment by SJT5** [comment]
I'm not really seeing where I could use offsets per coin, but it did make me think that This can be punched in directly in the Pairs File in the Common folder. Thanks anyway!
