### ISSUE TITLE
"24h Volume tolerance for DCA"

### ISSUE THREAD

**Issue by Domber134** [mehtadone/PTFeeder#228]
I bought some coin when it had 1000eth 24h trading volume, then it went down under 800 and the DCA dont buying it up, because SOM is active for coins below 1000eth/24h.
Can you add something like if 24h volume is min 1000 then dca min 24h volume is 30% or something?

**Comment by mehtadone** [comment]
That is already possible. 

In your dca.txt file, you can add min_buy_volume for a dca specific min buy volume. Then you need to set ignore_som_only_mode as true so it still dca's. Also in your dca.txt file

https://wiki.profittrailer.io/doku.php/dca.properties
