### ISSUE TITLE
High CPU experienced running Version 1.4 - process DOTNET

### ISSUE THREAD

**Issue by Darent74** [mehtadone/PTFeeder#230]
running Ubuntu 16.04  on a number of systems.  Have experienced  FEEDER to stop randomly.
Further investigation have found the CPU to be spiking when FEEDER is running its cycle. 
"TOP"  shows 'DOTNET' as the process in question. 

temporary work around  , installed  cpulimit  and ran    cpulimit -e dotnet -l 80    to limit the process to 80 percent of cpu when it attempts to hog process.  This has stopped feeder from shutting down.

Have run feeder over multiple revisions, noticed the issue happening  from the last revision of  1.4.0.431 and 1.3.5.329  ,

**Comment by mehtadone** [comment]
CPU usage has been improved in the next version. If it is still the case after release (hopefully in the next week or so) please re-open the issue.
