### ISSUE TITLE
Handling 2 different base currencies (BTC & ETH / USDT)

### ISSUE THREAD

**Issue by jeremiahbnjmn** [mehtadone/PTFeeder#232]
as you know we could set up 2 bots on PT, each with different market, say 1 for BTC and 1 for ETH or USDT (on same exchange, e.g. bitrex). Can we set our feeder to handle those 2 different market? im assuming we can't since the way the appsetings works, but just want to make sure

P.S. Im not talking about arbitage, but just 2 different PT bots at different market each, handled by 1 Feeder

Thanks! have a good day

**Comment by scryba** [comment]
currently, i have two setups of PTFeeder, one for each PT setup

Setup 1
**PTFeeder/BTC/**  for **PT/BINANCE/BTC/**

Setup 2
**PTFeeder/ETH/**  for **PT/BINANCE/ETH/**


You have to remember to register both API keys with @ptfeederlicensebot Telegram bot.

**Comment by jeremiahbnjmn** [comment]
Hi scryba

I got couple questions:
1. do we have to create another api keys for the 2nd currency or we could use the same api keys from the 1st currency
2. i am assuming we can use the same feeder license for the 2nd currency setup. so 2 feeder files for different base currencies with 1 feeder licenses. kindly need your confirmation

Thanks for answering! (:

**Comment by scryba** [comment]
for Q1: create another account on Exchange for the 2nd Currency. Using the same account for both is not recommended it is even stated on PT's wiki- https://wiki.profittrailer.com/doku.php?id=faq#how_to_set_up_a_second_bot_instance.

Q2: Yes, 1 feeder license for the two feeder setups of different base currencies. but register the Main API key of the second Exchange with your current feeder license via @ptfeederlicensebot Telegram bot.

**Comment by jeremiahbnjmn** [comment]
pardon for the PT wiki, I missed it since I haven't really done a second PT instance, I should've researched it first.

And thank you for the simple and clear explanation on both questions.
I think I now have sufficient knowledge to start my ETH feeder.

Thanks again, Scryba!

**Comment by scryba** [comment]
you are very welcome.
Enjoy your day with PT and PTFeeder.

**Comment by mehtadone** [comment]
Glad it got sorted and thanks for the helping scryba
