### ISSUE TITLE
[SUGGESTION] IGNORE SUDDEN PRICE CHANGES

### ISSUE THREAD

**Issue by octobrium** [mehtadone/PTFeeder#233]
**max_trailing_buy = 10**
trailing buy... 98, 99, 100, 115 **IGNORED**, 117, 118, 113, 109 **BOUGHT**

**max_trailing_sell = 10**
trailing sell... 100, 101, 103, 90 **IGNORED**, 87, 91, 93, 97 **SOLD**

**Reason:** Ever watch your coin start mooning past 10% then have it shoot down to 0.5% profit and watch the bot sell it... only to see it bounce back five seconds later and keep going up?
Do you like buying into sudden pump and dumps?

**Solution:** an option to ignore making buy/sell decisions based on sudden changes of more than X% of your trailing_buy and trailing_profit.

Price fluctuation shakes weak hands. We need a setting to hodl during these times

**Comment by mehtadone** [comment]
@octobrium I think its a good idea but unfortunately PT feeder doesn't make any buy or sell decisions or have any information about the trailing. This would need to be implemented in PT directly.
