### ISSUE TITLE
WRN] Handled excpetion: Could not update database. Will try again next time. An error occurred while updating the entries. See the inner exception for details.

### ISSUE THREAD

**Issue by kj3407** [mehtadone/PTFeeder#237]
I have been getting this error for 2 days, I have tried deleting the pt feeder file in the database a few times, it was running and trading fine, then just stopped and I check the command prompt and seen these errors, I have tried every thing. please help. Ive included a screen shot of error and my appsetting: 
![ptfeeder error](https://user-images.githubusercontent.com/36521389/36949187-f457f354-1fb2-11e8-8e20-4109c4246525.PNG)

{
	"General": {
		"BaseCurrency": "BTC",
		"BuyStrategy": "EMAGAIN",
		"BuyValue": "-2.3",
		"MaxCost": "1.6",
		"DcaEnabled": "-3",
		"DcaMaxBuySpread": "1.5",
		"DcaMaxBuyTimes": "2",
		"DcaMaxCost": "0.15",
		"DcaMinBuyBalance": "10",
		"DcaSellTrigger": "0.6",
		"DcaSellStrategy": "GAIN",
		"DcaSellValue": "0.55",
		"DcaTrailingBuy": "0.15",
		"DcaTrailingProfit": "0.15",
		"ExcludedCoins": "BURST,ZEC,RISE,FUN,SAFEX,ZCL,BNB,BTS,BTA,DAR,DRACO,SLING,CRYPT,DOGE,UNO,SC,INCNT,NAUT,SJCX,NOTE,TKN,TIME,TRIG,MTL,DGD,DCT,CPC,FLDC,COVAL,BTCD,BCY,AUR,GLD,XMG,GBYTE,NBT,AMP,EXCL,BLK,SLS,SYNX,PKB,FLO,RISE,1ST,CLUB,QWARK,GBG,RCN,EMC2,GRS,QRL,BITB,2GIVE,BLITZ,ERC,EGC,FAIR,WAX",
		"SomOnlyCoins": "BTC-WAX, BTC-WINGS, BTC-ZCL",
		"EnabledCoinsOnly": "",
		"MaxBuySpread": "1.0",
		"MaxTrailingBuy": "0.3",
		"MaxTrailingProfit": "0.15",
		"MinBuyBalance": "50",
		"MinBuyPrice": "0.00005",
		"MinBuyVolume": "500",
		"MinProfit": "0.55",
		"MinTrailingBuy": "0.01",
		"MinTrailingProfit": "0.01",
		"MinutesForLongerTermTrend": "720",
		"MinutesToMeasureTrend": "30",
		"MaxTradingPairs": "5",
		"SellStrategy": "GAIN",
		"SellValue": "0.75",
		"TopCurrenciesToCheck": "10"
	},
	"MarketConditions": {
		"Configs": [

			{
				"FolderName": "01-superbear",
				"MaxTopCoinAverageChange": "-2",
				"DcaEnabled": "false",
				"BuyValueOffset": "200",
				"TrailingProfitOffset": "-20",
				"SellValueOffset": "-30",
				"MinProfitOffset": "-20",
				"MaxBuySpreadOffset": "-20"
			},
			{
				"FolderName": "02-bear",
				"MaxTopCoinAverageChange": "-0.5",
				"DcaTrailingBuyOffset": "25",
				"DcaTrailingProfitOffset": "-25",
				"DcaEnabled": "30",
				"DcaSellValueOffset": "-10",
				"BuyValueOffset": "25",
				"MaxPairsOffset": "-20",
				"MaxBuySpreadOffset": "-20"
			},
			{
				"FolderName": "03-boring",
				"MaxTopCoinAverageChange": "2.5",
				"BuyValue": "-2.3",
				"BuyStrategy": "EMAGAIN",
				"Weight": "99"
			},
			{
				"FolderName": "04-bull",
				"MaxTopCoinAverageChange": "5",
				"DcaTrailingBuyOffset": "-10",
				"DcaTrailingProfitOffset": "10",
				"DcaSellValueOffset": "10"
			},
			{
				"FolderName": "05-superbull",
				"MaxTopCoinAverageChange": "1000",
				"DcaTrailingBuyOffset": "-20",
				"DcaTrailingProfitOffset": "20",
				"DcaSellValueOffset": "20",
				"MinBuyBalanceOffset": "5",
				"MaxPairsOffset": "20"
			}
		]
	},
	"Price": {
		"Configs": [{
				"MaxPrice": "0.0001",
				"BuyValueOffset": "50",
				"CostOffset": "-5"
			},
			{
				"MaxPrice": "0.0005",
				"BuyValueOffset": "50",
				"CostOffset": "-5"
			}
		]
	},
	"Volume": {
		"Configs": [{
				"MaxVolume": "100",
				"BuyValueOffset": "30",
				"CostOffset": "-20"
			},
			{
				"MaxVolume": "500",
				"BuyValueOffset": "20",
				"CostOffset": "-10"
			},
			{
				"MaxVolume": "1000",
				"MinBuyBalanceOffset": "-20"
			}
		]
	},
	"PriceTrendChange": {
		"Configs": [{
				"MaxPriceTrendPercentageChange": "-6",
				"DcaEnabled": "false",
				"sellonlymode": "true",
				"TrailingProfitOffset": "-10",
				"SellValueOffset": "-30",
				"MaxBuySpreadOffset": "-20"
			},
			{
				"MaxPriceTrendPercentageChange": "-2",
				"BuyValueOffset": "100",
				"CostOffset": "5",
				"SellValueOffset": "-10"
			},
			{
				"MaxPriceTrendPercentageChange": "5"
			},
			{
				"MaxPriceTrendPercentageChange": "20",
				"TrailingBuyOffset": "-25",
				"TrailingProfitOffset": "5"
			},
			{
				"MaxPriceTrendPercentageChange": "15000",
				"DcaEnabled": "200",
				"BuyValueOffset": "10",
				"TrailingProfitOffset": "-10",
				"SellValueOffset": "-30",
				"MaxBuySpreadOffset": "-20"
			}
		]
	},
	"LongerTermPriceChange": {
		"Configs": [{
				"MaxPriceTrendPercentageChange": "-10",
				"DcaEnabled": "200",
				"BuyValueOffset": "10",
				"TrailingProfitOffset": "-10",
				"SellValueOffset": "-30",
				"MaxBuySpreadOffset": "-20"
			},
			{
				"MaxPriceTrendPercentageChange": "10"
			},
			{
				"MaxPriceTrendPercentageChange": "10000",
				"DcaEnabled": "200",
				"BuyValueOffset": "10",
				"TrailingProfitOffset": "-10",
				"SellValueOffset": "-30",
				"MaxBuySpreadOffset": "-20"
			}
		]
	},
	"AverageCandleSize": {
		"Configs": [{
			"MaxPercentageSizeOfPrice": "0.025",
			"SellOnlyMode": "true",
			"SellValueOffset": "-30",
			"DcaEnabled": "false"
		}]
	}
}

**Comment by mehtadone** [comment]
There is a new version in testing now. Hopefully it will be released by the end of the week which removes the need for the db whilst running.

I haven't been able to reproduce but will keep trying. Deleting the db seems to work for a lot of users but not all. 

A few more things to try have been detailed here https://github.com/mehtadone/PTFeeder/wiki/Common-errors#14-database-error

**Comment by kj3407** [comment]
just an fYI, I think whats happening is that when the bot changes strategy, it get's stuck in that strategy, it also may be the percent change for that strategy also.  So if I put: "99", then i may get stuck in that strategy, even though, I change it for change to 55%, it still got stuck when the market move into boring, it stay in super bear, and not move.  I will wait for the update, but I think I will use price trend change other then market conditions.

**Comment by mehtadone** [comment]
Another option for a fix is added on the common errors page https://github.com/mehtadone/PTFeeder/wiki/Common-errors#14-database-error

**Comment by mehtadone** [comment]
https://github.com/mehtadone/PTFeeder/releases/tag/pt-feeder-v1.4.0.457

**Comment by bgreater** [comment]
@mehtadone Still getting the exception with the new version, and here is the verbose error 
![screenshot 2018-03-06 16 05 02](https://user-images.githubusercontent.com/152350/37058345-36bfb924-2158-11e8-9b99-e6b3ffc0bca0.png)

**Comment by mehtadone** [comment]
Any chance you can attach the full log file to this issue? It will be in your logs directory

**Comment by bgreater** [comment]
Sure thing
[PTFeeder-20180306.zip](https://github.com/mehtadone/PTFeeder/files/1786738/PTFeeder-20180306.zip)

**Comment by mehtadone** [comment]
@bgreater and just to confirm that you deleted the db file first before running the new version.

The log file is really useful. Thank you

**Comment by bgreater** [comment]
Do you mean the PT DB or PTF? I used the new directory from the prerelease for PTF

**Comment by mehtadone** [comment]
@bgreater the PTF db. But if you used a fresh directory, that is fine.

I'm trying to reproduce it exactly so hope you don't mind me asking for more info. 

Would you be able to add your appsettings.json to pastebin.com and let me know if Calculatetrailings is true or false in your hostsettings.json?

**Comment by mehtadone** [comment]
@bgreater the PTF db. But if you used a fresh directory, that is fine.

I'm trying to reproduce it exactly so hope you don't mind me asking for more info. 

Would you be able to add your appsettings.json to pastebin.com and let me know if Calculatetrailings is true or false in your hostsettings.json?

**Comment by bgreater** [comment]
`CalculateTrailingValues` is true
appsettings.json https://pastebin.com/ZMcubPnM
windows server 13

**Comment by mehtadone** [comment]
@bgreater Really appreciated that. I think this one might do it. Fingers crossed. 

https://github.com/mehtadone/PTFeeder/releases/tag/pt-feeder-v1.4.0.459

**Comment by bgreater** [comment]
Hey I've got invested interest in seeing this work
![](https://media.giphy.com/media/5fBH6zoAQg9dHK2ttsc/giphy.gif)

**Comment by bgreater** [comment]
@mehtadone that last release is working for me!

**Comment by CryptoTalks** [comment]
NaN% with new release is still a problem..
Any advice?

**Comment by bgreater** [comment]
@CryptoTalks maybe post your log file so @mehtadone can dive in

**Comment by mehtadone** [comment]
Seems to have been fixed in the latest version. Closing unless someone has details of otherwise
