### ISSUE TITLE
Possible Buy log empty

### ISSUE THREAD

**Issue by timtaylorrr** [mehtadone/PTFeeder#24]
Hi

My "possible buy log" is empty. there should be at least those coins listed which the bot is allowed to trade, right?

Thank you.

Regards, 
Holger

**Comment by mehtadone** [comment]
Few things to check: 

How long did you wait after you started up? PT takes a little while to check. 
Do PT logs say anything?

If PT buy log is empty, PT thinks its not allowed to buy anymore. Global SOM, or low balance or something like that.

**Comment by mehtadone** [comment]
Reopen if needed
