### ISSUE TITLE
NaN% Issue

### ISSUE THREAD

**Issue by CryptoTalks** [mehtadone/PTFeeder#240]
PT bot (that is also running feeder) keep showing: 
"BTC changed by NaN% in 30 mins" ??

I never used to have an issue with my feeder. Then my VPS crashed and I had to reload it. Losing all previous data and sales history.

Is this an issue in determining configuration of market trend?  How cam I fix this?

**Comment by mehtadone** [comment]
https://github.com/mehtadone/PTFeeder/releases/tag/pt-feeder-v1.4.0.457

Closing as duplicate of https://github.com/mehtadone/PTFeeder/issues/237
