### ISSUE TITLE
Cannot run second instance of Profit Feeder 

### ISSUE THREAD

**Issue by chostetler15** [mehtadone/PTFeeder#242]
I have 3 instances of Profit Trailer bot running on my computer; only one has Profit Feeder running and its working great! I am starting to set up profit feeder on a second bot and I keep getting this error.

2018-03-06 10:39:15.007 -08:00 [Fatal] One or more valid profit trailer config directories must be set so application.properties can be found. If you are using ProfitTrailerFolder1 style directories, remember to remove the "trading" folder

I unzipped a new copy of PT Feeder to a new directory for PT Feeder 2
I used telegram to add a new API key to my license. 
I changed the ServerUrl to a different port than my first PT Feeder 
I input the the folder path using double \\ between folders. AND used "ProfitTrailerFolder2" for the directory path, AND no it is not to the "trading" folder.
I opened command prompt, got into my other PT Feeder directory, ran dotnet pt-feeder.dll and I got that error. 

Can anyone help me get Profit Feeder set up on a second Profit Trailer bot (on the same computer).

**Comment by mehtadone** [comment]
If you are running a new instance of Feeder, the  you need to use ProfitTrailerFolder1. ProfitTrailerFolder2 is if you want to drive multiple PT bots from one feeder

**Comment by mehtadone** [comment]
Reopen if still an issue

**Comment by chostetler15** [comment]
I have tried running one instance with both ProfitTrailerFolder1 and ProfitTrailerFolder2, I tried running two instances of profit feeder with each listed seperately, as well as running two instances as just ProfitTrailerFolder1. 

When running one instance of profit feeder it will open with no issues, but does not run the second bot from ProfitTrailerFolder2 location.

I tried changing the working profit feeder settings folder to the other bot, and got the same error. I double checked the API's on telegram and they are both correctly listed. But I will try and unregister them and re-register them if that is possible.

**Comment by mehtadone** [comment]
I don't think it's a api issue.

If you could post your hostsettings.json without any keys to pastebin.com and I can have a look

**Comment by chostetler15** [comment]
Checked telegram, PT Feeder Licenses... 

They listed both default API keys for binance. So I unregistered both of them and re-registered just the second bot's api key. Retried with the working profit feeder (with updated location), and still no luck (same error). 

I re-registered my main bot on PT feeder license telegram and it works fine for my main bot again. But still nothing

**Comment by chostetler15** [comment]
https://pastebin.com/uH7e4dSa <---- first bot settings that work just fine
https://pastebin.com/Kjt6dz69 <---- second bot, second instance that I tried to run. only the folder location changed

**Comment by mehtadone** [comment]
It needs to be

    "ProfitTrailerFolder1": "C:\\Users\\Cyrus\\Desktop\\Profit Trailer\\David

**Comment by chostetler15** [comment]
Wow! Thank you. I swear I tried changing the folder name before. But it finally works. 

So note to anyone who has this same problem. If you want to run a second instance of PT Feeder on a second bot, then do not have the word trading in your folder file names. 

Not sure why my first Profit Feeder could run when the word "trading" was in the folder, but it works now.
