### ISSUE TITLE
Sequence contains more than one matching element

### ISSUE THREAD

**Issue by nmalancea** [mehtadone/PTFeeder#244]
Can someone help me resolve this issue please? PTF stops shortly after I start it.
![image](https://user-images.githubusercontent.com/3107683/37075328-33b48b46-2186-11e8-82a2-1d14902f9be8.png)

**Comment by mehtadone** [comment]
Please upgrade to the latest version and see if the error repeats

**Comment by nmalancea** [comment]
Redownloading Feeder resolved the issue.
