### ISSUE TITLE
Buy Strategy based Offset Groups

### ISSUE THREAD

**Issue by ITJusus** [mehtadone/PTFeeder#246]
One of the major complaints about PT is the lack of ability to utilize multiple possible buy strategies in the same bot instance.  One could spin up a separate bot instance, using a different port...but then you can't target the same coins (without confusing the bots).  You could create a 2nd account on the same exchange (Binance), but this is officially considered a no-no by Binance.  PTF has made some strides in getting us closer to addressing this issue, with use of things like Market Conditions and Offset Groups.

But, PTF still has not gotten to the point of where it has fully addressed the issue for us.  The final and most important piece to have in PTF, I think, will be Offset Groups that directly measure the very same indicators utilized in each of the PT buy strategies:  EMASPREAD, SMASPREAD, EMAGAIN, SMAGAIN, EMACROSS, SMACROSS, LOWBB, and HIGHBB.

This would allow us to apply a particular strategy to a particular coin, based on whether that coin is currently in the range closest to one of these strategy's set buy_value.  For example, it would look something like this...

  **},
  "BUYSTRATEGYRANGES": {
    "Configs": [
      {
        "CurrentEMASpreadRange": "-9",
	  "BuyStrategy": {
	  "BuyValue": "-8",
	  "BuyStrategy": "EMASPREAD",
	  "Weight": "100"
	},		
		"DcaMinBuyBalanceOffset": "-23",
		"TrailingBuyOffset": "150"
      },
      {
        "CurrentEMASpreadRange": "-3",
	  "BuyStrategy": {
	  "BuyValue": "-2",
	  "BuyStrategy": "EMASPREAD",
	  "Weight": "100"
	},		
		"DcaMinBuyBalanceOffset": "-53",
		"TrailingBuyOffset": "100"
      },
      {
        "CurrentEMASpreadRange": "1",
	  "BuyStrategy": {
	  "BuyValue": "2",
	  "BuyStrategy": "EMASPREAD",
	  "Weight": "100"
	},		
		"DcaMinBuyBalanceOffset": "-93",
		"TrailingBuyOffset": "50"
      },**

Never mind the example offsets and above's specific values, just generic values to show the concept.  

Basically, if the EMASPREAD of a specific coin is currently between 1 and -3, then apply the BuyStrategy listed under that range (along with its offsets).  If the EMASPREAD for a specific coin is currently found to be in the range between -3 and -9, then apply the BuyStrategy listed under that range (along with its offsets).  

This would give us the ability to utilize multiple possible EMASPREAD srtategies, based on what range of the EMASPREAD each coin currently resides in.

The same concept could then be applied for adding say HIGHBB range based triggers into this same Offset Group area ("BUYSTRATEGYRANGES") just below that "CurrentEMASpreadRange" and one could simply make the "Weight" lower or higher based on which strategy is preferred over the other when two or more of these strategy ranges are hit at the same time for the same coin...

  **{
        "CurrentHighBBRange": "20",
	  "BuyStrategy": {
	  "BuyValue": "21",
	  "BuyStrategy": "EMASPREAD",
	  "Weight": "150"
	},		
		"DcaMinBuyBalanceOffset": "-23",
		"TrailingBuyOffset": "150"
      },
      {
        "CurrentHighBBRange": "50",
	  "BuyStrategy": {
	  "BuyValue": "51",
	  "BuyStrategy": "EMASPREAD",
	  "Weight": "150"
	},		
		"DcaMinBuyBalanceOffset": "-53",
		"TrailingBuyOffset": "100"
      },
      {
        "CurrentHighBBRange": "-1",
	  "BuyStrategy": {
	  "BuyValue": "-2",
	  "BuyStrategy": "EMASPREAD",
	  "Weight": "150"
	},		
		"DcaMinBuyBalanceOffset": "-93",
		"TrailingBuyOffset": "50"
      },**

And I think you get the point.

**Comment by mehtadone** [comment]
That's super interesting. I'll leave this open and let's revisit to see if it is still needed when PT has multiple indicators as per https://github.com/taniman/profit-trailer/issues/370

When this is ready, it would complicate the requirement a bit but we can revisit then

**Comment by ITJusus** [comment]
Thank you, yes, I was aware of the multiple indicator strategies coming down the pipe for PT...but I think those will all be for secondary confirmation (RSI) of a primary indicator (buy strats like EMASPREAD) and not necessarily what I'm referring to here (mine being closer to a market condition threshold).  

I think when they implement that, it will likely not complicate what I'm suggesting, as the primary indicator/buy strategy will still be what we are interested in tracking with PTF...while the secondary confirmation indicators will still only need be referenced in PT alone.  Now if they add more primary indicators (buy strategies) to the existing list, then you would want to add those as well, so I can see how that would add to the amount of items you would need to implement into this new feature.  

Maybe if you happen to find some time, before they release the new indicator combos, perhaps you could implement this based on the primary indicators/buy strategies they already currently support...and then we could help work out any kinks before they make it even more complex?  Then you would already have a good foundation built and would just be able to add a bit on top, rather than start from scratch at that time.  I'm not a dev in this game, so you know better the inside scoops than I do...but that would be nice, I think.

**Comment by mehtadone** [comment]
Moved to forum: 

http://forum.ptfeeder.co/t/buy-strategy-based-offset-groups/36
