### ISSUE TITLE
Error when typing dotnet pt-feeder.dll in command prompt 

### ISSUE THREAD

**Issue by john020884** [mehtadone/PTFeeder#249]
Hello I have followed the instruction but when I type in dotnet pt-feeder.dll into command prompt I'm getting the following error:

C:\Users\john0>dotnet "C:\Users\john0\Desktop\PT FEEDER\pt-feeder.dll"
[19:17:07 ERR] Error whilst starting PT Feeder
System.ArgumentException: The directory name C:\Users\john0\config\ is invalid.
Parameter name: path
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at System.IO.FileSystemWatcher..ctor(String path)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.CreateFileWatcher(String root)
   at Microsoft.Extensions.Configuration.FileConfigurationExtensions.SetBasePath(IConfigurationBuilder builder, String basePath)
   at pt_feeder.Program.Main(String[] args) in C:\projects\profittrailer-config-generator\pt-feeder\Program.cs:line 50

Any ideas? Any help would be appreciated as it's driving me nuts. I

Thanks

John

**Comment by mehtadone** [comment]
Try changing directory to C:\Users\john0\Desktop\PT FEEDER then typing dotnet pt-feeder.dll

**Comment by john020884** [comment]
it says : 

The application to execute does not exist: 'C:\Users\john0\pt-feeder.dll'

**Comment by mehtadone** [comment]
your doing something wrong as that not the same directory. In the previous message it wasC:\Users\john0\Desktop\PT FEEDER

**Comment by john020884** [comment]
what do i type to get to 

C:\Users\john0\Desktop\PT FEEDER

I am typing      start "C:\Users\john0\Desktop\PT FEEDER"  and it opens an new command prompt window but the new command prompt window says: 

C:\Users\john0>

**Comment by mehtadone** [comment]
Do you know how to change directory?

**Comment by john020884** [comment]
i typed cd Desktop, i am now in the Desktop on commande prompt C:\Users\john0\Desktop>

and the folder is in the Desktop. Now i need to access the folder. The link on your website doesn't say how to access the folder. Thanks for helping. I've set everything else up and a VPS too i'm just having problems with command prompt as i haven't used it for years

**Comment by john020884** [comment]
so i have a command prompt window open that says: C:\Users\john0\Desktop> 

I now need to access my PT FEEDER folder on my desktop. What do I type in command prompt next to access PT FEEDER folder? 

Thanks

**Comment by mehtadone** [comment]
Thats fine. So you now need to cd "PT FEEDER". Then you should be able to type "dotnet pt-feeder.dll"

**Comment by john020884** [comment]
thanks its working, " Loading initial prices & candles from Binance"

**Comment by mehtadone** [comment]
Perfect!

**Comment by john020884** [comment]
thanks, last question. If on Profit trailer I have the setting: ALL_trading_enabled = false, and test mode =true   the PT feeder won't override these settings right?  Or will PT Feeder override these? 

It's just because I want to keep it all in test mode at the moment because I need to upload it all to a VPS.

**Comment by mehtadone** [comment]
no it will not override test mode. ALL_trading_enabled will be overriden hover by pair specific config. There is a test mode flag in hostsettings.json of Feeder. https://github.com/mehtadone/PTFeeder/wiki/hostsettings.json#test-mode-from-version-133

**Comment by john020884** [comment]
ok thanks for your help. I'll put it on a VPS tomorrow and start with 1000 bucks and see how it goes. Hopefully 1 million in 2 weeks
