### ISSUE TITLE
ExcludedPairs not working on Binance

### ISSUE THREAD

**Issue by Christine-Y** [mehtadone/PTFeeder#25]
sorry, some weird formatting is happening...

Having     "ExcludedPairs": "ENJBTC",   in the pairs.json file should translate to 
BTCETH_trading_enabled = false 

I only have this is the PTF pairs output
# ENJBTC has been set to SELL ONLY mode
# Reason: Price (0.0000249) was lower than min price of 0.0001
# Actual trailing profit was 0.57
# Pump and dump price change was -12.85
# Notes: 
ENJBTC_trading_enabled = true
ENJBTC_trailing_profit = 0.1
ENJBTC_DCA_enabled = -2
ENJBTC_sell_value = 1.25
ENJBTC_sell_only_mode = true

**Comment by mehtadone** [comment]
Hey, 

"ExcludedPairs": "ENJ".

The name is misleading. It should probably be excluded coin

**Comment by vwodwo22** [comment]
Did this work for you?  It is not working for me?
