### ISSUE TITLE
VPS hosting for Profit Trailer and PT Feeder

### ISSUE THREAD

**Issue by john020884** [mehtadone/PTFeeder#250]
Hello, this is not an issue, but I was wondering if anyone can suggest a good VPS company where I can put my Profit Trailer and PT FEEDER?

Would 4GB RAM / 3 CORE / 50GB SSD HW RAID 10 / DDoS-Protected / 3TB BW / 1GBPS be sufficient for both PTrailer an PT Feeder?

Any suggestions would be appreciated.

**Comment by mehtadone** [comment]
Yes that will be fine
