### ISSUE TITLE
Error on PTFeeder Start-Up

### ISSUE THREAD

**Issue by LKNLC** [mehtadone/PTFeeder#252]
I have recently purchased PT and PTF as well as install services.  However, I am not sure that the Feeder is working.  The tech that I had do the setup said it is running unless there are errors that show in the shortcut file he created. When I open the shortcut I have the following error: 

ERR] Your port configured in hostsettings.json or the default of 5001 is in use. This can be changed by adding the line "ServerUrls": "http://localhost:XXXX" into hostsettings.json where XXXX is an unused port

The tech said that this is because it was already running when I opened the shortcut, but it does the same thing when I shut everything off and reopen the short cut.  Not sure how to fix this.

**Comment by mehtadone** [comment]
Try adding this line to your hostsettings.json and changing the port number: 

https://github.com/mehtadone/PTFeeder/wiki/hostsettings.json#serverurls-leave-default

**Comment by mehtadone** [comment]
Comment if you still need help
