### ISSUE TITLE
[REQUEST] Handle for Profit Trailer -> Possible Buy Log --> "24H%" column

### ISSUE THREAD

**Issue by IAmNigh** [mehtadone/PTFeeder#254]
I would like a way to get the values from the Profit Trailer -> Possible Buy Log --> "24H%" column for a specific coin, so that I may control the Feeder configs accordingly.

**Comment by IAmNigh** [comment]
Should be fair straight forwards to implement using 'BCPTETH' for example:
https://www.binance.com/api/v1/ticker/24hr?symbol=BCPTETH

Returns the json Array data and then get the "priceChangePercent" value will get the 24H% column...

**Comment by mehtadone** [comment]
Is this in addition to the Longertermpricechange? You change MinutesForLongerTermTrend to 1440, you can achieve the same thing

**Comment by IAmNigh** [comment]
mehtadone, you are correct, it also works to return the 24H price change %. No need to increase the query time of the bot. I'll close this. Thanks for your help.
