### ISSUE TITLE
[REQUEST] BB Width Offset Group

### ISSUE THREAD

**Issue by jake501** [mehtadone/PTFeeder#256]
I've been using LOWBB buy strats fairly successfully however, depending on how big the trails are set, it can usually end up buy at the beginning of a big downturn or at a sudden drop before crashing another 10-20% after the buy. Then you gotta DCA to hell to get out with a mere 1 to 2% profit.

I'm using BB length 200 and 15 min candles. Default buy value -20, Sell value -10. This offset would be more beneficial than relying on price trends, volume or any of the other currently available groups especially as BB length could me more helpful in determining longer trends than just the PriceTrend.

I'm not sure if this is easily implemented, in works, or even feasible, however, creating a BB Width offset group would be freaking amazing. In this first image, the beginning would normally get bought, really shitty usually.

BB Width % = (HIGHBB - LOWBB) / SMALine * 100

![1](https://user-images.githubusercontent.com/34288768/37244212-852f6476-2453-11e8-9316-21d5a0d8a7b0.PNG)

But if we are able to create offsets that if the BB width is smaller than 10 for example, make the buy value like -40 so the chances of buying are slim. But once the volatility has reached it's higher width, than we lower the buy value so we can snag the bottoms. Then in this offset group, we can make it change offsets at every width percentage that we want. 

![2](https://user-images.githubusercontent.com/34288768/37244213-87999402-2453-11e8-8a3d-de9b29b6f2fe.PNG)

This offset would also be great if your doing the LOWBB and HIGHBB combo. This way your not selling at the bottom spikes but at the higher ones. Although of course, this is riskier when it just touches once then plummets but hey that's the name of the game.

![image](https://user-images.githubusercontent.com/34288768/37244420-d74666f8-2456-11e8-91ae-15cd0e2deb4a.png)

**Comment by jake501** [comment]
I was reading through some other requests and I think this offset would go perfectly with the offsets proposed in #246. Being able to change strategies when for example, the BB value is above 50 to something quicker like EMAGAIN then switch it off when its past 100 while at the same time, increasing buy/sell values when the BB WIDTH is greater than a certain percentage to maximize the dips and gains.

For anyone who trades based on volatility, this would be the money maker. Honestly with the STRATOFFSET and this BBOFFSET groups, Feeder would become so much more valuable!!

**Comment by mehtadone** [comment]
BBWIDTH is now a strategy in PT v2. Please reopen/comment here if you think this is still needed.
