### ISSUE TITLE
[REQUEST] Pair specific DCA settings

### ISSUE THREAD

**Issue by RobinopdeBeek** [mehtadone/PTFeeder#257]
Hi! Thanks for the great new features in 1.4!

Would it be possible to have pair specific DCA settings? Like with an offset group in which you can regulate DCA offsets per pair, instead of per market condition?

**Comment by mehtadone** [comment]
PT unfortunately doesn't support pair specific dca properties. There is an open PT issue for this and once it is implemented, I will add it in feeder
