### ISSUE TITLE
[REQUEST] Update to PAIRS.properties more often

### ISSUE THREAD

**Issue by Cryptoqueb** [mehtadone/PTFeeder#258]
I'm using the values in PAIRS.properties to make sure I buy at the lowest possible with EMASPREAD, but with 3m between each update it sometimes miss a good buy or does a bad one. Could we have an option to make updates to that file more frequently?

thx

**Comment by mehtadone** [comment]
You can update a quick as 1 minute without any binance bans

**Comment by Cryptoqueb** [comment]
Does "MarketConditionCheckInMinutes":  update the PAIRS.properties or simply change the market condition? Seems like it's the latter.

**Comment by Cryptoqueb** [comment]
I have it at 1m and I'm pretty certain that the PAIRS.properties is not updating every minute

**Comment by mehtadone** [comment]
It will be updating 1 min plus the time it takes to do the calculations. That will be dramatically reduced in the next version. 

MarketConditionCheckInMinutes changes the pairs.properties when the market condition changes, or every 5 checks regardless. 

This can be configured to write every time if you would like: https://github.com/mehtadone/PTFeeder/wiki/hostsettings.json#turnstoregeneratefiles-from-135

**Comment by Cryptoqueb** [comment]
Cool! Didn't see that im sorry. This gonna help me quite a lot!

thx a lot

**Comment by mehtadone** [comment]
No problem
