### ISSUE TITLE
[REQUEST] "MaxBaseCoinPriceChange"

### ISSUE THREAD

**Issue by RobinopdeBeek** [mehtadone/PTFeeder#259]
Hi! 
We now have "MinBaseCoinPriceChange" to tell the bot to SOM if BTC goes up more than X %. But I would also like to tell the bot to SOM if BTC goes down X %, as a lot of the pairs follow the down movement. 
In the current market condition setup structure it is not possible to set multiple ranges for "BaseCoinPriceChange", while also having the ranges for "MaxTopCoinAverageChange". 

If it is possible to do this then can someone tell me? Otherwise it would be awesome to see a "MaxBaseCoinPriceChange" :)

**Comment by mehtadone** [comment]
Added in 1.5
