### ISSUE TITLE
Pt feeder

### ISSUE THREAD

**Issue by Mrcrypt0** [mehtadone/PTFeeder#26]
I can not get this to work, help

**Comment by mehtadone** [comment]
Please read the wiki

**Comment by Mrcrypt0** [comment]
I have been trying for 24 hours to get this to work, when double clicking on the Start the program by executing `dotnet pt-feeder.dll` or use [pm2](http://pm2.keymetrics.io/) to manage the process easily. A .json file to easily integrate it into pm2 is included in the release zip file.

 

If you are on windows. 

1) Please open notepad and write `dotnet pt-feeder.dll`.

2) Save this file as pt-feeder.bat

3) Copy this file into the folder where you extracted the contents of the ptf release zip file. 

4) Double click on the pt-feeder.bat file. You should see pt-feeder running

A screen appears briefly than disappears it is not running.. Can I get someone to help please

 


 

Paul Murphy

Principal & Sales Agent

 

p   |  0407 165 684

e   |   <mailto:paulmurphy@boomrealestate.com.au> paulmurphy@boomrealestate.com.au

w  |   <http://www.boomrealestate.com.au> www.boomrealestate.com.au

 

 <http://www.facebook.com/boomrealestate>         <https://www.instagram.com/boomrealestate/>         <https://twitter.com/BoomRealEstate1> 

 <http://www.boomrealestate.com.au/>

**Comment by Thijsjuh92** [comment]
Don't forget without the>>>>> ` <<<<<<< mine first mistake!!

**Comment by Mrcrypt0** [comment]
Done that,, following all the steps when I double click on the batch file to run it, it pops up for a second then gone and nothing runs.

 

What could I have done wrong?

 

Trading key? Default key?

 


 

Paul Murphy

Principal & Sales Agent

 

p   |  0407 165 684

e   |   <mailto:paulmurphy@boomrealestate.com.au> paulmurphy@boomrealestate.com.au

w  |   <http://www.boomrealestate.com.au> www.boomrealestate.com.au

 

 <http://www.facebook.com/boomrealestate>         <https://www.instagram.com/boomrealestate/>         <https://twitter.com/BoomRealEstate1> 

 <http://www.boomrealestate.com.au/>

**Comment by Thijsjuh92** [comment]
Then you just need to read the Wiki ;-)

**Comment by Mrcrypt0** [comment]
I have done that, I have been trying to get this to work for 12 hours. Can profitbot help get this working?

 

 


 

Paul Murphy

Principal & Sales Agent

 

p   |  0407 165 684

e   |   <mailto:paulmurphy@boomrealestate.com.au> paulmurphy@boomrealestate.com.au

w  |   <http://www.boomrealestate.com.au> www.boomrealestate.com.au

 

 <http://www.facebook.com/boomrealestate>         <https://www.instagram.com/boomrealestate/>         <https://twitter.com/BoomRealEstate1> 

 <http://www.boomrealestate.com.au/>
