### ISSUE TITLE
[ISSUE] Calculating trailing values

### ISSUE THREAD

**Issue by vrmg1221** [mehtadone/PTFeeder#260]
I have a problem with the trailing values. My buy and sell strategy is this:
"BuyStrategy": "LOWBB",
"BuyValue": "6",
"MaxTrailingBuy": "1", 
"MinTrailingBuy": "0.4",

"SellStrategy": "GAIN",
"SellValue": "1",
"MinTrailingProfit": "0.255",
"MaxTrailingProfit": "1",

 -In hostsettings CalculateTrailingValues is true
- The market conditions I am using is:

{
 "FolderName": "03-Normal",
        "MaxTopCoinAverageChange": "1",
		"TrailingBuyOffset": "17",
                "TrailingProfitOffset": "20",
                "BuyValueOffset": "-10",
},

When the pairs.properties file is generated, I make sure it is using the Normal market conditions.
And as you see below the trailing buy is still 0.4 and trailing profit is still 0.255 - the offset is not calculated:

ADAETH_trading_enabled = true
ADAETH_DCA_enabled = -2
ADAETH_buy_strategy = LOWBB
ADAETH_buy_value = 5.4
ADAETH_sell_value = 1
ADAETH_trailing_profit = 0.255
ADAETH_trailing_buy = 0.4

- As you see, the buy_value is calculated just fine, but both the trailing_profit and trailing_buy is not.
- This is just a simplied version of my settings (I have removed the PriceChange groups, to remove noice)
- I have linked the appsettings file I have done my testing with.

- I think the issue might be because PT feeder states this as the buy and sell strategy in the top of the pairs.properties:

#------- Buy strategy -------
ALL_buy_strategy = LOWBB
ALL_buy_value = 5.4
ALL_trailing_buy = 1

#------- Sell strategy -------
ALL_sell_strategy = GAIN
ALL_sell_value = 1
ALL_trailing_profit = 1

![udklip1](https://user-images.githubusercontent.com/13337186/37247324-a8f70952-24b9-11e8-9b35-d284f98eec25.PNG)

![udklip2](https://user-images.githubusercontent.com/13337186/37247336-ba6db8a2-24b9-11e8-9602-39753bd3799a.PNG)

**Comment by hargate** [comment]
I am having the same issue. Both calculated trailing values are not calculating in accordance with the setting that I have in my appsetting.json file. I had to turn "CalculateTrailingValues" = "false".

**Comment by vrmg1221** [comment]
After more testing... Basicly my trailing values in my market conditions doesn't work.. I have tried when I override the buyStrategy to add a minTrailingBuy value higher than the original, which doesn't work. Adding the trailingBuyOffset in a normal MarketConditions config doesn't work or inside an BuyStrategy Override.

**Comment by mehtadone** [comment]
Added a check for trailings on every turn of the market in 1.5
