### ISSUE TITLE
[Request] DCA buy volume should not be the same as initial buy volume.

### ISSUE THREAD

**Issue by DaNiSeL** [mehtadone/PTFeeder#261]
Hello,

Have been asking this in discord but no one seems to know if this option actually exist.
I have my initial buy volume set to "1000" but if the volume of a coin drops below this,
It will also not DCA buy because of this. can you make / or is there an option to set the DCA volume to another volume like "500" 

So it will keep DCA buying untill coin volume 500, and will go to SOM below that number.

Thanks.

**Comment by mehtadone** [comment]
You can set min_buy_volume in your dca.txt files as per https://wiki.profittrailer.com/doku.php?id=dca.properites but you will also have set Ignore_sell_only_mode as true in the same file. This will keep buying dca even though they might be in som for new buys.
