### ISSUE TITLE
When BaseCurrency is not BTC, BTC is not being generated in the pairs file.

### ISSUE THREAD

**Issue by Brillynt** [mehtadone/PTFeeder#262]
I have my BaseCurrency set to ETH. In the generated pairs file, BTC is not listed at all.

**Comment by mehtadone** [comment]
That's unfortunately not possible as the market does not exist on the exchanges. PT will only support market pairs that the exchange supports. For example on bittrex, BTC-ETH is a supported market but ETH-BTC is not.
