### ISSUE TITLE
Pair-specific values

### ISSUE THREAD

**Issue by Juice102** [mehtadone/PTFeeder#264]
I understand I can write pair-specific values into pairs.txt.  However, if the coin is listed in EnabledCoinsOnly , PTF creates redundant appsettings that seem to override the manual settings.  If the coin is not listed in EnabledCoinsOnly, it accepts the manual settings, but in watchmode.  For example, if I want to take the occasional "manual" swing trade, how do I ensure the SellValue will be the specific value I want and not the "generic" value I set for other coins (and not be in watchmode)?    I don't want to set the sell value on the exchange b/c I also want a stop loss.

**Comment by mehtadone** [comment]
You can use the "Footer" functionality of feeder. This will add pair specific config at the end of the pairs.properties file, and this will be one that is used, even though Feeder might have generated config earlier in the file: 

https://github.com/mehtadone/PTFeeder/wiki/Market-Folders#footer-folder-from-version-140
