### ISSUE TITLE
[REQ] Block new coins!

### ISSUE THREAD

**Issue by rer0dgers** [mehtadone/PTFeeder#266]
Most brand new coins start with a high volume, high enough to make my possible the list. The great majority of them drop extremely fast. Also, most never recover the list day price. We really need a way to block new coins until they reach their stable price. Something like this... 

"MinCoinAge": "7"  // Tracked in days, this controls how old a coin must be to trade.

**Comment by MrS1n1st3r** [comment]
Just set your enabled pairs..and only add new coins to enabled pairs when you are ready to.

**Comment by rer0dgers** [comment]
I already do that. Why would anyone want to continue to maintain a list of hundreds of pairs and weekly evaluate adding new ones when this could be managed with one "MinCoinAge" property.

**Comment by mehtadone** [comment]
This is already been done and dev complete. https://github.com/mehtadone/PTFeeder/issues/100 Will be in the next version

**Comment by doktorn26** [comment]
👍🏾

Få Outlook for iOS<https://aka.ms/o0ukef>
________________________________
