### ISSUE TITLE
command prompting telegram bot :(

### ISSUE THREAD

**Issue by bestinthewest** [mehtadone/PTFeeder#267]
so i want to add api key for pt feeder. but nothing works to add an api key.

PT Feeder Licenses, [14.03.18 16:58]
That's not a valid command. Try again or contact your reseller.

PT Feeder Licenses, [14.03.18 16:58]
Is there anything else I can help you with?

1. List registered API keys
2. Register an API key
3. Unregister an API key
4. Quit

Jason Best, [14.03.18 16:58]
/2. Register an API key

PT Feeder Licenses, [14.03.18 16:58]
That's not a valid command. Try again or contact your reseller.

PT Feeder Licenses, [14.03.18 16:58]
Is there anything else I can help you with?

1. List registered API keys
2. Register an API key
3. Unregister an API key
4. Quit

PT Feeder Licenses, [14.03.18 17:03]
Looks like you've done what you needed to.

PT Feeder Licenses, [14.03.18 17:03]
Goodbye. Type /start to start over

**Comment by mehtadone** [comment]
You just need to press the number, 

2

Did that not work?

**Comment by bestinthewest** [comment]
yes it did thank you :)
