### ISSUE TITLE
UpsideDownsideVolatility values do not get updated when Pairs file are written

### ISSUE THREAD

**Issue by RobinopdeBeek** [mehtadone/PTFeeder#269]
Hi, 

I've been using Kurette's indicator for Tradingview to visualise the UpsideDownsideVolatility, and that works very well (thanks Kurette). But when I compare it with the Upside and Downside Volatility that gets written to the Pairs file, they don't match up. 

For instance: 
If I look at the NEBL/BTC in the Pairs file it states Upside: 0.39% and Downside: 0.45%, giving difference of **-0.06%**. 
But on Tradingview it states Upside: 1.11% and Downside: 0.75%, giving difference of **0.36%**. 
Looking at the chart it is clear that the Tradingview values are correct. 

It seems that the Upside and Downside values are not updating. They has been on the same values for quite some time now.

**Comment by mehtadone** [comment]
Hey, yes this is because the volatility isn't calculated at every cycle yet due to performance limitations. But it is dev complete to do so in the next version as per https://github.com/mehtadone/PTFeeder/issues/193

**Comment by mehtadone** [comment]
Ps. Can you link the tradingview script so I can check the new version matches up?

**Comment by RobinopdeBeek** [comment]
Great thanks! Here is the link:
https://www.tradingview.com/script/ohONdnxB-Upside-Downside-Volatility-of-ProfitTrailer-Feeder/
