### ISSUE TITLE
pt feeder not running

### ISSUE THREAD

**Issue by Mrcrypt0** [mehtadone/PTFeeder#27]
When opening the bat file it does not proceed, evertything else seems right,,troubleshoot

**Comment by vwodwo22** [comment]
Can you ellaborate on "does not proceed" .  Does it open and close or give you a message?

**Comment by Mrcrypt0** [comment]
I have Profit Trailer running, I have downloaded a new version pt-feeder-v1.3.3.204.zip Extracted to a new file

 

I have followed the instructions in wiki, I have downloaded https://www.microsoft.com/net/learn/get-started/windows?utm_expid=.-Fmi9Q05Ry2oXQgdtPElHw.0 <https://www.microsoft.com/net/learn/get-started/windows?utm_expid=.-Fmi9Q05Ry2oXQgdtPElHw.0&utm_referrer> &utm_referrer=

 

I also made the batch file as attached.

 

 

The only other thing it I think it could be is the API KEY.. I used this one

#Put here your licensed API key

default_apiKey = 3503f9744ea94273824a6960ce9f3fcf  ( this is the one I gave to Profit Trailer )

 

I changed the host settings to below

 

Help would be greatly appreciated

 

 



 



 


 

Paul Murphy

Principal & Sales Agent

 

p   |  0407 165 684

e   |   <mailto:paulmurphy@boomrealestate.com.au> paulmurphy@boomrealestate.com.au

w  |   <http://www.boomrealestate.com.au> www.boomrealestate.com.au

 

 <http://www.facebook.com/boomrealestate>         <https://www.instagram.com/boomrealestate/>         <https://twitter.com/BoomRealEstate1> 

 <http://www.boomrealestate.com.au/>

**Comment by Mrcrypt0** [comment]
I think I have everything right, Profit trailer is running,

 

I cant open the batch file and run profit feeder,,what could be the reason?

 


 

Paul Murphy

Principal & Sales Agent

 

p   |  0407 165 684

e   |   <mailto:paulmurphy@boomrealestate.com.au> paulmurphy@boomrealestate.com.au

w  |   <http://www.boomrealestate.com.au> www.boomrealestate.com.au

 

 <http://www.facebook.com/boomrealestate>         <https://www.instagram.com/boomrealestate/>         <https://twitter.com/BoomRealEstate1> 

 <http://www.boomrealestate.com.au/>

**Comment by Mrcrypt0** [comment]
Is there something you see here that isn’t right

 



 

 


 

Paul Murphy

Principal & Sales Agent

 

p   |  0407 165 684

e   |   <mailto:paulmurphy@boomrealestate.com.au> paulmurphy@boomrealestate.com.au

w  |   <http://www.boomrealestate.com.au> www.boomrealestate.com.au

 

 <http://www.facebook.com/boomrealestate>         <https://www.instagram.com/boomrealestate/>         <https://twitter.com/BoomRealEstate1> 

 <http://www.boomrealestate.com.au/>

**Comment by vwodwo22** [comment]
Try open a standard command print window. Cmd.  Then drag your bat file into the command prompt window and hit enter. What does it say?

**Comment by Mrcrypt0** [comment]
See below..not recognized.

 

I downloaded https://www.microsoft.com/net/learn/get-started/windows?utm_expid=.-Fmi9Q05Ry2oXQgdtPElHw.0 <https://www.microsoft.com/net/learn/get-started/windows?utm_expid=.-Fmi9Q05Ry2oXQgdtPElHw.0&utm_referrer> &utm_referrer=

 

What do I do?




 

Paul Murphy

Principal & Sales Agent

 

p   |  0407 165 684

e   |   <mailto:paulmurphy@boomrealestate.com.au> paulmurphy@boomrealestate.com.au

w  |   <http://www.boomrealestate.com.au> www.boomrealestate.com.au

 

 <http://www.facebook.com/boomrealestate>         <https://www.instagram.com/boomrealestate/>         <https://twitter.com/BoomRealEstate1> 

 <http://www.boomrealestate.com.au/>

**Comment by Mrcrypt0** [comment]
Checked and this is working and downloaded .net again and repaired.

 


 

Paul Murphy

Principal & Sales Agent

 

p   |  0407 165 684

e   |   <mailto:paulmurphy@boomrealestate.com.au> paulmurphy@boomrealestate.com.au

w  |   <http://www.boomrealestate.com.au> www.boomrealestate.com.au

 

 <http://www.facebook.com/boomrealestate>         <https://www.instagram.com/boomrealestate/>         <https://twitter.com/BoomRealEstate1> 

 <http://www.boomrealestate.com.au/>

**Comment by Mrcrypt0** [comment]
Drag the bat file into the dotnet box and nothing..what could it be

 


 

Paul Murphy

Principal & Sales Agent

 

p   |  0407 165 684

e   |   <mailto:paulmurphy@boomrealestate.com.au> paulmurphy@boomrealestate.com.au

w  |   <http://www.boomrealestate.com.au> www.boomrealestate.com.au

 

 <http://www.facebook.com/boomrealestate>         <https://www.instagram.com/boomrealestate/>         <https://twitter.com/BoomRealEstate1> 

 <http://www.boomrealestate.com.au/>

**Comment by vwodwo22** [comment]
cant say for sure. New to this myself?  Did you register your API with the telegram bot?  Are you on windows or Linux? If windows, if you open a command prompt and type "dotnet" what does it say?  Can you take a screen shot, or copy and paste the text from configure file. Hide/remove your license key and API so we don't see it.

**Comment by Mrcrypt0** [comment]
Mehtadone has got it working on discord although in the hour and a bit its been running it has not bought or sold anything.

 


 

Paul Murphy

Principal & Sales Agent

 

p   |  0407 165 684

e   |   <mailto:paulmurphy@boomrealestate.com.au> paulmurphy@boomrealestate.com.au

w  |   <http://www.boomrealestate.com.au> www.boomrealestate.com.au

 

 <http://www.facebook.com/boomrealestate>         <https://www.instagram.com/boomrealestate/>         <https://twitter.com/BoomRealEstate1> 

 <http://www.boomrealestate.com.au/>

**Comment by Mrcrypt0** [comment]
Happy to pay someone to get this running propertly and making a lot of profit.. Its only using .8 btc at the moment and not doing jack shit.

 

Is there a gun that can tweak my settings to get this super aggressive and earning.

 


 

Paul Murphy

Principal & Sales Agent

 

p   |  0407 165 684

e   |   <mailto:paulmurphy@boomrealestate.com.au> paulmurphy@boomrealestate.com.au

w  |   <http://www.boomrealestate.com.au> www.boomrealestate.com.au

 

 <http://www.facebook.com/boomrealestate>         <https://www.instagram.com/boomrealestate/>         <https://twitter.com/BoomRealEstate1> 

 <http://www.boomrealestate.com.au/>

**Comment by jfike33** [comment]
I'm having this exact same issue. When I click on batch file. The cmd window opens momentarily. About ten lines of code display and the window closes down very fast. I can't read any of the code. When I drug the file into the cmd window and hit enter, it says: the application to execute does not exists. I installed the sdk. repaired it. uninsttalled and reinstalled. Still doens't work.
