### ISSUE TITLE
Rough time frame for new releases?

### ISSUE THREAD

**Issue by Mtrade** [mehtadone/PTFeeder#270]
I understand hard due dates are impractical for development, but maybe it is possible to provide a rough estimate of when the next 1 or 2 PTfeeder release(s) will arrive. It might be helpful for people to plan for their upgrade, or decide if they should roll back to a prior version or wait, for example if a current version has an issue that affects their strategy.
Thanks

**Comment by mehtadone** [comment]
The aim will be a release, whether big or small every 2 to 3 weeks. This next release however is a lot longer as we are prepping for PT Version 2
