### ISSUE TITLE
MinBuyVolumeOffset for DCA

### ISSUE THREAD

**Issue by MrS1n1st3r** [mehtadone/PTFeeder#271]
Is there currently a way to offset MinBuyVolume or will you be adding a DCAMinBuyVolumeOffset?

I have a MinBuyVolume set at a number, but often times, when in DCA, the volume for a that coin gets below that number by 2, or something nominal, and it will not DCA.  I wouldn't mind having a MinBuyVolume requirement for DCA that is smaller, so get out of the bag.

**Comment by mehtadone** [comment]
You can add min_buy_volume already for dca. It's just not generated by feeder yet. If you would like to use it, just add it to your dca.txt files.

https://wiki.profittrailer.com/doku.php/dca.properties

**Comment by MrS1n1st3r** [comment]
I did but it doesn't seem to be taking  effect. Do i need to restart PF for anything not in the two main properties files?

**Comment by mehtadone** [comment]
No need to restart. Just for wait for the next market condition check.

Has it written in your dca file in PT monitor - config section?

**Comment by MrS1n1st3r** [comment]
It does not write said property...

**Comment by MrS1n1st3r** [comment]
I put the line in the dca.txt file under the footer folder. But it doesn't write the file.

**Comment by MrS1n1st3r** [comment]
Edit : doesn't write it to the config section.

**Comment by MrS1n1st3r** [comment]
It´s working now.

**Comment by MrS1n1st3r** [comment]
OK i's working as in it now writes the property BUT the coin is still in SOM in DCA for being under the main volume, so the lower DCA volume isn't affecting this.
