### ISSUE TITLE
Handled exception: Error when checking market conditions. 

### ISSUE THREAD

**Issue by SatoshiBill** [mehtadone/PTFeeder#274]
Will try again next set to an instance of an object.

ty in advance....

appsettings.json - https://pastebin.com/snPPG973

hostsettings.json - https://pastebin.com/ahp4kFpA**** @mehtadone

**Comment by SatoshiBill** [comment]
Could not work out which market condition to use.

**Comment by smoochy** [comment]
`"MarketConditionCheckInMinutes": "\5",`

Try removing the \ in front of the 5.

**Comment by mehtadone** [comment]
If you need any more help, please re-open or comment on this issue
