### ISSUE TITLE
[time: ERR] Handled Exception: when parsing response from bittrex: Value cannot be null

### ISSUE THREAD

**Issue by g1j0seJOE** [mehtadone/PTFeeder#276]
I seen a past issue with this message, and only that it typically the api key sending wrong info but what was the fix to this issue.  Thanks for your time and help with this in advance.

**Comment by mehtadone** [comment]
Could be a couple of things. The most likely is that the bittrex api is sending wrong data. This will resolve itself.

The other issue it could be if it is happening on every coin is your machine time has gone out of sync. Try the time sync tool in the common errors page if this is the case.

**Comment by mehtadone** [comment]
Closing for now. Reopen if still an issue
