### ISSUE TITLE
Error installing Feeder?

### ISSUE THREAD

**Issue by digicoingroup** [mehtadone/PTFeeder#278]
Brand new to PT and Feeder. Attempting to install and configure PT Feeder and I'm getting this error:
![feeder_error](https://user-images.githubusercontent.com/37671821/37803949-34518f52-2e08-11e8-91ce-4942714833fc.jpg)
Any assistance would be much appreciated!

**Comment by mehtadone** [comment]
In your hostsettings.json, is the folder path pointing to a valid profit trailer directory?

**Comment by digicoingroup** [comment]
Hello,

Thanks for the question. I'll show you what the file looks like:




Here's the desktop:


Is that right? Do I need to change any of the settings?

Richard

**Comment by mehtadone** [comment]
Hi Richard, doesn't look like the file attached

**Comment by mehtadone** [comment]
Doesn't look like it

**Comment by digicoingroup** [comment]
Ok. I'll resend as attachments when I get a chance. Driving now.


Richard Ouellette
SmarterShopperStore
Mobile: 401-585-9925
Email: rao22861@gmail.com

**Comment by digicoingroup** [comment]
Just got back. I've attached the 2 screenshoots as jpg files.

**Comment by mehtadone** [comment]
Sorry, am I being silly? I still can't see them.

**Comment by smoochy** [comment]
No, same here. I think, digi is replying to github via email and attaching the screenshots into the email. Which does not seem to work.

@digicoingroup can you please add the pictures via the github website, not reply via email?

**Comment by digicoingroup** [comment]
Good morning,

I'll post the 2 screenshots here:

![desktop-2018-03-25_9-07-37](https://user-images.githubusercontent.com/37671821/37975123-9d843752-31ac-11e8-907a-23b22a987033.jpg)
![hostsettings json_2018-03-25_9-09-29](https://user-images.githubusercontent.com/37671821/37975167-b0762bea-31ac-11e8-96df-52d9f8d3a264.jpg)

Hopefully that works!

**Comment by smoochy** [comment]
Please quickly remove that screenshot again, as your licence key can be seen.

**Comment by digicoingroup** [comment]
Thanks, I had 100% opaque blockage on the highlighter. What's the best way to effectively block that info?

**Comment by smoochy** [comment]
Remove the key from the file, take the screenshot, add it again.

**Comment by mehtadone** [comment]
@digicoingroup . I removed your comment just as it had license info. 

Couple of things to check: 

1. Your serverurl line has localhost with a space. Remove the space. 
2. Are you running with the same user? The folder you are pointing to is admin. 
3. Can you check that the application.properties file is in that directory.

**Comment by digicoingroup** [comment]
Got it! Makes sense.

**Comment by digicoingroup** [comment]
Space removed: 
![image](https://user-images.githubusercontent.com/37671821/37976062-9c745ad4-31ae-11e8-95bb-340ef0c59236.png)

Is that right?

**Comment by digicoingroup** [comment]
Revised screenshoot:
![image](https://user-images.githubusercontent.com/37671821/37976391-698c2c18-31af-11e8-862a-40b184b0fff9.png)

**Comment by digicoingroup** [comment]
I hope this answers the "Can you check that the application.properties file is in that directory."
![image](https://user-images.githubusercontent.com/37671821/37976823-5ceaa1b4-31b0-11e8-9645-a72783188ef1.png)

**Comment by digicoingroup** [comment]
I don't believe I've made any changes regarding..."Are you running with the same user? The folder you are pointing to is admin." How can I confirm that?

**Comment by smoochy** [comment]
Try to remove that space:

![37976391-698c2c18-31af-11e8-862a-40b184b0fff9](https://user-images.githubusercontent.com/34371932/37977483-14334af0-31e4-11e8-98e0-86785011e82a.png)

**Comment by digicoingroup** [comment]
Ok. Former space returned and later space removed...

![image](https://user-images.githubusercontent.com/37671821/37978078-27410942-31b3-11e8-874d-15484e279a9b.png)

**Comment by digicoingroup** [comment]
Ok. I ran the PT Feeder bot and took these screenshots:

![image](https://user-images.githubusercontent.com/37671821/37984243-c5abf618-31c3-11e8-9a37-602845fe5af9.png)

![image](https://user-images.githubusercontent.com/37671821/37984276-dc689d70-31c3-11e8-92cf-df5ec91f4ab9.png)

![image](https://user-images.githubusercontent.com/37671821/37984298-eb113864-31c3-11e8-85e2-2caab25d39ce.png)

How does it look?

**Comment by mehtadone** [comment]
Not good but better than previously. Can you try delete ptfeeder.db in your database directory and starting again?

**Comment by mehtadone** [comment]
That looks good now

**Comment by digicoingroup** [comment]
Thanks for your help. Any further tweaks or suggestions? I have a lot to learn!

**Comment by mehtadone** [comment]
Join the discord, watch some YouTube video, ask questions. We are working on bring out more educational content
