### ISSUE TITLE
[REQUEST] A DCA Min/MaxTrailingProfit/Buy

### ISSUE THREAD

**Issue by alexjbyron** [mehtadone/PTFeeder#279]
Hi,

Fairly self explanatory from the title but when trying to maximise profits etc., the individual settings for each pair that PTF creates for every coin, depending on Market Conditions, does not seem to translate when your coins are in DCA. The DCA settings for Profit and Buy are static and are set by DcaTrailingProfit/Buy in the appsettings. 

Most, if not all, of my pairs are in DCA all of the time so it would be nice to utilize PTFs ability to maximise your profits when coins are in DCA.

Thanks

**Comment by mehtadone** [comment]
PT does not support per pair configuration. How would you suggest this would work?

**Comment by alexjbyron** [comment]
I see, so per pair config does not work if in the DCA file? so if I put something like NEOETH_sell_only_mode = true or NANOETH_trailing_profit = 0.0854 into the DCA file it wouldn't work?

I didn't realise but thanks for the reply. Ill raise an issue with PT, if no one has already, as i don't see why they couldn't introduce this.

The only other way i could imagine to do it is to somehow push DCAs into pairs once they have been DCA'ed then back into DCA when they need to be but this would be far to complicated and probably impossible through PT.

Thanks again

**Comment by alexjbyron** [comment]
Alternatively, give users an option to push an average trailing profit etc into the DCA file. This could be determined from the data collected from the Pairs analysis that PTF does and based on the top X amount of coins you choose to analyse?

**Comment by mehtadone** [comment]
Well PT version 2 which is being tested at the moment has pair specific dca. Once that is released, I'll update feeder to support it. That will be the best solution

**Comment by alexjbyron** [comment]
Thanks for the response, much appreciated
