### ISSUE TITLE
error while running PT- FEEDER

### ISSUE THREAD

**Issue by ambatibalaji** [mehtadone/PTFeeder#284]
When I ran the command pt-feeder.dll, I got the below error:
Unhandled Exception: System.InvalidOperationException: Failed to convert '' to type 'System.Double'.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.ComponentModel.DoubleConverter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureI
   --- End of inner exception stack trace ---

**Comment by mehtadone** [comment]
There seems to be an issue with your appsetting.json. Can you copy and paste the contents of the file on pastebin.com and send me the link?

**Comment by ambatibalaji** [comment]
Hi Team,

PFB the link:

https://pastebin.com/pvgjcBF8

**Comment by mehtadone** [comment]
Try putting "DcaMinBuyBalance": "0",

**Comment by ambatibalaji** [comment]
sorry team,

I fixed tatt error

**Comment by ambatibalaji** [comment]
Hi Team,

I got the below error now:

Hosting environment: Production
Content root path: C:\profittrailer\profit feeder\ptfeeder.zip
Now listening on: http://localhost:8083
Application started. Press Ctrl+C to shut down.
[17:57:19 FTL] One of your api keys is not valid. Have you added your
default_key to your license using the telegram bot @ptfeederlicensebot?
Application is shutting down...

C:\profittrailer\profit feeder\ptfeeder.zip>


How to add default_key to the license

**Comment by mehtadone** [comment]
You can use the discord bot: PT Feeder License Bot#9756 or the telegram bot https://github.com/mehtadone/PTFeeder/wiki/License-Registration-and-Activation

**Comment by Belians18** [comment]
hi,

i'm having the same problem. how do i fix:

PT Feeder has shutdown due to an unhandled exception
