### ISSUE TITLE
Feeder Warnings

### ISSUE THREAD

**Issue by Daxxers** [mehtadone/PTFeeder#286]
<img width="879" alt="capture" src="https://user-images.githubusercontent.com/37769173/38065358-42b032c2-3346-11e8-91b8-7e5fa2ff93e1.PNG">

Hi, is this something to be concerned about? Thanks..

**Comment by Daxxers** [comment]
Saw the previous issue and installed Timesync, still no joy. Thanks.

**Comment by mehtadone** [comment]
This is nothing to be concerned about. As you can see, it is only a few pairs. Timezone helps when it is all pairs. 

This happens when there is either a connection blip or the exchange api doesn't return the right info, if its a new coin for example. this should solve on next run.
