### ISSUE TITLE
Need further explanation on how to increase Buy amounts....

### ISSUE THREAD

**Issue by Printersmith** [mehtadone/PTFeeder#287]
The bot is buying little $10 increments, so when I sell, it's making me .14 - .34 in USD which is not even worth my time to enter into Cointracking.  I want to make a MINIMUM $5 per trade, so I am playing with all the Min / Max settings, but I can't seem to get it to buy more than $10 - $20 at one time just yet.

I want to enter with $40 or .005BTC and top out at $200 or .02BTC when it stops buying and just rides it out.

There are a lot of options in the Wiki that have no corresponding setting in the .JSON and some in the .JSON that I cannot find in the Wiki.  

Could someone take the time who has experience and make a list for the brand new people that correlates every setting in the Wiki with what is in the .json

I would be very happy to pay the ETH to get this all done, thanks so much!!

**Comment by mehtadone** [comment]
A couple of things you can do. 

In hostsettings.json, set UseCostPercentage to false. 
Then in appsettings.json, set your MaxCost to 0.005.  
And in dca.txt file set your max_cost to 0.02. 

I think that should achieve what you want. 

Feel free to re-open the issue if you need more info or more explainations on why.
