### ISSUE TITLE
Excluded Pairs Not Working

### ISSUE THREAD

**Issue by vwodwo22** [mehtadone/PTFeeder#29]
I have  my excluded pairs as such for Binance however it is still selling these currencies. any ideas why?

  "ExcludedPairs": "XVGETH, ADAETH, TRXETH, IOTAETH, ZECETH",

**Comment by mehtadone** [comment]
It should be: 

"ExcludedPairs": "XVG, ADA, TRX, IOTA, ZEC",

**Comment by vwodwo22** [comment]
Even after changing to those excluded pairs, it still does not exclude them :/
