### ISSUE TITLE
Error in Profit Trailer

### ISSUE THREAD

**Issue by ambatibalaji** [mehtadone/PTFeeder#290]
Hi,
       I am getting following error in profit trailer. 
"2018-04-01 17:17:37 INFO ProfitTrailerService - Cache Heartbeat
2018-04-01 17:17:42 ERROR ProfitTrailerService - CB - [{"asset":"BTC","free":"0.00000261","locked":"0.00"

Can you tell me how to resolve the issue.

**Comment by mehtadone** [comment]
Hi, this is the wrong github
