### ISSUE TITLE
[BUG] Database grows too big, eating RAM and speed

### ISSUE THREAD

**Issue by bruce133** [mehtadone/PTFeeder#291]
My ptfeeder.db reached 116 MB before I decided to delete it. After restarting, it's now at just over 1 MB.

Reason for deleting it was that Feeder could no longer start due to the Feeder process hitting the memory limit I had set for it in PM2 at 300 MB. After deleting the database it starts up fine, performs its queries a lot quicker, and currently uses less than 150 MB of memory.

I suggest doing automatic cleanup during startup, perhaps even deleting the database.

**Comment by mehtadone** [comment]
The use of the database has been removed during the running of the application in the next version. If you could make do whilst we finish testing, that would be great!

**Comment by bruce133** [comment]
@mehtadone Sounds good, looking forward to it!
