### ISSUE TITLE
PTFeeder not DCAing

### ISSUE THREAD

**Issue by Cryptobolla** [mehtadone/PTFeeder#292]
I have been running my bot and pt feeder for about a month.   It is making trades, but does not dca. I have bags down 28 and 52 percent and it does not dca.  I am not sure what the problem is?

**Comment by jake501** [comment]
Without seeing what your settings are, it's hard to tell but just make sure that you have DcaEnabled = true or a number between say -1 to -5ish. Another thing to make sure is that you have a dca.txt file in either your market condition folders or your footer folder. That dca.txt is what determines what dca buy strat and triggers are sent to Profit Trailer.

Hope that helps!

-Jake

**Comment by Cryptobolla** [comment]
"General": {
    "BaseCurrency": "ETH", // MARKET
    "BuyStrategy": "LOWBB", // ALL_buy_strategy
    "BuyValue": "15", // ALL_buy_value
    "MaxCost": "0.009", // ALL_max_cost or or All_max_cost_percentage
    "DcaEnabled": "-3", // ALL_DCA_enabled
    "DcaMaxBuySpread": "1", // max_buy_spread in DCA.properties
    "DcaMaxBuyTimes": "5", // max_buy_times in DCA.properties
    "DcaMaxCost": "0", // max_cost in DCA.properties
    "DcaMinBuyBalance": "20", // min_buy_balance in DCA.properties
depending on UseMinBuyBalancePercentage in hostsettings.json
    "DcaSellStrategy": "GAIN", // sell_strategy in DCA.properties
    "DcaSellValue": "0.75", // sell_value in DCA.properties
    "DcaTrailingBuy": "0.15", // trailing_buy in DCA.properties
    "DcaTrailingProfit": "0.15", // trialing_profit in DCA.properties
    "ExcludedCoins": "BNB", // coins you don't want PTF to create settings
for. These will have no config generated and will appear in watchmode
    "SomOnlyCoins":
"MTL,DGD,TRIG,MTL,SWIFT,ARDR,SAFEX,BTA,DAR,DRACO,SLING,CRYPT,DOGE,UNO,SC,INCNT,NAUT,SJCX,NOTE,TKN,TIME",
// these are coins where BASE_COIN_sell_only_mode will be true
    "DcaIncludedCoins": "ETH", // if there are any coins in this list, ONLY
these coins will have dca enabled.
    "MaxBuySpread": "1", // All_max_buy_spread
    "TrailingBuy": "0.3", // All_trailing_buy
    "TrailingProfit": "0.3", // All_tailing_profit
    "MinBuyBalance": "50", // All_min_buy_balance or
All_min_buy_balance_percentage
    "MinBuyPrice": "0.00005", // All_min_buy_price
    "MinBuyVolume": "500", // All_min_buy_volume
    "MinutesForLongerTermTrend": "720", // minutes to measure trend for
LongerTermPriceChange
    "MinutesToMeasureTrend": "60", // minutes to measure trend for base
coin trend, PriceTrendChange and volatility calc
    "MaxTradingPairs": "15", // ALL_max_trading_pairs
    "SellStrategy": "GAIN", // ALL_sell_strategy
    "SellValue": "0.75", // ALL_sell_value
    "TopCurrenciesToCheck": "35" // number of pairs to check from your
exchange for MaxTopCoinAverageChange


 "MarketConditions": {
    "Configs": [
      {
        // If the top coins average is less than -1.5%, then go into Sell
Only Mode
        "FolderName": "01-bear",
        "MaxTopCoinAverageChange": "-1.5",
        "BuyValueOffset": "-30",
        "SellOnlyMode": "true",
        "SellValueOffset": "-20"
      },
      {
        // Only use the defaults if we are in a boring market - more than
-1.5 change and less than 0.5% change
        "FolderName": "02-boring",
        "MaxTopCoinAverageChange": "0.5"
      },
      {
        // Increase the buyvalue if we are in a bull market. More than 0.5%
and less 1000%. This is a catch all as in the market conditions, you need a
section for all scenarios.
        "FolderName": "03-bull",
        "MaxTopCoinAverageChange": "1000",
        "BuyValueOffset": "2"
      }
    ]
  },
  "Volume": {
    "Configs": [
      {
        // For any coins with a volume of less than 500 BTC, then increase
the trailingbuy by 10% and reduce the trailing profit by -20%
        "MaxVolume": "500",
        "TrailingBuyOffset": "10",
        "TrailingProfitOffset": "-20",
        "DcaEnabled": "-20"
      }
    ]
  },
  "PriceTrendChange": {
    "Configs": [
      {
        // if a coin has dropped more than -5% in  "MinutesToMeasureTrend":
"60", then go sell only mode and drop the SellValue by 20%
        "MaxPriceTrendPercentageChange": "-5",
        "SellOnlyMode": "true",
        "SellValueOffset": "-20"
      },
      {
        // if a coin has changed between -5% and 0.5% then increase the
TrailingProfit by 5% and reduce the TrailingBuy by -70%
        "MaxPriceTrendPercentageChange": "0.5",
        "TrailingBuyOffset": "-70",
        "TrailingProfitOffset": "5"
      }

I see
DCAenable -3 above, but no dcatext flie

**Comment by mehtadone** [comment]
Have you also looked at the PT log ? That normally gives clues if there are issues

**Comment by Cryptobolla** [comment]
What would I be looking for?

**Comment by mehtadone** [comment]
It's normally quite obvious. Balance warnings, cost warnings or errors.

**Comment by Cryptobolla** [comment]
I have some api errors from time to time, but they tend to go away?

**Comment by mehtadone** [comment]
Yes they are ok. Can you also share your dca.properties file

**Comment by Cryptobolla** [comment]
# ---------------COMMON PT FEEDER CONFIG-----------------------

buy_strategy = ANDERSON
buy_style = DOUBLEDOWN

ignore_sell_only_mode = false

buy_trigger_1 = -3.5
buy_trigger_2 = -4.5
buy_trigger_3 = -4.5
buy_trigger_4 = -5.5
buy_trigger_5 = -5.5



# ---------------USING 02-boring. WRITTEN ON Friday, April 6, 2018 6:54:31
AM UTC ---------------


#-------DO NOT MODIFY ANYTHING IN THIS FILE AS PT FEEDER IS IN CONTROL. IT
WILL OVERWRITE ANY OF YOUR CHANGES-------

enabled = true
trailing_profit = 0.15
trailing_buy = 0.15
sell_value = 0.75
max_cost = 0
max_buy_times = 5
sell_strategy = GAIN
max_buy_spread = 1
min_buy_balance = 0
min_buy_balance_percentage = 20


This is my DCA properties from Profit trailer

**Comment by b0nadrag** [comment]
DcaIncludedCoins: "ETH", // if there are any coins in this list, ONLY
these coins will have dca enabled.

See above.

In your config file, DCA is turned on for ETH only. Add the Exchange codes for the coins you wish to DCA.

**Comment by mehtadone** [comment]
Good spot @b0nadrag

**Comment by Rswtrader1** [comment]
Good afternoon fellas,
I am also having a DCA issue where PTF is not  DCAing. I want any coin that I buy to have the ability to DCA, so I used "All DCA Enabled". Evidently this is not correct and would appreciate you input to rectify the issue!

See below...
Thank you 

{
  "General": {
    "BaseCurrency": "BTC", // MARKET
    "BuyStrategy": "EMAGAIN", // ALL_buy_strategy
    "BuyValue": ".15", // ALL_buy_value
    "MaxCost": "0.155", // ALL_max_cost or or All_max_cost_percentage
    "DcaEnabled": "-1.5", // ALL_DCA_enabled
    "DcaMaxBuySpread": "0.5", // max_buy_spread in DCA.properties
    "DcaMaxBuyTimes": "5", // max_buy_times in DCA.properties
    "DcaMaxCost": "0.015", // max_cost in DCA.properties
    "DcaMinBuyBalance": ".0", // min_buy_balance in DCA.properties depending on UseMinBuyBalancePercentage in hostsettings.json
    "DcaSellStrategy": "GAIN", // sell_strategy in DCA.properties
    "DcaSellValue": ".55", // sell_value in DCA.properties
    "DcaTrailingBuy": "0.15", // trailing_buy in DCA.properties
    "DcaTrailingProfit": "0.15", // trialing_profit in DCA.properties
    "ExcludedCoins": "BNB", // coins you don't want PTF to create settings for. These will have no config generated and will appear in watchmode
    "SomOnlyCoins": "MTL,DGD,TRIG,MTL,SWIFT,ARDR,SAFEX,BTA,DAR,DRACO,SLING,CRYPT,DOGE,UNO,SC,INCNT,NAUT,SJCX,NOTE,TKN,TIME", // these are coins where BASE_COIN_sell_only_mode will be true
    "DcaExcludedCoins": "ALL_DCA_enabled", // if there are any coins in this list, ONLY these coins will have dca enabled.
    "MaxBuySpread": ".5", // All_max_buy_spread
    "TrailingBuy": "0.2", // All_trailing_buy
	"TrailingProfit": "0.38", // All_trailing_profit
    "MinBuyBalance": "0", // All_min_buy_balance or All_min_buy_balance_percentage
    "MinBuyPrice": "0.0000021", // All_min_buy_price
    "MinBuyVolume": "35", // All_min_buy_volume
    "MinutesForLongerTermTrend": "720", // minutes to measure trend for LongerTermPriceChange
    "MinutesToMeasureTrend": "120", // minutes to measure trend for base coin trend, PriceTrendChange and volatility calc
    "MaxTradingPairs": "45", // ALL_max_trading_pairs
    "SellStrategy": "GAIN", // ALL_sell_strategy
    "SellValue": "1.65", // ALL_sell_value
    "TopCurrenciesToCheck": "50" // number of pairs to check from your exchange for MaxTopCoinAverageChange
	},
  "MarketConditions": 
	{"Configs": [
      {
        // If the top coins average is less than -1.5%, then go into Sell Only Mode
        "FolderName": "01-bear",
        "MaxTopCoinAverageChange": "-3.5",
        "BuyValueOffset": "50",
        "SellOnlyMode": "true",
        "SellValueOffset": "-20"
      },
      {
        // Only use the defaults if we are in a boring market - more than -1.5 change and less than 0.5% change
        "FolderName": "02-boring",
        "MaxTopCoinAverageChange": "2.5"
      },
      {
        // Increase the buyvalue if we are in a bull market. More than 0.5% and less 1000%. This is a catch all as in the market conditions, you need a section for all scenarios.
        "FolderName": "03-bull",
        "MaxTopCoinAverageChange": "1000",
        "BuyValueOffset": "-50"
      }
    ]
  },
  "Volume": {
    "Configs": [
      {
        // For any coins with a volume of less than 500 BTC, then increase the trailingbuy by 10% and reduce the trailing profit by -20%
        "MaxVolume": "500",
        "TrailingBuyOffset": "10",
        "TrailingProfitOffset": "-20",
        "DcaEnabled": "-20"
      }
    ]
  },
  "PriceTrendChange": {
    "Configs": [
      {
        // if a coin has dropped more than -5% in  "MinutesToMeasureTrend": "60", then go sell only mode and drop the SellValue by 20%
        "MaxPriceTrendPercentageChange": "-5",
        "SellOnlyMode": "true",
        "SellValueOffset": "-20"
      },
      {
        // if a coin has changed between -5% and 0.5% then increase the TrailingProfit by 5% and reduce the TrailingBuy by -70%
        "MaxPriceTrendPercentageChange": "0.5",
        "TrailingBuyOffset": "-70",
        "TrailingProfitOffset": "5"
      }
    ]
  }
}
