### ISSUE TITLE
[REQUEST] Better telegram follow up

### ISSUE THREAD

**Issue by BroTastix** [mehtadone/PTFeeder#293]
- Trend Changes:
Perfect as is.

- New Bought Coins:
If a new pair is bought (+amount), When a DCA is triggered and wich DCA is triggered.

- New Sells:
For every sell a message, Pairs, DCA and pending pairs.
Incl the amount, the amount of profit in %, , amount of DCA.

- Crash of PT software:
If the bot crashes, telegram message.

- Sum up
24h sum up with amount of profit in $ and %, amount of sells
weekly sum up with amount of profit in $ and %, amount of sells
Perfect scenario would be sending /weekly or /daily to telegram bot and we get the notification. Don't know if this is possible, an automated sum up after 24h should be possible to code from the bot.

**Comment by mehtadone** [comment]
Hey, this seems to be a request for PT not PT feeder as it's PT that is the trading engine. I'll suggest requesting this on the PT github but if you have PT pro, PT notifications does this
