### ISSUE TITLE
[Bug Alert] trailing_profit and trailing_buy are not calculating correctly

### ISSUE THREAD

**Issue by hargate** [mehtadone/PTFeeder#295]
@mehtadone 

trailing_profit and trailing_buy are not calculating correctly. To test this issue, I removed all trailing_profit and trailing_buy offsets from the appsettings.json file (attached as appsettings.txt). PTF still created individual coin trailing_profit and trailing_buy values in the PAIRS.properties file (attached as PAIRS.txt).

This issue was previously identified in issue 260 (link below), but has not received any comments by the development team. Therefore, I am re-submitting with [Bug Alert] in the title.

Calculating the trailing values seems to be a core function of PTF, but cannot be used until this bug is fixed.

https://github.com/mehtadone/PTFeeder/issues/260

[appsettings.txt](https://github.com/mehtadone/PTFeeder/files/1886710/appsettings.txt)
[PAIRS.txt](https://github.com/mehtadone/PTFeeder/files/1886711/PAIRS.txt)

**Comment by mehtadone** [comment]
Can you give a little bit more explaination of why you think they are not calculating correctly?

I see that the pairs have different trailing buy and trailing profit values.

**Comment by hargate** [comment]
I removed all trailing_profit and trailing_buy offsets from the appsettings.json file. Therefore, all pairs should have the value set in the General section.

Obviously, I typically use offsets, but realized that I wasn't getting the results that I expected (they were VERY low). So, I turned off PTF, removed all trailing offsets, turned PTF on, let it run through multiple cycles, and still got results that are unexpected (e.g. not seeing the default trailing values).

**Comment by mehtadone** [comment]
That is why the pairs are all different. There is an opportunity to update the wiki which I hope to work on this week . But the trailings are calculated from the volatility calculations https://github.com/mehtadone/PTFeeder/wiki/Trailing-Volatility

**Comment by hargate** [comment]
Thank you very much
