### ISSUE TITLE
PTF causing SOM Only on PT 

### ISSUE THREAD

**Issue by BenBlignaut** [mehtadone/PTFeeder#297]
All possible buy on PT showing SOM Enabled. PT support reckons it is a PTF issue

**Comment by mehtadone** [comment]
Have you had a look at the pairs.properties? PTF writes the reason for putting pairs in SOM as a comment just above each pair specific property set

**Comment by BenBlignaut** [comment]
It just came right now. I think this may have something to do with the Binance API issue earlier

Thanks anyway



Sent from my Samsung Galaxy smartphone.


-------- Original message --------
