### ISSUE TITLE
PTF Not adding strategy or triggers to DCA.properties

### ISSUE THREAD

**Issue by bpkenn** [mehtadone/PTFeeder#298]
I'm seeing an issue with PTF not adding in the DCA Buy strategy and triggers in the DCA.properties.

I'm migrating my config from a known working windows setup, to Ubuntu Linux VM.  The only configuration change made was in the host settings to define the trading folder. It looks like PTF is generating and modifying the files just fine, so I don't think its any type of permission issue.  Here is a snip showing the missing config

![image](https://user-images.githubusercontent.com/1319589/38571338-da4e4eac-3cb5-11e8-86e9-e9187137ce34.png)

**Comment by mehtadone** [comment]
Check that the txt files are there and named correctly in the market condition folders. Linux is case sensitive so they need to be dca.txt, indicator.txt and pairs.txt

**Comment by bpkenn** [comment]
That was the issue!  Thanks!
