### ISSUE TITLE
PT Feeder Problem

### ISSUE THREAD

**Issue by Galvez100** [mehtadone/PTFeeder#30]
Hello, I was wondering why I am getting this error message:
"Bollox. Something went wrong getting config for BTC-SUB. Will use default config
 System.NullReferenceException: Object reference not set to an instance of an object.
   at Services.services.OverrideService.SanitizeProperties(Pair pair)
   at ptfeeder.ProfitTrailer.<PairSpecificConfig>d__14.MoveNext() in C:\projects\profittrailer-config-generator\pt-feeder\ProfitTrailer.cs:line 239"

I get that error with every single pair and the bot wont begin trading as it has no settings to trade with. Would appreciate any help. Thanks

**Comment by Galvez100** [comment]
I might add that PT Feeder is running on my home PC as of now and the time and date are both set correctly. Is there any setting that will allow me to edit the time inside PT Feeder? I also tried to set it to automatic and it still shows the same error

**Comment by mehtadone** [comment]
This is when there are missing properties in the appsettings.json file. Better warning messages will be added in the next beta.

See the upgrade instructions on https://github.com/mehtadone/PTFeeder/releases/tag/pt-feeder-v1.3.3.206
