### ISSUE TITLE
Sell strategy to remain the same when pair is bought

### ISSUE THREAD

**Issue by yohgii** [mehtadone/PTFeeder#300]
Is it possible to keep the sell strategy the same on the pair bought even when the market folder changes?

**Comment by mehtadone** [comment]
Can you give me an example where it is different? If it is changing, there will be something in feeder settings that says it should change.

**Comment by yohgii** [comment]
when my market folder changes to bull the sellvalueoffset is 30. So the Trigger % on my bot goes up. When it does, it resets the trigger%. For instance, I was in bull and the trigger was hit and it was trailing, but, when the folder changed trigger % changed to the Profit %. This has prevented a few sales already. My trigger was 5.35. it went to 6.4. the folder changed to bull and trigger went to 7%. it didn't hit 7% the market changed back to boring and 5.35 trigger but by that time the profit % was at 5. My trailing profit is about 1%

**Comment by mehtadone** [comment]
I confirmed this with the PT devs and they said it should reset the trailing or trigger. If it is, would you mind raising an issue on the PT github.
