### ISSUE TITLE
[REQUEST] BTC-ETH-USDT Market switch functionality

### ISSUE THREAD

**Issue by aalemayehu** [mehtadone/PTFeeder#302]
Hello, 
I love your product. Just had a quick suggestion. Is it possible to get a market switching functionality where if the underlying currency in the current market changes by a certain %, feeder would be able to switch to a different market? This would definitely help solve the risk of BTC shooting up and being stuck with bags of ALTS. 

Let me know what you think and thanks again, 
Addis

**Comment by mehtadone** [comment]
As @zapedge mentioned, this needs to be done in PT not PTF as PTF doesn't have the bought orice
