### ISSUE TITLE
High/Low Percentage calculation

### ISSUE THREAD

**Issue by Mtrade** [mehtadone/PTFeeder#304]
Can you confirm that PTFeeder is taking the required OHLC info from the exchange for this calculation, and that the listed formula is being applied correctly?

As an example, as at April 15 22:45 UTC data for Binance BTC-IOTA was:
720 min. high: 21000
720 min. low: 19100

Using the formulas listed:
First variance = (21000-19100)/2 = 950
Median variance = 21000 - 950 = 20050
Highlow percentage = (19534 - 20050) / 19534 * 100 = -2.6415%

This is the data output to the PAIRS file at that time, showing High/Low price change (720) at -0.89%

------------------BTC/IOTA------------------
Last Price: 0.00019534
Volume: 5085.0453
Price change (60): -0.65%
Price change (720): -0.22%
High/Low price change (60): -0.8%
High/Low price change (720): -0.89%
Upside volatility: 0.44%
Downside volatility: 0.46%

This apparent discrepancy seems to be happening on some pairs, while others appear to be calculating more accurately. Not sure if this is a coincidence.

**Comment by mehtadone** [comment]
This is exactly what is done. Volume is taken from OHLC. 

There have been some improvements with candles on version 1.5 so would be interesting to see if it still happens there.
