### ISSUE TITLE
Error whilst trying PT End Point

### ISSUE THREAD

**Issue by Mystakilla** [mehtadone/PTFeeder#309]
System invalid operation exception, an invalid request URI was provided.

Im currently running on a virmach VPS, not sure if this is the issue or not, ive tried localhost:8081, didnt help.  any ideas?   Thanks for the help

BTW, i currently upgraded to V2.0 PT and V1.5 PF and just now receiving this error.

**Comment by mehtadone** [comment]
It needs to be the full URL that you access profit trailer on. So http://localhost:8081 for example. If you've tried this, can you post the full error and the snippet of your hostsettings file
