### ISSUE TITLE
Support: Could not work out which market

### ISSUE THREAD

**Issue by yohgii** [mehtadone/PTFeeder#314]
Just upgraded to the new pt and ptf. I am getting the error "Could not work out which market condition to use. Using the last one". How do I fix this?

**Comment by mehtadone** [comment]
Can you share your appsettings please?

**Comment by yohgii** [comment]
I fixed it. It was an extra break.

**Comment by yohgii** [comment]
thx bro

**Comment by mehtadone** [comment]
Ahh perfect. Sorry I didn't get to help in time, but fixing yourself is more rewarding!
