### ISSUE TITLE
hostpolicy.dll error

### ISSUE THREAD

**Issue by Ereezy** [mehtadone/PTFeeder#318]
I keep getting:

 "a fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found"

When trying to run the new PT Feeder version

**Comment by NOZ00** [comment]
I 2nd that issue

**Comment by mehtadone** [comment]
Can you check that you installed dotnet sdk 2.1.4 correctly. https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.4 including a restart on your PC if you are on windows??

**Comment by Ereezy** [comment]
I checked my pc today and restarted it and the screen that they show on the .NET website pops up just like the picture after typing in dotnet but I still get that hostpolicy error.

**Comment by Ereezy** [comment]
NOZoo,

Whatd you do to get it working?

**Comment by mehtadone** [comment]
Duplicate of: https://github.com/mehtadone/PTFeeder/issues/322
