### ISSUE TITLE
Dust Values - Binance reduced back to 0.000999

### ISSUE THREAD

**Issue by Uruwashii** [mehtadone/PTFeeder#319]
Hello, Binance have dropped their min values back down to 0.001 for BTC , 0.02 for ETH etc. - Appsettings have previous 0.02 values (BTC as example).

Confired new valies for dust are:

BTC_dust = 0.000999
ETH_dust = 0.00999
BNB_dust = 0.999
USDT_dust = 9.99

**Comment by mehtadone** [comment]
Will be updated in version 1.7
