### ISSUE TITLE
Unhandled Exception: Microsoft.Data.Sqlite.SqliteException: SQLite Error 1:

### ISSUE THREAD

**Issue by Kizzle65** [mehtadone/PTFeeder#320]
So I upgraded my PT and PTF today to the latest versions.  PT works fine and then I upgrade PTF, start it and get this error after I start it.  Can anybody point me in the right direction of what is the issue? 

![capture](https://user-images.githubusercontent.com/35324718/39401675-f05351d6-4b18-11e8-9e05-31f5c5b94ed2.PNG)

**Comment by tash649** [comment]
@Kizzle65 can you delete database file?

**Comment by Kizzle65** [comment]
That worked.  now i get this error. FTL] One or more valid profit trailer config directories must be set so application.properties can be found.  Getting this error.  I am taking that it is the new path/directory for the newest version but I have rechecked it and can't figure it out unless it's something completely different that is wrong.  Anyone have any ideas?
