### ISSUE TITLE
FTL] One or more valid profit trailer config directories must be set so application.properties can be found. 

### ISSUE THREAD

**Issue by Kizzle65** [mehtadone/PTFeeder#321]
FTL] One or more valid profit trailer config directories must be set so application.properties can be found.  Getting this error.  I am taking that it is the new path/directory for the newest version but I have rechecked it and can't figure it out unless it's something completely different that is wrong.  Anyone have any ideas?

**Comment by mehtadone** [comment]
Have you added ProfitTrailerEndPoint1 to your hostsettings?

**Comment by Sarafan31** [comment]
I have the same problem, and no idea to fix it

**Comment by mehtadone** [comment]
Can you send me the contents of your hostsettings file? Removing any keys

**Comment by bkcrypto808** [comment]
hi, after upgrading PT to 2.x new version I get the same error. Upgraded PFeeder to latest as well.
What is ProfitTrailerEndPoint1 entry?

**Comment by CPin77** [comment]
Has anyone found a fix for this? I just Installed PT Feeder and also getting this Error msg.

**Comment by bkcrypto808** [comment]
Cpin77, what is your profit trailer url (can x out the ip if you have it)

**Comment by bkcrypto808** [comment]
Cpin77, for profitrailderfolder1, what do you have listed?

**Comment by CPin77** [comment]
192.168.1.92:8081/monitoring

**Comment by bkcrypto808** [comment]
Sounds good! Good luck

**Comment by CPin77** [comment]
Unfortunately it didn’t work. I’ve tried multiple PTFolder1 paths and nothing seems to work.

**Comment by CPin77** [comment]
C:\\Users\\Jay\\Desktop\\ProfitTrailer\\Initialization”,

**Comment by mehtadone** [comment]
It should be without the initialisation. Also, what do you have as your ProfitTrailerApiEndPoint1?

**Comment by mehtadone** [comment]
It should be without the monitoring at the end

**Comment by Kizzle65** [comment]
This is what I have so far. 
![capture](https://user-images.githubusercontent.com/35324718/39660612-c3bb3c4a-5010-11e8-9226-77a24813a9c9.PNG)

**Comment by mehtadone** [comment]
This looks correct. If you are still getting the error, try changing https to http. If it is still a problem, please re-open the issue

**Comment by CPin77** [comment]
I’ll give this a try. Thanks again for your help.
