### ISSUE TITLE
hostpolicy.dll fatal error - PTF not working

### ISSUE THREAD

**Issue by CryptoFrogg** [mehtadone/PTFeeder#322]
Hey,
@zwarbo on Discord help pointed to me that I should write here regards my fatal error issue... 

I've upgraded PT1.x to PT2.x and (still) working superb :) ... also I've upgraded PTF1.4x to PTF1.5.x and this fatal error is blowing my mind... when opening CMD and writing dotnet pt-feeder.dll is not wotking.. i've tried repairing .net and rebooting, tried uninstalling, rebooting and reinstaling, and the result is the same... also the %PATH% is ok and showing (C:/Program files/dotnet).. 

I would appreciate any help, so I can run PTF with PT.. 

![6](https://user-images.githubusercontent.com/38881883/39471141-c81cafe8-4d41-11e8-89ec-373dd3b5d89a.JPG)

**Comment by hit770** [comment]
I have same issue.

**Comment by mehtadone** [comment]
@CryptoFrogg @hit770 can you try running the pi version from the release page? Same way as you are, it just comes with more dependencies included in the zip

**Comment by CryptoFrogg** [comment]
Did try it. not working... 
same error.. .

**Comment by mehtadone** [comment]
I'm a little stuck too. Do you have any dotnet runtimes installed? Seems to be one potential solution https://github.com/aspnet/Home/issues/2943

**Comment by mehtadone** [comment]
Seems like you've tried everything. I think you mentioned on chat you uninstalled and reinstalled the dotnet SDK. I remember you showing on chat that it was working initially and there was another error. Can you remember what you did in the middle which started causing this error?

**Comment by Ereezy** [comment]
this has not worked for me either since I downloaded the new file (1.5) for PT 2.0

**Comment by tash649** [comment]
@Ereezy where are you from?

**Comment by CryptoFrogg** [comment]
ok thnx guys

**Comment by mehtadone** [comment]
http://forum.ptfeeder.co/t/hostpolicy-dll-fatal-error-ptf-not-working/41
