### ISSUE TITLE
PT Feeder "Cannot find BaseCurrency in your setting json files

### ISSUE THREAD

**Issue by starkindustries89** [mehtadone/PTFeeder#327]
Hi, 
when i try to start the pt feeder, the error in the title occurs.

https://pastebin.com/n7Sf8Af6 <---- hostsettings.json
https://pastebin.com/JMAmdyYy <---- appsettings.json

Can someone help me please?

Chris

**Comment by mehtadone** [comment]
You seem to be using an old appsettings with the new feeder. The format of the appsettings has changed
