### ISSUE TITLE
Registering API Keys

### ISSUE THREAD

**Issue by Knopfler23** [mehtadone/PTFeeder#33]
I added my license through the bot, but when I went to add my API it now just spits out its default language--"Welcome to the PT Feeder License Bot. Type /manage for a list of commands"--without and won't do anything else! How am I supposed to get this running!!

**Comment by mehtadone** [comment]
Please message me on Discord and I'll help sort it out

**Comment by Knopfler23** [comment]
What is your discord tag number.

**Comment by Knopfler23** [comment]
Im unable to find you there.

**Comment by mehtadone** [comment]
mehtadone#8253

**Comment by Knopfler23** [comment]
Thank you. I just sent an invitation request.
