### ISSUE TITLE
Price trend value changes

### ISSUE THREAD

**Issue by Mtrade** [mehtadone/PTFeeder#331]
A suggestion/request - does Feeder retain prior values of PriceTrend and LongerTermPriceTrend for example? Being able to determine the actual change in the calculated value of LongerTermPriceTrend from X periods ago would be helpful to identify price trend shifts. EX. If the LongTermPriceTrend value was significantly negative and is now becoming more positive, that could signal a potential upside move. However if LongTermPriceTrend is decreasing after being quite positive that could signal a potential downside move.

I.e. the idea of PriceTrend value of X becomes more significant if we know what came before it, and consequently whether it is changing to become more positive or negative.

**Comment by mehtadone** [comment]
moved to forum: 

http://forum.ptfeeder.co/t/price-trend-value-changes/26
