### ISSUE TITLE
LongerTermPriceTrendGrouping doesn't honor Sell Only Mode

### ISSUE THREAD

**Issue by climbcolorado** [mehtadone/PTFeeder#332]
This is the config:

    "LongerTermPriceChangeGrouping": {
    "Configs": [
      {
        "MaxPriceTrendPercentageChange": "0" ,
		"SellOnlyModeEnabled": "true",
		"Override": {
		},
      },
	  {
        "MaxPriceTrendPercentageChange": "100000",   
		"Override": {
		},		
      }
    ]
  },

-=-= This coin should be set to SOM -=-=
#------------------BTC/BCPT------------------
# Last Price: 0.00005117
# Volume: 291.0821
# Coin age: 11/14/2017 00:00 UTC
# Price change (360): 0.37%
# Price change (1440): -1.41%
# Volume change (360): -98.46%
# Volume change (1440): -98.91%
# High/Low price change (360): 0.21%
# High/Low price change (1440): -0.81%
# Upside volatility: 0.25%
# Downside volatility: 0.2%

BCPT_Dca_Enabled = -1
BCPT_Trading_Enabled = true
BCPT_Trailing_Buy = 1.75
BCPT_Trailing_Profit = 3

**Comment by climbcolorado** [comment]
[ptfeeder15-appsettings_json.txt](https://github.com/mehtadone/PTFeeder/files/2010604/ptfeeder15-appsettings_json.txt)

**Comment by climbcolorado** [comment]
This turned out to be a typo in the config.   Sorry, please close!

**Comment by mehtadone** [comment]
No problems

**Comment by climbcolorado** [comment]
If anyone cares.   This was changed from the 1.4 version to include Trend in the name.

LongerTermPriceChangeGrouping = LongerTermPrice**Trend**ChangeGrouping
