### ISSUE TITLE
OBV

### ISSUE THREAD

**Issue by spinmaker** [mehtadone/PTFeeder#333]
hey guys, PTF keeps changing OBV, for example it changes it to:

O_B_V_Candle_Period = 300
O_B_V_Length = 50
O_B_V_Signal = 1

when it should be:

OBV_Candle_Period = 300
OBV_Length = 50
OBV_Signal = 1

**Comment by tash649** [comment]
You should set ObvCandlePeriod in appsettings.json instead OBVCandlePeriod. @spinmaker
