### ISSUE TITLE
WRN - Program Issues message 

### ISSUE THREAD

**Issue by NOZ00** [mehtadone/PTFeeder#335]
Hi

I'm just wondering why I'm getting the WRN message when running PTF, image attached.
Cannot calculate... The coins don't exist? 
<img width="778" alt="screen shot 2018-05-19 at 1 07 58 pm" src="https://user-images.githubusercontent.com/38798870/40264401-14724aec-5b66-11e8-84fb-c8b9a544d3b9.png">

Anyone know what's happening here?
PTF is still running but I would rather not have this issue just in case.

Thanks
Phil

**Comment by mehtadone** [comment]
These are coins where there is not enought data returned from the exchange. The coin name was sent via the api hence why PT tries to check it. Nothing to worry about
