### ISSUE TITLE
A JSON parsing exception occurred in [... pt-feeder.runtimeconfig.json]: * Line 1, Column 2 Syntax error: Malformed token

### ISSUE THREAD

**Issue by cedricscheepers** [mehtadone/PTFeeder#338]
I just upgraded to the latest version, and this happened.

![screen shot 2018-05-21 at 10 26 16](https://user-images.githubusercontent.com/7846485/40297906-a98475d4-5ce1-11e8-9e4f-969062fbf127.png)

**Comment by mehtadone** [comment]
Which version did you move from and to?

**Comment by cedricscheepers** [comment]
From v1.5.1.685 to the latest version

**Comment by cedricscheepers** [comment]
@mehtadone - The old version was working until I stopped it to upgrade. I'll roll back now to see. I am currently using a VPS.

**Comment by cedricscheepers** [comment]
@mehtadone - Rolled back and it is working

**Comment by mehtadone** [comment]
Sorry, I meant a linux VPS. The only reason for mentioning that is that there wasn't a solution so it may take trying a couple of things to get this working. 

Can you let me know the output of when you type `dotnet --version`? @cedricscheepers

**Comment by cedricscheepers** [comment]
2.1.101

![screen shot 2018-05-21 at 12 47 12](https://user-images.githubusercontent.com/7846485/40303964-2829a7f2-5cf5-11e8-89b1-5cbc05f37d72.png)

**Comment by mehtadone** [comment]
Can you try installing 2.1.4? 

https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.4

**Comment by cedricscheepers** [comment]
I upgraded dotnet, now the following happens:

![screen shot 2018-05-21 at 13 09 07](https://user-images.githubusercontent.com/7846485/40304780-5027411c-5cf8-11e8-9417-0870a4b66ca7.png)

**Comment by cedricscheepers** [comment]
Rolled back to previous version, it is working

**Comment by mehtadone** [comment]
@cedricscheepers that second error is easy to fix. remove the ptfeeder.db file from your database directory.

**Comment by cedricscheepers** [comment]
@mehtadone - Perfect, I'm closing the issue.

Thank you for your support, it is as great as PT Feeder, I appreciate it.  Keep up the great work!  :-)
