### ISSUE TITLE
MaxPairsOffset result not being recognised by profit trailer when its is not an integer

### ISSUE THREAD

**Issue by max00d** [mehtadone/PTFeeder#34]
When the result of setting 'MaxPairsOffset' results in a float this is not recognised by profit trailer and it endlessly buys.  As a results i have 17 pairs currently trading when the value of MaxPairsOffset is '7'.  When going into 'bear' config it reduced this value by 20% to 5.8 - at this point PF endlessly bought until I caught it.

Not strictly an issue with PTF but being raised because it results in an issue in PT.  This value should be rounded to an integer from PTF.

When the PAIRS.proporties file is written and a float occurs - the only way to prevent it from buying endlessly is to manually change the value to an integer (hence the reason for it being raised).

**Comment by mehtadone** [comment]
Which version of PTF are you using?

**Comment by max00d** [comment]
I'm running a version I downloaded on Saturday so am assuming v1.3.2.194.  Is there is a way I can check then I will.

**Comment by mehtadone** [comment]
It was fixed in 1.3.3 which is the latest on github. I'd reccomend updating to that. Version number is just in the filename on the zip at the moment

**Comment by mehtadone** [comment]
Reopen if needed
