### ISSUE TITLE
[REQUEST] TradingView Alerts Signal Length

### ISSUE THREAD

**Issue by dhollings** [mehtadone/PTFeeder#341]
Currently if you connect tradingview alets to Feeder via gmail this applies:

"The alerts are valid for how long you set SignalLength in your hostsettings.json (default is 15 mins) After this time, the setting for that coin will revert back to the DEFAULT settings or any other pair overrides you have."

REQUEST that the SignalLength have the option to allow TOGGLING, in other words... signal stays in effect until a new signal is received.

If you want to have TradingView give a toggling signal like a) Good Time To Trade b) Stop Trading (sort of a red light / green light thing).  Then the current SignalLength length settings is not the best.  

Perhaps for now we can set the SignalLength to a big number like 1440 and the next signal would override the first.  Maybe?

**Comment by mehtadone** [comment]
Moved to forum:
