### ISSUE TITLE
Pending_Order_Wait_Time was converted to Decimal

### ISSUE THREAD

**Issue by SG2010** [mehtadone/PTFeeder#342]
According to Profit Trailer Wiki, Pending_Order_Wait_Time and DCA_Pending_Order_Wait_Time should be Integer.  But after setting Integer "PendingOrderWaitTime" and "DcaPendingOrderWaitTime" the value is converted to decimal and not being honored by Profit Trailer.

(i.e. PendingOrderWaitTime = 2880, then in Profit Trailer Config -> Pair, Pending_Order_Wait_Time became 2880.0)

**Comment by mehtadone** [comment]
Recorded on our private github. Closing on here as will be closing github issues to move to a forum
