### ISSUE TITLE
Pt-feeder setup help

### ISSUE THREAD

**Issue by StelarHalfing** [mehtadone/PTFeeder#343]
When i unzip profit trailer and setup the config with my license key and everything needed i run the dotnet ptfeeder.dll           pause code and i get an error which i currently do not know how to fix (i also have the latest version of dotnet and microsoft frame)  

Error:
  An assembly specified in the application dependencies manifest (pt-feeder.deps.json) was not found:
    package: 'Microsoft.ApplicationInsights.AspNetCore', version: '2.1.1'
    path: 'lib/netstandard1.6/Microsoft.ApplicationInsights.AspNetCore.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.0-linux-x64.xml;aspnetcore-store-2.0.0-osx-x64.xml;aspnetcore-store-2.0.0-win7-x64.xml;aspnetcore-store-2.0.0-win7-x86.xml

PAUSE
Press any key to continue . . .

i took out the file location for security reasons can anyone help me?

**Comment by mehtadone** [comment]
You've installed the wrong version of dotnet. If you use the one linked in the wiki installation instructions, it should be fine

**Comment by StelarHalfing** [comment]
I uninstalled dotnet and reinstalled it from the wiki and i am still getting the same error

**Comment by StelarHalfing** [comment]
Never mind i got it thanks for the help
