### ISSUE TITLE
no comment written to PT config for selected config/group

### ISSUE THREAD

**Issue by davewantsmoore** [mehtadone/PTFeeder#346]
When this config is selected.   I get a comment (under, # Selected configs #) for each applicable pair.
```
"MyGrouping": {
	  "Condition": "[pair.Volume] >= [config.Vol]",
		  "Configs": [{
			"Vol" : "20",
          "TrailingProfitOffset" : "100"	
```

... but for either of these next two.  I don't get a comment in the top section of the PT config, to indicate they've been selected.    But they ARE being selected (I can see my MaxTradingPairsOffset has been doubled as expected).

```
"MyGrouping": {
	  "Condition": "[positions.TotalPairsBoughtCost] <= [config.Cost]",
		  "Configs": [{
			"Cost" : "20",
          "MaxTradingPairsOffset" : "100"	
```

```
"MyGrouping": {
	  "Condition": "[market.TopCoinsChange(1)] <= [config.Vol]",
		  "Configs": [{
			"Vol" : "20",
          "MaxTradingPairsOffset" : "100"	
```

**Comment by mehtadone** [comment]
Just as a workaround for this until I get chance to fix it, if you add `[pair.LastPrice] > 0` to your groupings, it will get printed in your pair comments. For example:

```
"MyGrouping": {
	  "Condition": "[positions.TotalPairsBoughtCost] <= [config.Cost] && [pair.LastPrice] > 0 ",
		  "Configs": [{
			"Cost" : "20",
          "MaxTradingPairsOffset" : "100"
```
