### ISSUE TITLE
Default buy timeout after sell

### ISSUE THREAD

**Issue by BeldarConehead** [mehtadone/PTFeeder#347]
In the appsettings.json file there's a setting "RebuyTimeout", changing it changes the PT Pairs file setting "DEFAULT_Rebuy_Timeout", but on the PT Wiki site, there is no "DEFAULT_Rebuy_Timeout" setting. There is one for "DEFAULT_buy_timeout_after_sell". Is PT Feeder not changing this correctly? Is "RebuyTimeout" supposed to be the setting for timeout after a sale? Is this a bug?

**Comment by mehtadone** [comment]
Feeder translates settings from appsettings to PT. So you can use BuyTimeoutAfterSell in your appsettings if that is what you require. rebuy timeout was deprecated as part of https://github.com/taniman/profit-trailer/releases/tag/2.4.25

**Comment by BeldarConehead** [comment]
If it was depreciated in 2.4.25, why am I seeing it in my installations of 2.4.28?

Sincerely,

David Kaye

**Comment by mehtadone** [comment]
You need to remove it from your settings. PT or Feeder won't change your settings for you.

**Comment by BeldarConehead** [comment]
Got it, thank you.
