### ISSUE TITLE
Error -4092 EACCES permission denied

### ISSUE THREAD

**Issue by Dougwoody** [mehtadone/PTFeeder#35]
Hello,
I believe this issue is something i'm just overlooking. PT was easy to get up and running and Feeder seemed to be just as easy. Although when I start the batch file, I get this error.

Error -4092 EACCES permission denied
Failed to bind to address http://localhost:8083

Any help would be appreciated. Thanks in advance.

**Comment by mehtadone** [comment]
IS your port already in use? Change the port in PT feeder to something that isn't being used. 

Reopen is needed
