### ISSUE TITLE
Nest full strategies under MarketConditions

### ISSUE THREAD

**Issue by pmedia1000** [mehtadone/PTFeeder#37]
It would be a good idea to be able to nest full strategies under market conditions, so we can define a complete set of parameters for different markets like:

01-superbear  >> EMAGAIN....
...
05-superbull   >> LOWBB

**Comment by sha-doh** [comment]
I agree, this would be beneficial, or at least allowing us to switch strategy that would remain persistent in hotconfig..

**Comment by XcidTrader** [comment]
up vote x 100

**Comment by damajicman3** [comment]
I agree. I tried to add some in there but didn't work.

**Comment by MetaAtman** [comment]
Fully agree! The most needed feature

**Comment by timtaylorrr** [comment]
Would it be possible to add a line to each market condition and leave the general buy strategy empty?

**Comment by mehtadone** [comment]
No, as you'll end up with it twice in your pair.properties. Also you need different buy values for each strategy.

**Comment by timtaylorrr** [comment]
So would it be possible to use different strategies with the current version?

**Comment by XcidTrader** [comment]
The dynamic market settings are based off the default settings which act as a base. So I’d imagine you can’t leave them empty . I think the defaults are essentially the Boeing market .

I’d love to know if you could use a diff buy strat in one of the defined  markets

**Comment by timtaylorrr** [comment]
I tried that already:

System.AggregateException: One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (Cannot find BuyStrategy in your appsettings.json))) ---> System.AggregateException: One or more errors occurred. (One or more errors occurred. (Cannot find BuyStrategy in your appsettings.json)) ---> System.AggregateException: One or more errors occurred. (Cannot find BuyStrategy in your appsettings.json) ---> System.MissingFieldException: Cannot find BuyStrategy in your appsettings.json

**Comment by iller75** [comment]
Upvote from me.

**Comment by Duskfall** [comment]
This is a must. Any hint on this release?

**Comment by efahrenholz** [comment]
How about we remove the buy strat and buy value from the appsettings.json and have the user define them in the markets folder? This way we can dynamically alter the strategy as feeder updates which market it sees itself in. It's going to copy pasta the files from the market folder anyways. I'd love to see some offsets applied to buy value but I realize that could get...complicated. Let's just do the easy part first.

**Comment by fjdelaba** [comment]
Sorry didnt see that it was here!, still a great idea!

**Comment by mehtadone** [comment]
Added in 1.4

**Comment by Duskfall** [comment]
Thanks for this! Does this also work for SellStrategy?
````
"SellStrategy": {
   "BuyValue": "-10",
    "SellStrategy": "HIGHBB",
    "Weight": "55",
    "SellValue": "2.5", // change also the sell value
}

**Comment by mehtadone** [comment]
Only buy for this release but sell will be added in 1.4.1
