### ISSUE TITLE
Specify which coins to trade

### ISSUE THREAD

**Issue by timh77** [mehtadone/PTFeeder#40]
In PT you can specify which coins you want to trade. Sometimes this is easier then excluding those. Would it be possible to add such a feature to FTP?

ALL_enabled_pairs=ADABTC, ARKBTC, COIN, COIN, COIN

**Comment by mehtadone** [comment]
Add a property called EnabledPairsOnly in your appsettings.json in version 1.3.3+. This is undocumented at the moment and in testing so please check the pairs.properties generated first before turning on PT.

**Comment by timh77** [comment]
Just tested it a few times on different installations. Everything looks okay. Only the specified pairs were added to the pairs file and none were missing.

Bedankt! ;-)
