### ISSUE TITLE
PTFeeder doesn't allow for docker setup

### ISSUE THREAD

**Issue by ihackalot** [mehtadone/PTFeeder#42]
Actually, PTF is not happy with just knowing PairsLocation destination folder as documented, it needs (understandably) also PF .properties files. The point is that PTF assumes that those files are located in the parent directory of the trading folder, which is probably the case most of the times, but not always.

My docker setup for PF and PTF uses symlinks inside of the PF container, in order to bind mount both config and trading folders as volumes to provide some persistence (could eventually be data volumes). Then volumes are shared with the PTF container. Unfortunately, PTF is not happy with this setup, so when it steps back from the trading folder to find *.properties it finds nothing instead.

Is it possible to have an option inside hostsettings.json to define a custom location for PF config files that eventually falls back to the parent folder as default?

That would help a lot, otherwise, a docker setup is not possible.

**Comment by cmartin81** [comment]
I am running on docker and it works fine. When running they are configured with the same volume

**Comment by ihackalot** [comment]
Are you running both PT and PTF on docker? I do, and I share PT volumes (config and trading) with PTF. Sure fix is easy enough: mount all in one volume and make a folder structure that PTF will like, but it's ugly.

**Comment by grandmore** [comment]
@ihackalot I'm just about to setup feeder inside docker. 

Did you manage to get Telegraph to communicate from inside docker on ProfitTrailer. Mine will not work. It works on my laptop but not in the cloud.

Any pointers on doing feeder inside Docker? 
Fancy sharing your docker setup?

**Comment by ihackalot** [comment]
Telegram won't work on local network, but it will once you deploy.

**Comment by grandmore** [comment]
@ihackalot Did you have to add a ssl certificate to get it to work. My deployed one does not pass the message test but my laptop version does.

**Comment by ihackalot** [comment]
Nope, no ssl... Actually I closed all ports on my vps and use either openvpn or a socks tunnel to connect. I would never keep this dude publicly accessible.
BTW, please use discord for support. I don't wanna feel rude or anything man, it's just that I opened this issue to ask for a specific feature and we should not pollute it with other topics. Please use the support channel to get your questions answered. Thanks!

**Comment by grandmore** [comment]
I tunnel in as well on a vpn. 
Will use support thread instead.

**Comment by ketonatus** [comment]
I use ProfitTrailer on a NFS share (EFS on amazon). Maybe that helps ?
That way it is mounted on say: /nfshare/ProfitTrailer with all the files there for PTFeeder to access.

PFT runs from the share mind you, so i can run ptfeeder and trailer from 1 separate amazon instance.

**Comment by mehtadone** [comment]
Ability to change location of PT .properties files added in 1.3.4. Wiki page on hostsettings.json has the details on how to use it
