### ISSUE TITLE
Feeder cannot get BTC price from Bittrex, Binance or Polo or Any Coin Price Defaults to SuperBear

### ISSUE THREAD

**Issue by cryptroid** [mehtadone/PTFeeder#53]
See screen shots... I have tried everything, using different ports, restarting my computer and PT and PTF....help?

<img width="637" alt="screen shot 2018-01-13 at 12 43 41 pm" src="https://user-images.githubusercontent.com/35219101/34910059-98bb4504-f862-11e7-9f95-44dfa1c35162.png">
<img width="653" alt="screen shot 2018-01-13 at 12 51 30 pm" src="https://user-images.githubusercontent.com/35219101/34910060-98d3bfa8-f862-11e7-8b4c-010aa0621618.png">
<img width="950" alt="screen shot 2018-01-13 at 1 12 41 pm" src="https://user-images.githubusercontent.com/35219101/34910126-9920662c-f863-11e7-9c3e-18b3a171ecd8.png">

**Comment by mehtadone** [comment]
Check your timezone on your machine. If you are using windows, run something like timesynctool.com
