### ISSUE TITLE
Buys occur way to early into a down trend

### ISSUE THREAD

**Issue by chrismpalmer** [mehtadone/PTFeeder#54]
I understand the software attempts to solve a problem with its best efforts.

This could be related more towards Profit Trailer. However if Feeder can control a buy in certain scenarios then its a value add.

Frequently the bot buys way to early in a drop cycle. If your looking at it from a 5 minute chart thats fine it seems safe. But if you pulled back to an hour view you would see that the macd is way over the 0 line. I would suggest its very risky buying at the top of a Macd. If it wanted to purchase based on rule X it should take a look and defer it longer.... any Mac D below 0 is so much safer.... I am not an expert. But when I see it buy at high 1 hour Mac d....every time these are 4-6 level deep bags... Almost every time. Have a look for yourself.

**Comment by lutzleonhardt** [comment]
+1 full agree to take the MACD into account (maybe RSI as well)

**Comment by mehtadone** [comment]
Multiple indicators are coming directly in PT
