### ISSUE TITLE
IP Ban

### ISSUE THREAD

**Issue by rtom098** [mehtadone/PTFeeder#56]
Got an ip ban with 5min refresh on binance.
Did they set it up? Whats a good value then.

 openOrders - ERROR: -1003, Way too many requests; IP banned until 1515929738237

**Comment by mashuble** [comment]
Same for me

**Comment by ablankenship10** [comment]
Binance changed API weights for some calls that PT and or PTF use. Need to wait for an update from either or both teams. Shut your bots down in the meantime.

**Comment by mehtadone** [comment]
Api calls reduced in latest version
