### ISSUE TITLE
Pairs Offset is wrong ... 

### ISSUE THREAD

**Issue by Bertiger** [mehtadone/PTFeeder#57]
I had to do it now like you see in the code

https://pastebin.com/sYWmDQTd

it does not use the "general value" imo
i had to set  "MaxPairsOffset": "0" in boring to get my general value
otherwise, it would not have changed back in boring to 12 pairs

**Comment by github-4me** [comment]
+100

**Comment by mehtadone** [comment]
IS this still an issue as I cannot reproduce it?

**Comment by Bertiger** [comment]
Not not an issue anymore
