### ISSUE TITLE
Enhancement Request - SOM flag for 24h High

### ISSUE THREAD

**Issue by jalapeno777** [mehtadone/PTFeeder#58]
I would love to see a pair check that if a coin's current value is within a specified % of the 24h high for the day it will put that coin into sell only mode.  This would allow further protection from a large pump or unusual spike in price (such as from news) that doesn't have the support to stay at those levels.  The % would be based between the low and the high for the day. 

Or alternatively (or in addition to) a SOM flag for coins that have an incredibly high spread between the low and the high for the day might be an option as well.

**Comment by rww1313** [comment]
this is my issue.  the bot is buying after a pump way to early leaving me with large bags.

**Comment by mehtadone** [comment]
This can now be achieved with the HighLowPercentageChange to see how far away the price is from the average price
