### ISSUE TITLE
MIN_TRADE_REQUIREMENT_NOT_MET - What does this mean?

### ISSUE THREAD

**Issue by xs0crates** [mehtadone/PTFeeder#59]
I've been trying to figure out what this means, but I can't seem to find any info on it. Suddently the BTC bot stopped working and gave me that error. 

My speculation is that it output the error because BTC prices dropped, but again, I'm not sure since I can't find any info on it.

Could anyone clear this up? Thanks beforehand.

**Comment by mehtadone** [comment]
This is when your trade size is too small for the exchange. Have a look at the PT wiki for more details
