### ISSUE TITLE
SomOnlyPairs potential issue

### ISSUE THREAD

**Issue by neo302** [mehtadone/PTFeeder#65]
There may be an issue when parsing the pairs for SOMOnlyPairs. 
I noticed when the pair QWARK was in the list, it was also putting ARK in SOM as ARK is in the word QWARK.  ARK is not in the SOMOnlyPairs list.

**Comment by timh77** [comment]
Yes, there is. It was fine in previous version. I used the setting after @methadone told me to try it. 

Op 16 jan. 2018 03:56, om 03:56, neo302 <notifications@github.com> schreef:

**Comment by mehtadone** [comment]
Will be fixed in the next beta this evening
