### ISSUE TITLE
[REQ] Better FileStructure

### ISSUE THREAD

**Issue by Q-Rush** [mehtadone/PTFeeder#69]
Hi,

i would love to see a better filestructure. Currently its a pain in the a** to update the feeder via ssh.
Would be great if the dependencies could be separated into a /data folder.

thanks!

**Comment by github-4me** [comment]
+1

**Comment by njbrown09** [comment]
the problem is that PTFeeder uses dotnet core. Dotnet core publishing has terrible file structure

**Comment by ihackalot** [comment]
In your case I would just use git. Then whatever the update yo define locally you can simply `git push` to your origin.

**Comment by mehtadone** [comment]
All the dotnet have been removed from the normal build. They have been kept in for the rpi build as there is no SDK installer for the pi. Will slowly reduce the number of dependencies.
