### ISSUE TITLE
[REQUEST] Have pt-feeder detect config changes without restarting 

### ISSUE THREAD

**Issue by daryledesilva** [mehtadone/PTFeeder#70]
Hi, are there any plans to have pt feeder watch for config changes especially appsettings.json? kust like what pt is already doing. this is really useful in usecases where i have another script updating the appsettings.json automatically (like updating whitelists generated from a third party script i created)

**Comment by github-4me** [comment]
+1

**Comment by neo302** [comment]
Please 👍

**Comment by symbion6** [comment]
+1
Essential for a tool like this.
Having to restart after every minor settings change is starting to get pretty annoying.

**Comment by smoochy** [comment]
Yes, this would be really awesome to have

**Comment by Wackywoods** [comment]
Yip this is something that is really needed. having to reboot it every chance is frustrating. PT changes are picked up so sure the same can apply to PTF..
