### ISSUE TITLE
Could not work out...

### ISSUE THREAD

**Issue by crack00r** [mehtadone/PTFeeder#71]
I get 75% of all requests this error:

[08:10:11 WRN] Could not work out which market condition to use. Using the last one

**Comment by mehtadone** [comment]
This normally happens when the Market conditions are in the wrong order. Feel free to send me your appsettings.json as a pastebin.com on here or discord and I can have a look.

**Comment by crack00r** [comment]
Config: https://pastebin.com/ywz88d9g
Log: https://pastebin.com/pfaKeMVB

as you can see sometimes, it works, sometimes not

**Comment by crack00r** [comment]
as soon it switch settings, the bot buys again

**Comment by mehtadone** [comment]
What market condition should it be when the average change of the top coins have increased 5%?
