### ISSUE TITLE
Add the ability to manually set generals parameters in Pairs.txt file

### ISSUE THREAD

**Issue by nazbrok** [mehtadone/PTFeeder#77]
Hi,

My request is kind of the same as this issue #37 but more global.

Depending on the market state (bull, bear, ...) we might need to be able to change a lot more of parameters. For instance in bear mode maybe I want to enable only 3 pairs like I will want to use 15 in super bull.

I think if we add something in the pairs.txt, PTFeeder should just not generate this parameter. What we write in this file should be prioritary.

So that way we could specify different strategy, paris number and so one in the specific pairs.txt.

**Comment by mehtadone** [comment]
That particular example, you can do in PTF. 

See https://github.com/mehtadone/PTFeeder/wiki/appsettings.json---Offset-List

MaxPairsOffset
