### ISSUE TITLE
Windows Version looking for wrong boring file

### ISSUE THREAD

**Issue by DJRob** [mehtadone/PTFeeder#80]
It seems like the version 1.3.4.236 Windows is looking for the wrong boring.txt file. (see attached)
![ptfeedererror1](https://user-images.githubusercontent.com/23213456/35188079-095f5d1c-fdf5-11e7-8370-6422f8e86b6a.PNG)

**Comment by mehtadone** [comment]
The folder location is specified in the appsettings.json. It can be changed in that. Is this in the default settings?

**Comment by DJRob** [comment]
I got it figured out. I pasted an older version with 5 MarketConditions in the appsettings.json file instead of just the new 3 MarketConditions. My bad.
