### ISSUE TITLE
PTF will not collect trend price from exchanges if "MinutesToMeasureTrend" is set to 5

### ISSUE THREAD

**Issue by RichardLuo0506** [mehtadone/PTFeeder#81]
Works with 60min, 15min. If I set to 5, after a while it'll start returning NaN% change.

**Comment by mehtadone** [comment]
5 min candles are used to find historic data. Unfortunately some of the exchanges won't return information that far back in time if we go more grandular than that so at the moment, it is not possible to set a timeframe lower than 5 mins.
