### ISSUE TITLE
Map cost parameters to Profit Trailer

### ISSUE THREAD

**Issue by HeebyGeeby** [mehtadone/PTFeeder#82]
PT uses:
_ALL_max_cost = n_ or
_ALL_max_cost_percentage = n_

PTF uses:
_"Cost": "n"_ and
_"UseMaxCostPercentage": "true/false"_
Translating the values from PTF to PT. 

1. If a user sets _"Cost": "1"_ intending a 1% cost but incorrectly sets  _"UseMaxCostPercentage": "false"_ potentially leading to say a 1 BTC buy instead of a .01 BTC buy. 

2. If in the future, saves to config are applied to the bot immediately then the order in which a user changes these becomes very significant. 

3. Why move away from the PT standard of parameters? 

(Apologies if there is an excellent reason why it was done this way)

**Comment by mehtadone** [comment]
The reason for this was to abstract away some of the complexities of using %, but I agree that it has made it more complicated. PTF is anything but simple. 

I will look at getting it aligned up with PT again, but with the extra caveat of maintaining backward compatiblity now.
