### ISSUE TITLE
[Request] Separate app settings/dca folders on a per exchange basis

### ISSUE THREAD

**Issue by jalapeno777** [mehtadone/PTFeeder#83]
I find profit trailer (and as an extension of that PT Feeder) performs better using different settings on different exchanges.  For example binance has much higher volume so I tend to have the min. volume to be significantly higher than on polo or bittrex.  In addition trend tracking/dcas/tolerance etc are a bit different as well for better success rates.

I would love the ability to run a single instance of PT Feeder and have it adjust the PT files for an exchange specifically for that exchange rather than a blanket solution for all exchanges which typically has less than stellar results except for the exchange those settings work best on.

**Comment by SJT5** [comment]
Was about to request something similar, but possibly handled differently: a MinBuyVolumeOffset option per exchange.

**Comment by mehtadone** [comment]
Exchange offset added to 1.4
