### ISSUE TITLE
Max_cost and minbuybalance problems

### ISSUE THREAD

**Issue by Azizg** [mehtadone/PTFeeder#84]
Before i had only PT running and it was okay. I bought PTF after i saw many vids that were telling its awesome. I installed it and took some setting from some guys from Youtube actually these guys gave me an impetus to buy that PTF. After i made everything ready to run i started PT and PTF. It was okay. After i night i woke up and saw that nothing was trading beacuse i got one problem: increase max_cost at least to 0,002 or 0,001. My "Cost" setting is in percentage so it should be both for DCA and pairs but it looks like PT doesnt recognize this setting and continues telling i should increase it. Okay, i made many many things with these costs and finally it disappeared 

But then i ran into another problem "cannot buy XXXXBTC...." and saying something like it will exceed my minbuybalance and SHOWING EXACTLY THE SAME NUMBERS FOR ALL CURRENCIES" i tried many many things with these settings and finally it disappeared. 

After that again i came to a problem with max_cost - it appeared again . i deleted PT and PTF astarted all again from beggining copy pasted the "basic" srttings from that youtoube guy and again voila - max_cost proble, Please help me beacuse im somewhere between hitting my desktop with a stone and throwing it ot of window, 

Thank you

**Comment by XcidTrader** [comment]
Hi,

Those are all simple problems to fix, don’t worry.

Change your appsetting (found in PTf config) to not use percentages = false .

Then in hot config set an exact amount to trade with . And set you min balance to how much btc you want to hold back. 

That will get rid of your min and max issues

**Comment by Azizg** [comment]
help me to write that my head is just blowing up i dont know how to code-write that

**Comment by urbanfenix** [comment]
I'm having this same problem as well. I'm working on figuring it out.

**Comment by bkcrypto808** [comment]
Hi Azizg, 
is .003 for both minbuybalance and dcaminbuy balance reserving 3% of total BTC not to trade? I am having same issue.

**Comment by Azizg** [comment]
i guess yes

**Comment by Azizg** [comment]
actually my pt and ptf is working now

**Comment by Azizg** [comment]
i think i did it i will paste me settings for host and appsettings for ptf

**Comment by Azizg** [comment]
{
  "General": {
    "BaseCurrency": "BTC", // MARKET
       "BuyStrategy": "EMASPREAD", // ALL_buy_strategy
       "BuyValue": "-3", // ALL_buy_value
       "Cost": "0.0025", // ALL_max_cost or or All_max_cost_percentage
       "DcaEnabled": "-3", // ALL_DCA_enabled
       "DcaMaxBuySpread": "1", // max_buy_spread in DCA.properties
       "DcaMaxBuyTimes": "5", // max_buy_times in DCA.properties
       "DcaMaxCost": "0.0025", // max_cost in DCA.properties
       "DcaMinBuyBalance": "0.0025", // min_buy_balance in DCA.properties depending on UseMinBuyBalancePercentage in hostsettings.json
       "DcaSellTrigger": "0.6", // sell_trigger in DCA.properties
       "DcaSellStrategy": "GAIN", // sell_strategy in DCA.properties
       "DcaSellValue": "0.75", // sell_value in DCA.properties
       "DcaTrailingBuy": "0.15", // trailing_buy in DCA.properties
       "DcaTrailingProfit": "0.15", // trialing_profit in DCA.properties
       "ExcludedPairs": "BNB", // coins you don't want PTF to create settings for. These will have no config generated and will appear in watchmode
       "SomOnlyPairs": "BURST,ZEC,SAFEX,BNB,BTS,BTA,DAR,DRACO,SLING,CRYPT,DOGE,UNO,SC,INCNT,NAUT,SJCX,NOTE,TKN,TIME,TRIG,MTL,DGD,DCT,CPC,FLDC,COVAL,BTCD,BCY,AUR,GLD,XMG,GBYTE,NBT,AMP,EXCL,BLK,SLS,SYNX,PKB,FLO,RISE,1ST,CLUB,QWARK,GBG,RCN,EMC2,GRS,QRL,BITB,2GIVE,BLITZ,ERC,EGC,FAIR", // these are coins where BASE_COIN_sell_only_mode will be true
       "DcaExcluded": "", // coins you don't want DCA enabled for no matter what
       "MaxBuySpread": "1", // All_max_buy_spread
       "MaxTrailingBuy": "0.3", // All_trailing_buy
       "MaxTrailingProfit": "0.3", // All_tailing_profit
       "MinBuyBalance": "0.0025", // All_min_buy_balance or All_min_buy_balance_percentage
       "MinBuyPrice": "0.00005", // All_min_buy_price
       "MinBuyVolume": "150", // All_min_buy_volume
       "MinProfit": "0.55", // All_min_profit
       "MinTrailingBuy": "0.01", // minumum the trailing buy after offsets can be
       "MinTrailingProfit": "0.01", // minumum the trailing buy after offsets can be
       "MinutesForLongerTermTrend": "720", // minutes to measure trend for LongerTermPriceChange
       "MinutesToMeasureTrend": "60", // minutes to measure trend for base coin trend, PriceTrendChange and volatility calc
       "NumberOfPairs": "15", // ALL_max_trading_pairs
       "SellStrategy": "GAIN", // ALL_sell_strategy
       "SellValue": "0.75", // ALL_sell_value
       "TopCurrenciesToCheck": "35" // number of pairs to check from your exchange for MaxTopCoinAverageChange
  },
  "MarketConditions": {
    "Configs": [
      {
        "FolderName": "01-superbear",
        "MaxTopCoinAverageChange": "-2",
        "BuyValueOffset": "-200",
        "TrailingProfitOffset": "-20",
        "SellValueOffset": "-30",
        "MinProfitOffset": "-20",
        "MaxBuySpreadOffset": "-20"
      },
      {
        "FolderName": "02-bear",
        "MaxTopCoinAverageChange": "-0.5",
        "DcaTrailingBuyOffset": "25",
        "DcaTrailingProfitOffset": "-25",
        "DcaSellValueOffset": "-10",
        "BuyValueOffset": "-100",
        "MaxPairsOffset": "-20",
        "MaxBuySpreadOffset": "-20"
      },
      {
        "FolderName": "03-boring",
        "MaxTopCoinAverageChange": "2.5"
      },
      {
        "FolderName": "04-bull",
        "MaxTopCoinAverageChange": "5",
        "DcaTrailingBuyOffset": "-10",
        "DcaTrailingProfitOffset": "10",
        "DcaSellValueOffset": "10"
      },
      {
        "FolderName": "05-superbull",
        "MaxTopCoinAverageChange": "1000",
        "DcaTrailingBuyOffset": "-20",
        "DcaTrailingProfitOffset": "20",
        "DcaSellValueOffset": "20",
        "MinBuyBalanceOffset": "5",
        "MaxPairsOffset": "20"
      }
    ]
  },
  "Price": {
    "Configs": [
      {
        "MaxPrice": "0.0001",
        "BuyValueOffset": "-50",
        "CostOffset": "-5"
      },
      {
        "MaxPrice": "0.0005",
        "BuyValueOffset": "-50",
        "CostOffset": "-5"
      }
    ]
  },
  "Volume": {
    "Configs": [
      {
        "MaxVolume": "100",
        "BuyValueOffset": "-30",
        "CostOffset": "-20"
      },
      {
        "MaxVolume": "500",
        "BuyValueOffset": "-20",
        "CostOffset": "-10"
      },
      {
        "MaxVolume": "1000",
        "MinBuyBalanceOffset": "-20"
      }
    ]
  },
  "PriceTrendChange": {
    "Configs": [
      {
        "MaxPriceTrendPercentageChange": "-5",
        "BuyValueOffset": "-10",
        "TrailingProfitOffset": "-10",
        "SellValueOffset": "-30",
        "MaxBuySpreadOffset": "-20"
      },
      {
        "MaxPriceTrendPercentageChange": "-2",
        "BuyValueOffset": "100",
        "CostOffset": "5",
        "SellValueOffset": "-10"
      },
      {
        "MaxPriceTrendPercentageChange": "5"
      },
      {
        "MaxPriceTrendPercentageChange": "20",
        "TrailingBuyOffset": "-25",
        "TrailingProfitOffset": "5"
      },
      {
        "MaxPriceTrendPercentageChange": "15000",
        "BuyValueOffset": "-10",
        "TrailingProfitOffset": "-10",
        "SellValueOffset": "-30",
        "MaxBuySpreadOffset": "-20"
      }
    ]
  },
  "LongerTermPriceChange": {
    "Configs": [
      {
        "MaxPriceTrendPercentageChange": "-10",
        "BuyValueOffset": "-10",
        "TrailingProfitOffset": "-10",
        "SellValueOffset": "-30",
        "MaxBuySpreadOffset": "-20"
      },
      {
        "MaxPriceTrendPercentageChange": "10"
      },
      {
        "MaxPriceTrendPercentageChange": "10000",
        "BuyValueOffset": "-10",
        "TrailingProfitOffset": "-10",
        "SellValueOffset": "-30",
        "MaxBuySpreadOffset": "-20"
      }
    ]
  },
  "AverageCandleSize": {
    "Configs": [
      {
        "MaxPercentageSizeOfPrice": "0.025",
        "SellOnlyMode": "true",
        "SellValueOffset": "-30"
      }
    ]
  }
}

**Comment by Azizg** [comment]
{
  "Host": {
    "TrexPairsLocation": "",
    "PoloPairsLocation": "",
    "BinancePairsLocation": "",
    "LicenseKey": "",
    "ServerUrls": "http://localhost:8083",
    "MarketConditionCheckInMinutes": "3",
    "CalculateTrailingValues": "true",
    "UseMaxCostPercentage": "false",
    "UseMinBuyBalancePercentage": "false",
    "TelegramBotId": "",
    "TelegramChatId": ""
  },
  "Serilog": {
    "MinimumLevel": "Debug"
  }
}

**Comment by bkcrypto808** [comment]
Thanks, I assume you are not using PFeeder?

**Comment by nexenta81** [comment]
Hi guys, I was able to get a decent config for BTC Market but I cant get PTFeeder to work for USDT market.. Do you happen to have a basic PRFeeder config for USDT? Thanks a lot!
