### ISSUE TITLE
Losing cost basis

### ISSUE THREAD

**Issue by bkcrypto808** [mehtadone/PTFeeder#86]
Hi, 
I am getting more of these types on multi DCA .... Please setENGBTC_bought_price or  2018-01-22 19:13:39 INFO AverageCalculator - Please set ARKBTC_bought_price ....PT I assume will have a hard time selling , anyone know the syntax in hotconfig or PT to update price?

**Comment by mehtadone** [comment]
This is a PT question. If you have a look at the PT wiki or on the PT discord, I'm sure someone can help
