### ISSUE TITLE
Map Price Bought

### ISSUE THREAD

**Issue by hozdil** [mehtadone/PTFeeder#89]
Hi,

Is it possible to map the bought price in order to solve issue in Trailer like:
"AverageCalculator - Please set IOTABTC bought price"

I tried by adding 
IOTABTC_bought_price = 0.00013740 
in Feeder Pairs.properties. 

It appears well in the generated config in Trailer but it looks like it doesn't get it.

Thanks

**Comment by mehtadone** [comment]
You need to use hotconfig now: https://wiki.profittrailer.io/doku.php/hotconfig
