### ISSUE TITLE
Add Ability to SOM or DCA a coin based on coin %

### ISSUE THREAD

**Issue by Pr0fess0rCha0s** [mehtadone/PTFeeder#91]
Hey,

I think it would be good to give us the option to allow us to query the 24 hour % and then to configure a SOM or DCA based on that %.  If a coin hits 40% then there seems to be a higher chance it will tank the next day.  It would be nice to automatically catch that trend.  Just having an option in the appsettings like PriceTrendChange, but also have PriceCoinChange or something.  

Thoughts?

Thanks!

**Comment by mehtadone** [comment]
This already exists. https://github.com/mehtadone/PTFeeder/wiki/appsettings.json---Offset-List

Please reopen the issue if this is not exactly what you are looking for.

**Comment by Pr0fess0rCha0s** [comment]
Hey...Thanks for the response.  I was working on this tonight.  I'm wanting more of the 24H% percent column that is based on Binance.  For instance, if I wanted all my coins lower than 10% of the 24 hour price change of that coin from Binance, I was trying to do something like this:

 "PriceTrendChange": {
    "Configs": [
        {
        "MaxPriceTrendPercentageChange": "-10",
        "DcaEnabled": "false",
	"SellOnlyMode": "true"
      },

However, this looks like it is making everything from my pairs profit % and doing things with that.  I just want to clarify.  Is there a way to take the 3rd column labeled 24H% and do something with that number?

Thanks!!
