### ISSUE TITLE
Paring response from bittrex: NULL

### ISSUE THREAD

**Issue by MGData64** [mehtadone/PTFeeder#93]
The log file is showing the below error every 3 minutes when PTF does a search. The feeder works and no other errors are reported except the below. 
[time: ERR] Handled Exception: when parsing response from bittrex: Value cannot be null.   

Issue on: 
PTF version: pt-feeder-v1.3.4.236 Build 2,3 & 4
Host: Linux  Ubuntu 16.x
VPS: Germany 
Error: [time: ERR] Handled Exception: when parsing response from bittrex: Value cannot be null.

**Comment by mehtadone** [comment]
This is normally when the API is sending out incorrect data. Is this fixed now?
