### ISSUE TITLE
Question 1 feeder license 2 bots on Binance

### ISSUE THREAD

**Issue by Gitulu** [mehtadone/PTFeeder#94]
Hi guys, 

Just a short question is it possible to use the feeder with 2 bots both on Binance?
Binance works well on the same RIG with two different accounts.
Because 1 feeder license can update 4 exchanges but in the config Binance is listed only one time.

Thanks a lot

**Comment by mehtadone** [comment]
You can't use the same installation of binance but you can run multiple instances of feeder.

**Comment by Gitulu** [comment]
Hello mehtadone,

Thank you for your feedback.

This is a good workaround but with two instances of the bot on Binance and two feeders this will maybe result in an IP ban?

It would be better to get an feature in the hosting file like "BinancePairsLocation" and "BinancePairsLocation2".

Or I´m wrong with to much API calls?

An other idea can be a macro and copy the content from 1 folder to the other bot but this is not synchron.

Thank you
