### ISSUE TITLE
Formatting pairs file. Owned coins listed first

### ISSUE THREAD

**Issue by Brisco00** [mehtadone/PTFeeder#97]
Currently it is difficult to located owned coins in the generated pairs file if I want to review their configuration generated by PTF.

New setting: Format_Pairs_File = true/false

When enabled the coins section of the pairs file is formatted into sections. 

1st all owned coins
2nd all coins deemed tradeable (SOM = False)
3rd all coins deemed non tradeable (SOM = True)
Each section has applicable coins sorted a-z
Each section could also be titled with a commented summary giving the # of coins contained

**Comment by mehtadone** [comment]
This is not going to be possible as PT Feeder does not know of any positions that PT might be holding. Its totally agnostic and only works off market data, and not what you currently hold and their states.
