### ISSUE TITLE
Autoblacklist new coins

### ISSUE THREAD

**Issue by cmartin81** [mehtadone/PTFeeder#98]
New coins will often fall quite a lot before it stabilizes. These coins should be blacklisted for a small period of time. When it is falling PT is picking up this coins as a possible buy.  

There has been made a plugin for this, but it only supports PT and Binance.
https://github.com/bennettca/ProfitTrailer-new-binance-listings

**Comment by mehtadone** [comment]
Duplicate: https://github.com/mehtadone/PTFeeder/issues/100
