### ISSUE TITLE
LowBB buying at 50% of BB when settings at 8-16%

### ISSUE THREAD

**Issue by mrdan89** [mehtadone/PTFeeder#99]
Hi, 
Please see attached my trade for CDT that was meant to be bought at the bottom of the BB but was bought in the middle. Any idea why this was caused by a bug?

I was watching the possible buys, had none "true trailing" and all sell triggers were at "12", and suddenly boom, a buy and i found that it was in the middle of the BB. 

![image](https://user-images.githubusercontent.com/35910235/35493923-d122c804-04f1-11e8-9d31-91b3d7b03ab3.png)
![image](https://user-images.githubusercontent.com/35910235/35493928-e017c472-04f1-11e8-814d-347eb3426e33.png)

[zip.zip](https://github.com/mehtadone/PTFeeder/files/1672224/zip.zip)

**Comment by mehtadone** [comment]
Hi, PT Feeder doesn't do any buying or selling. I think you need to raise this on the PT github.

**Comment by mrdan89** [comment]
i raised this in both PT & PTFeeder telegram and was directed here. :( ok i will try the PT github now. Thank you.
